"""EN + CS copy for the Settings section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "Settings",
        "title": "Settings",
        "subtitle": "Pick your AI provider, store API keys safely on your computer, tune defaults.",

        "provider_card_title": "AI provider & model",
        "provider_card_desc": "Each AI section uses these defaults. Sections may override the model from their own UI.",
        "provider_label": "Provider",
        "provider_openai": "OpenAI",
        "provider_anthropic": "Anthropic",
        "model_label": "Model",
        "model_hint": "Pick from the list or type your own model id.",
        "model_save": "Save model",
        "model_saved": "Saved",
        "model_invalid": "Model id can't be empty.",

        "keys_card_title": "API keys",
        "keys_card_desc_template": "Keys are stored in {keystore} on this computer. We never send them anywhere except to the provider you call.",
        "key_openai_label": "OpenAI API key",
        "key_openai_hint": "Starts with sk-...",
        "key_anthropic_label": "Anthropic API key",
        "key_anthropic_hint": "Starts with sk-ant-...",
        "key_github_label": "GitHub personal access token",
        "key_github_hint": "Read-only token. Optional - lets AI Career fetch your public repos with a higher rate limit.",
        "key_save_btn": "Save",
        "key_delete_btn": "Delete",
        "key_status_set": "Saved securely",
        "key_status_unset": "Not set",
        "key_save_empty": "Paste a key first.",
        "key_save_ok": "Saved.",
        "key_save_failed": "Could not save - the OS keystore is unavailable.",
        "key_delete_ok": "Deleted.",
        "key_delete_failed": "Nothing to delete.",
        "key_show_btn": "Show",
        "key_hide_btn": "Hide",

        "general_card_title": "General",
        "general_demo_default_label": "Start AI Career runs in Demo mode",
        "general_demo_default_desc": "When on, the analysis uses local mock data instead of calling the AI - useful for screenshots and offline work.",

        "logs_card_label": "Debug logs",
        "logs_card_desc": "We write a small rolling log file when something goes wrong (silent click, failed save, etc.). Use it to copy or clear the file.",
        "logs_view_btn": "View logs",
        "logs_open_folder_btn": "Open log folder",
        "logs_copy_btn": "Copy",
        "logs_copy_done": "Logs copied to clipboard.",
        "logs_copy_failed": "Could not copy the logs.",
        "logs_clear_btn": "Clear",
        "logs_clear_done": "Log file cleared.",
        "logs_clear_failed": "Could not clear the log file.",
        "logs_refresh_btn": "Refresh",
        "logs_back_btn": "Back to settings",
        "logs_view_title": "Debug logs",
        "logs_view_desc": "Tail of the current ~/AI Hub/logs/app.log. Older lines roll into app.log.1 / .2 / .3.",
        "logs_path_template": "Log file: {path}",
        "logs_empty": "No log entries yet. Use the app for a moment and refresh.",
        "logs_selection_hint": "Tip: drag with the mouse to select multiple lines, then press Ctrl+C - or use the Copy button to grab the whole file.",

        "vault_unavailable_title": "OS keystore is not reachable",
        "vault_unavailable_desc": "On Linux you may need to install gnome-keyring or kwallet. Until a backend is reachable, API keys can't be saved.",

        "ctx_quick_actions": "Quick actions",
        "ctx_qa_test_openai": "Test OpenAI key",
        "ctx_qa_test_anthropic": "Test Anthropic key",
        "ctx_qa_open_settings_file": "Open settings folder",

        "test_running": "Testing...",
        "test_ok": "Connection OK.",
        "test_no_key": "Save the key first.",
        "test_failed": "Failed: {error}",
    },
    "cs": {
        "nav_label": "Nastavení",
        "title": "Nastavení",
        "subtitle": "Vyber AI providera, ulož si API klíče bezpečně na svém počítači a uprav výchozí volby.",

        "provider_card_title": "AI provider & model",
        "provider_card_desc": "Tyto volby používají všechny AI sekce. Konkrétní sekce si může model přepsat ze svého UI.",
        "provider_label": "Provider",
        "provider_openai": "OpenAI",
        "provider_anthropic": "Anthropic",
        "model_label": "Model",
        "model_hint": "Vyber ze seznamu nebo napiš vlastní identifikátor.",
        "model_save": "Uložit model",
        "model_saved": "Uloženo",
        "model_invalid": "Identifikátor modelu nesmí být prázdný.",

        "keys_card_title": "API klíče",
        "keys_card_desc_template": "Klíče se ukládají do {keystore} na tomto počítači. Posílají se jen tomu providerovi, kterého voláte.",
        "key_openai_label": "OpenAI API klíč",
        "key_openai_hint": "Začíná na sk-...",
        "key_anthropic_label": "Anthropic API klíč",
        "key_anthropic_hint": "Začíná na sk-ant-...",
        "key_github_label": "GitHub personal access token",
        "key_github_hint": "Read-only token. Volitelné - umožní AI Career stáhnout vaše veřejné repozitáře s vyšším limitem.",
        "key_save_btn": "Uložit",
        "key_delete_btn": "Smazat",
        "key_status_set": "Uloženo bezpečně",
        "key_status_unset": "Nenastaveno",
        "key_save_empty": "Nejdřív vlož klíč.",
        "key_save_ok": "Uloženo.",
        "key_save_failed": "Nepovedlo se uložit - úložiště OS není dostupné.",
        "key_delete_ok": "Smazáno.",
        "key_delete_failed": "Není co smazat.",
        "key_show_btn": "Zobrazit",
        "key_hide_btn": "Skrýt",

        "general_card_title": "Obecné",
        "general_demo_default_label": "Spustit AI Career analýzu v Demo režimu",
        "general_demo_default_desc": "Když je zapnuté, analýza používá lokální mock data místo volání AI - hodí se na screenshoty a offline práci.",

        "logs_card_label": "Debug logy",
        "logs_card_desc": "Když se něco pokazí (kliknutí bez efektu, neúspěšné uložení atd.), zapisuje se to do malého log souboru. Tady ho můžeš zkopírovat nebo vymazat.",
        "logs_view_btn": "Zobrazit logy",
        "logs_open_folder_btn": "Otevřít složku s logy",
        "logs_copy_btn": "Zkopírovat",
        "logs_copy_done": "Logy zkopírovány do schránky.",
        "logs_copy_failed": "Nepodařilo se zkopírovat logy.",
        "logs_clear_btn": "Vymazat",
        "logs_clear_done": "Log soubor vymazán.",
        "logs_clear_failed": "Log soubor nelze vymazat.",
        "logs_refresh_btn": "Obnovit",
        "logs_back_btn": "Zpět do nastavení",
        "logs_view_title": "Debug logy",
        "logs_view_desc": "Konec aktuálního ~/AI Hub/logs/app.log. Starší záznamy se odlévají do app.log.1 / .2 / .3.",
        "logs_path_template": "Log soubor: {path}",
        "logs_empty": "Zatím žádné záznamy. Chvilku appku používej a klikni Obnovit.",
        "logs_selection_hint": "Tip: označ víc řádků myší a stiskni Ctrl+C - nebo tlačítkem Zkopírovat zkopíruj celý soubor.",

        "vault_unavailable_title": "Úložiště OS není dostupné",
        "vault_unavailable_desc": "Na Linuxu může chybět gnome-keyring nebo kwallet. Dokud nebude backend dostupný, API klíče nelze uložit.",

        "ctx_quick_actions": "Rychlé akce",
        "ctx_qa_test_openai": "Otestovat OpenAI klíč",
        "ctx_qa_test_anthropic": "Otestovat Anthropic klíč",
        "ctx_qa_open_settings_file": "Otevřít složku s nastavením",

        "test_running": "Testuji...",
        "test_ok": "Spojení OK.",
        "test_no_key": "Nejdřív klíč ulož.",
        "test_failed": "Neúspěch: {error}",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
