"""EN + CS copy for the AI Career section (HR-expert flow)."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI CV / Career",
        "title": "AI CV / Career",
        "subtitle": "Tailor your CV to a job posting, write a cover letter, and prepare for the interview.",

        "mode_chat": "Chat",
        "mode_form": "Form mode",
        "mode_chat_short": "Chat",
        "mode_form_short": "Form",
        "mode_toggle_tooltip": "Switch between conversational chat and the structured form-mode flow.",

        "tab_setup": "Setup",
        "tab_match": "Match",
        "tab_documents": "Documents",
        "tab_history": "History",

        "tab_setup_desc": "Position + profile",
        "tab_match_desc": "Score + evidence",
        "tab_documents_desc": "CV + cover letter + export",
        "tab_history_desc": "Previous analyses",
        "stage_status_waiting": "Waiting",
        "stage_status_active": "Active",
        "stage_status_done": "Done",

        "setup_hero_title": "Build a tailored application",
        "setup_hero_desc": "Drop a job posting and your resume. Everything else is optional - the more context you give, the more accurate the match report and generated documents.",

        "step_1_label": "STEP 1",
        "step_1_title": "Job posting",
        "step_1_desc": "Pull the description from a URL or paste it below.",
        "job_url_hint": "https://example.com/jobs/qa-engineer",
        "job_url_btn": "Fetch",
        "job_url_running": "Fetching...",
        "job_url_failed": "Could not download the page. Paste the text below instead.",
        "job_text_hint": "Paste the job posting here, or click Fetch above.",

        "step_2_label": "STEP 2",
        "step_2_title": "Resume & profile",
        "step_2_desc": "Drop your resume (mandatory) and optionally a LinkedIn export.",
        "resume_label": "Resume (PDF / DOCX / TXT / HTML) - required",
        "resume_drop_title": "Drop your resume here",
        "resume_drop_hint": "or click to browse the disk",
        "resume_no_file": "No file selected",
        "resume_unsupported": "Unsupported file type. Use PDF, DOCX, TXT or HTML.",
        "resume_browse_btn": "Browse...",
        "resume_clear_btn": "Clear",

        "linkedin_label": "LinkedIn export (PDF / TXT / HTML) - optional",
        "linkedin_drop_title": "Drop your LinkedIn export here",
        "linkedin_drop_hint": "Optional - click to browse",
        "linkedin_no_file": "No file selected",
        "upload_paste_path_btn": "Paste path",
        "upload_paste_path_tooltip": "Tip on Windows: Shift+Right-click a file in Explorer -> Copy as path, then click here.",
        "upload_cta_label": "Click to browse",

        "step_3_label": "STEP 3",
        "step_3_title": "GitHub profile",
        "step_3_desc": "Drop in your GitHub URL and we will pull your public repos automatically (token from Settings if present, anonymous otherwise).",
        "github_url_hint": "https://github.com/your-username (or just username)",
        "github_skip_label": "Skip GitHub - do not fetch any repos",
        "github_token_note_authenticated": "Using your GitHub token from Settings - 5000 requests / hour.",
        "github_token_note_anonymous": "No GitHub token saved - using the anonymous limit (60 requests / hour by IP). Save a token in Settings to lift the limit.",
        "github_status_loaded_template": "Loaded {count} public repositories from @{username}.",
        "github_status_failed_template": "GitHub fetch failed: {error}",

        "footer_followup_label": "Ask clarifying questions before running",
        "footer_followup_desc": "AI surfaces unclear items (e.g. 'Have you worked with Python?') and pauses for your answers.",
        "footer_run_btn": "Run analysis",
        "footer_run_running": "Running analysis...",
        "footer_run_followups_running": "Looking for unclear items...",
        "footer_run_match_running": "Scoring the match...",
        "run_disabled_hint": "Add a resume and a job posting to run the analysis.",

        "followup_title": "Quick clarifying questions",
        "followup_intro": "Before scoring, the AI spotted a few items in the job description that aren't crystal clear from your resume. Answer the ones you can - skip the rest.",
        "followup_answer_hint": "Your answer (1-2 sentences). Leave empty to skip this question.",
        "followup_skip_all": "Skip all",
        "followup_cancel": "Back to setup",
        "followup_continue": "Continue with analysis",
        "followup_no_questions": "Resume already covers the job description - no follow-ups needed.",
        "followup_other_label": "Other",
        "followup_other_hint": "Type your own answer here...",

        "error_no_keystore": "API keys cannot be saved on this machine - the OS keystore is unavailable. Try Demo mode for an offline preview.",
        "error_no_key_template": "Your {provider} API key is not saved yet. Open Settings to add it, or switch to Demo mode.",

        "match_title": "Match",
        "match_subtitle": "How strong is the candidate-role fit?",
        "match_overall_label": "OVERALL",
        "match_per_category_hint": "Hover a category title to see how AI scored it.",
        "match_matches_title": "MATCHES",
        "match_gaps_title": "GAPS / RISKS",
        "match_ats_title": "ATS KEYWORDS",
        "match_ats_present_label": "Present",
        "match_ats_missing_label": "Missing",
        "match_evidence_title": "EVIDENCE PREVIEW",
        "match_open_documents_btn": "Generate documents",
        "match_generating_documents": "Generating documents... (this can take a minute)",
        "docs_lang_dialog_title": "Document language",
        "docs_lang_dialog_desc": "Choose the language for generated documents.",
        "docs_lang_option_cs": "Czech (CS)",
        "docs_lang_option_en": "English (EN)",
        "docs_lang_dialog_cancel": "Cancel",
        "docs_lang_dialog_confirm": "Continue",
        "match_no_results_title": "No analysis yet",
        "match_no_results_desc": "Open Setup, drop your resume + job posting, then click Run analysis.",
        "match_verdict_label": "Verdict",

        "doc_title": "Documents",
        "doc_subtitle": "Review and edit each document. Export takes the text exactly as you see it.",
        "doc_tab_tailored_cv": "Tailored CV",
        "doc_tab_modern_cv": "Modern CV",
        "doc_tab_cover_letter": "Cover letter",
        "doc_tab_match_report": "Match report",
        "doc_tab_interview_prep": "Interview prep",
        "doc_tab_skill_gap": "Skill gap plan",
        "doc_tab_evidence": "Evidence (GitHub only)",

        "doc_empty_title": "Document is empty",
        "doc_empty_desc": "Click Generate to ask the AI to write this document from your match analysis.",
        "doc_generate_btn": "Generate",
        "doc_regenerate_btn": "Regenerate",
        "doc_running": "Generating...",

        "problem_label_template": "Problem {n}",
        "problem_hint": "Problem {n}: what is wrong or missing?",
        "add_problem_btn": "+ Add another problem",
        "refine_btn": "Refine with AI",
        "refine_running": "Refining...",

        "doc_back_btn": "Back to match",
        "export_md_btn": "Export MD",
        "export_html_btn": "Export HTML",
        "export_docx_btn": "Export DOCX",
        "export_pdf_btn": "Export PDF",
        "export_all_btn": "Save complete analysis",
        "export_ok_template": "Saved to {path}",
        "export_failed_template": "Export failed: {error}",
        "export_running": "Saving...",

        "doc_change_color_btn": "Change colour",
        "doc_change_layout_btn": "Change layout",
        "doc_theme_color_label": "Colour: {name}",
        "doc_theme_layout_label": "Layout: {name}",
        "doc_layout_two_column_sidebar": "Two-column sidebar",
        "doc_layout_single_column_serif": "Single column (serif)",
        "doc_layout_single_column_minimal": "Single column (minimal)",
        "doc_layout_centered_header_band": "Centred header banner",

        "history_title": "History",
        "history_subtitle": "Previous analyses are kept on disk so you can re-open them.",
        "history_empty_title": "No analyses yet",
        "history_empty_desc": "Run your first analysis from Setup and it will appear here.",
        "history_open_folder_btn": "Open documents folder",
        "history_open_app_btn": "Open in app",
        "history_refresh_btn": "Refresh",
        "history_loaded_from_template": "Reading from {path}",
        "history_score_label": "Score",

        "ctx_cost_title": "Session cost",
        "ctx_cost_calls_template": "{calls} calls · {tokens} tokens",
        "ctx_cost_session_template": "~${cost:.2f} this session",
        "ctx_activity_title": "Activity",
        "ctx_activity_ready": "Ready",
        "ctx_activity_scraping": "Fetching...",
        "ctx_activity_parsing": "Parsing files...",
        "ctx_activity_analyzing": "Analyzing...",
        "ctx_activity_followups": "Looking for unclear items...",
        "ctx_activity_waiting_user": "Waiting for your clarifications...",
        "ctx_activity_generating": "Generating...",
        "ctx_activity_exporting": "Exporting...",
        "ctx_activity_error": "Error",
        "ctx_quick_actions_title": "Quick actions",
        "ctx_qa_new_run": "New analysis",
        "ctx_qa_show_history": "Show history",
        "ctx_qa_open_how_to": "How to use this assistant",
        "menu_new_run": "New analysis",
        "menu_save_full": "Save complete analysis",
        "menu_open_folder": "Open documents folder",
        "menu_show_history": "Show history",
        "menu_how_to": "How to use this assistant",
        "menu_demo_load": "Show demo data",
        "menu_demo_clear": "Hide demo data",
        "demo_pill": "DEMO",
        "menu_save_no_run": "Run an analysis first - there is nothing to save yet.",
        "menu_save_running": "Saving complete analysis...",
        "menu_save_done_template": "Saved to {path}",
        "menu_open_folder_no_run": "No documents folder yet - generate and save the analysis first.",
        "ctx_provider_template": "{provider} · {model}",
        "ctx_run_status_idle": "Pre-flight",
        "ctx_run_status_active": "Run in progress",
        "ctx_run_status_done": "Run finished",

        "how_to_title": "How to use this assistant",
        "how_to_section_what": "What this section does",
        "how_to_what_text": "AI Career compares your resume against a specific job posting and produces an honest match report, a tailored CV, a cover letter, an interview-prep brief, and a skill-gap plan you can act on. Everything is grounded in the candidate evidence you provided - the AI is forbidden from inventing facts.",
        "how_to_section_inputs": "Inputs you should prepare",
        "how_to_inputs_text": "Drop your resume (PDF, DOCX, TXT or HTML) and either paste or fetch the job posting URL. Optionally drop a LinkedIn export and add your GitHub username for richer evidence. The more context you give, the better the match report.",
        "how_to_section_quality": "Quality tips",
        "how_to_quality_text": "Pick the cheapest model that gives you good output (gpt-5.4-mini is the default sweet spot). Save your OpenAI / Anthropic / GitHub keys in Settings - they go straight into the OS keystore. Use Demo mode to walk through the entire flow before you spend a token.",
        "how_to_close": "Got it",

        "chat_intro_text": "I'm your HR-side assistant. Once the match analysis is ready, ask me anything about the role, your gaps, or how to phrase a specific bullet.",
        "chat_send_hint": "Ask about the role, the gaps, the bullets...",

        "chat_mode_greeting": "Hi! I'm your HR career assistant. Tell me what you want to work on - tailor a CV to a specific role, draft a cover letter, prep for an interview, or sanity-check your LinkedIn. You can paste a job description or attach your CV at any time.",
        "chat_mode_send_hint": "Type your message... (e.g. \u201eI'm applying for a Frontend Engineer role at QualityWorks\u201c)",
        "chat_mode_input_attach": "Attach CV / job posting (PDF, DOCX, TXT, MD, HTML)",
        "chat_attachments_label": "Attachments",
        "chat_placeholder": "Ask about the role, your gaps, how to phrase a bullet...",
        "chat_running": "Thinking...",
        "chat_mode_input_clear": "Clear conversation",
        "chat_mode_attached_template": "Attached: {name}",
        "chat_mode_drop_hint": "Click here to attach a CV or job description (PDF, DOCX, TXT)",
        "chat_mode_attachment_remove": "Remove attachment",
        "chat_mode_paste_tooltip": "Paste from clipboard",
        "chat_mode_paste_done": "Pasted {chars} characters from the clipboard.",
        "chat_mode_paste_empty": "Clipboard is empty - copy something first.",
        "chat_mode_paste_failed": "Could not read the clipboard.",
        "chat_mode_running": "Thinking...",
        "chat_mode_error_template": "Chat failed: {error}",
        "chat_mode_quick_action_cv": "Generate a tailored CV for the role",
        "chat_mode_quick_action_letter": "Draft a cover letter",
        "chat_mode_quick_action_interview": "Prepare for the interview",
        "chat_mode_quick_action_gaps": "Show my biggest gaps",
        "chat_mode_attached_docs_title": "Attached documents",
        "chat_mode_no_attachments": "No documents attached yet.",
        "chat_mode_clear_btn": "Clear chat",
        "chat_mode_open_form_btn": "Open Form mode",
        "chat_mode_history_title": "Recent conversations",
        "chat_mode_history_empty": "Past chats appear here once you save them.",

        "qa_run_now": "Run analysis",
        "qa_open_match": "Open match report",
        "qa_open_documents": "Open documents",

        "doc_no_evidence_title": "Evidence document not available",
        "doc_no_evidence_desc": "Add your GitHub username in Setup to enable the Evidence document.",

        "ats_label_yes": "in resume",
        "ats_label_no": "not in resume",

        "history_run_role_template": "{role}",
        "history_run_company_template": "{company}",
    },
    "cs": {
        "nav_label": "AI Životopis / Kariéra",
        "title": "AI Životopis / Kariéra",
        "subtitle": "Přizpůsob životopis na konkrétní inzerát, napiš motivační dopis a připrav se na pohovor.",

        "mode_chat": "Chat",
        "mode_form": "Formulářový režim",
        "mode_chat_short": "Chat",
        "mode_form_short": "Formulář",
        "mode_toggle_tooltip": "Přepni mezi konverzačním chatem a strukturovaným formulářovým režimem.",

        "tab_setup": "Nastavení",
        "tab_match": "Shoda",
        "tab_documents": "Dokumenty",
        "tab_history": "Historie",

        "tab_setup_desc": "Pozice + profil",
        "tab_match_desc": "Skóre + důkazy",
        "tab_documents_desc": "Životopis + dopis + export",
        "tab_history_desc": "Předchozí analýzy",
        "stage_status_waiting": "Čeká",
        "stage_status_active": "Aktivní",
        "stage_status_done": "Hotovo",

        "setup_hero_title": "Sestavit žádost na míru",
        "setup_hero_desc": "Vlož inzerát a životopis. Vše ostatní je volitelné - čím víc kontextu dáš, tím přesnější bude report shody a vygenerované dokumenty.",

        "step_1_label": "KROK 1",
        "step_1_title": "Inzerát",
        "step_1_desc": "Stáhni popis z URL nebo vlož text níž.",
        "job_url_hint": "https://example.com/jobs/qa-engineer",
        "job_url_btn": "Stáhnout",
        "job_url_running": "Stahuji...",
        "job_url_failed": "Nepodařilo se stáhnout stránku. Vlož text ručně níže.",
        "job_text_hint": "Sem vlož text inzerátu, nebo nahoře klikni na Stáhnout.",

        "step_2_label": "KROK 2",
        "step_2_title": "Životopis a profil",
        "step_2_desc": "Přetáhni svůj životopis (povinné) a volitelně export z LinkedInu.",
        "resume_label": "Životopis (PDF / DOCX / TXT / HTML) - povinné",
        "resume_drop_title": "Přetáhni soubor sem",
        "resume_drop_hint": "nebo klikni a vyber z disku",
        "resume_no_file": "Není vybrán žádný soubor",
        "resume_unsupported": "Nepodporovaný typ souboru. Použij PDF, DOCX, TXT nebo HTML.",
        "resume_browse_btn": "Procházet...",
        "resume_clear_btn": "Vyčistit",

        "linkedin_label": "LinkedIn export (PDF / TXT / HTML) - volitelné",
        "linkedin_drop_title": "Přetáhni LinkedIn export sem",
        "linkedin_drop_hint": "Volitelné - klikni a vyber z disku",
        "linkedin_no_file": "Není vybrán žádný soubor",
        "upload_paste_path_btn": "Vložit cestu",
        "upload_paste_path_tooltip": "Tip pro Windows: ve Průzkumníku Shift+pravý klik na soubor -> Kopírovat jako cestu, pak klikni sem.",
        "upload_cta_label": "Klikni a vyber soubor",

        "step_3_label": "KROK 3",
        "step_3_title": "GitHub profil",
        "step_3_desc": "Vlož URL svého GitHub profilu a aplikace si automaticky stáhne tvoje veřejné repozitáře (token z Nastavení, pokud je uložen, jinak anonymně).",
        "github_url_hint": "https://github.com/tvoje-jmeno (nebo jen tvoje-jmeno)",
        "github_skip_label": "Přeskočit GitHub - nestahovat repozitáře",
        "github_token_note_authenticated": "Používám GitHub token z Nastavení - 5000 požadavků / hodinu.",
        "github_token_note_anonymous": "Žádný GitHub token není uložen - jedu anonymně (60 požadavků / hodinu z IP). Přidej token v Nastavení, ať limit zmizí.",
        "github_status_loaded_template": "Načteno {count} veřejných repozitářů od @{username}.",
        "github_status_failed_template": "Stažení GitHubu selhalo: {error}",

        "footer_followup_label": "Před spuštěním se ptát na nejasné věci",
        "footer_followup_desc": "AI najde nejasná místa (např. 'Pracoval jsi s Pythonem?') a počká na tvoje odpovědi.",
        "footer_run_btn": "Spustit analýzu",
        "footer_run_running": "Probíhá analýza...",
        "footer_run_followups_running": "Hledám nejasnosti...",
        "footer_run_match_running": "Skóruji shodu...",
        "run_disabled_hint": "Přidej životopis a inzerát, ať můžu spustit analýzu.",

        "followup_title": "Rychlé doplňující otázky",
        "followup_intro": "Než AI spočítá shodu, narazila na pár věcí v inzerátu, které z tvého životopisu nejsou jasné. Odpověz na to, co dokážeš - zbytek klidně přeskoč.",
        "followup_answer_hint": "Tvoje odpověď (1-2 věty). Když pole necháš prázdné, otázka se přeskočí.",
        "followup_skip_all": "Přeskočit vše",
        "followup_cancel": "Zpět na nastavení",
        "followup_continue": "Pokračovat s analýzou",
        "followup_no_questions": "Životopis pokrývá inzerát - žádné doplňující otázky nejsou potřeba.",
        "followup_other_label": "Jiné",
        "followup_other_hint": "Sem napiš vlastní odpověď...",

        "error_no_keystore": "Na tomto počítači nejde uložit API klíč - úložiště OS není dostupné. Vyzkoušej Demo režim pro offline náhled.",
        "error_no_key_template": "API klíč pro {provider} ještě není uložen. Otevři Nastavení a přidej ho, nebo přepni na Demo režim.",

        "match_title": "Shoda",
        "match_subtitle": "Jak silná je shoda kandidáta a pozice?",
        "match_overall_label": "CELKEM",
        "match_per_category_hint": "Najeď myší na nadpis sloupce a uvidíš, jak AI dovednost zařadila.",
        "match_matches_title": "SHODY",
        "match_gaps_title": "MEZERY / RIZIKOVÉ",
        "match_ats_title": "ATS KLÍČOVÁ SLOVA",
        "match_ats_present_label": "Přítomná",
        "match_ats_missing_label": "Chybí",
        "match_evidence_title": "NÁHLED DŮKAZŮ",
        "match_open_documents_btn": "Vygenerovat dokumenty",
        "match_generating_documents": "Generuji dokumenty... (může to zabrat minutu)",
        "docs_lang_dialog_title": "Jazyk dokumentů",
        "docs_lang_dialog_desc": "Vyber jazyk, ve kterém se mají dokumenty generovat.",
        "docs_lang_option_cs": "Čeština (CS)",
        "docs_lang_option_en": "Angličtina (EN)",
        "docs_lang_dialog_cancel": "Zrušit",
        "docs_lang_dialog_confirm": "Pokračovat",
        "match_no_results_title": "Zatím žádná analýza",
        "match_no_results_desc": "Otevři Nastavení, vlož životopis + inzerát a klikni na Spustit analýzu.",
        "match_verdict_label": "Verdikt",

        "doc_title": "Dokumenty",
        "doc_subtitle": "Zkontroluj a uprav každý dokument. Export vezme text přesně tak, jak ho vidíš.",
        "doc_tab_tailored_cv": "Životopis na míru",
        "doc_tab_modern_cv": "Moderní životopis",
        "doc_tab_cover_letter": "Motivační dopis",
        "doc_tab_match_report": "Report shody",
        "doc_tab_interview_prep": "Příprava na pohovor",
        "doc_tab_skill_gap": "Plán doplnění mezer",
        "doc_tab_evidence": "Důkazy (jen pokud máš GitHub)",

        "doc_empty_title": "Dokument je zatím prázdný",
        "doc_empty_desc": "Klikni na Vygenerovat a AI dokument napíše z tvé analýzy shody.",
        "doc_generate_btn": "Vygenerovat",
        "doc_regenerate_btn": "Vygenerovat znovu",
        "doc_running": "Generuji...",

        "problem_label_template": "Problém {n}",
        "problem_hint": "Problém {n}: co je špatně nebo chybí?",
        "add_problem_btn": "+ Přidat další problém",
        "refine_btn": "Upřesnit pomocí AI",
        "refine_running": "Upřesňuji...",

        "doc_back_btn": "Zpět na shodu",
        "export_md_btn": "Export MD",
        "export_html_btn": "Export HTML",
        "export_docx_btn": "Export DOCX",
        "export_pdf_btn": "Export PDF",
        "export_all_btn": "Uložit kompletní analýzu",
        "export_ok_template": "Uloženo do {path}",
        "export_failed_template": "Export selhal: {error}",
        "export_running": "Ukládám...",

        "doc_change_color_btn": "Změnit barvu",
        "doc_change_layout_btn": "Změnit rozložení",
        "doc_theme_color_label": "Barva: {name}",
        "doc_theme_layout_label": "Rozložení: {name}",
        "doc_layout_two_column_sidebar": "Dvousloupcové s panelem",
        "doc_layout_single_column_serif": "Jednosloupcové (patkové)",
        "doc_layout_single_column_minimal": "Jednosloupcové (minimální)",
        "doc_layout_centered_header_band": "Vystředěná hlavička",

        "history_title": "Historie",
        "history_subtitle": "Předchozí analýzy zůstávají na disku, ať se k nim můžeš vrátit.",
        "history_empty_title": "Zatím žádné analýzy",
        "history_empty_desc": "Spusť první analýzu z karty Nastavení a objeví se tady.",
        "history_open_folder_btn": "Otevřít složku s dokumenty",
        "history_open_app_btn": "Otevřít v aplikaci",
        "history_refresh_btn": "Obnovit",
        "history_loaded_from_template": "Načteno z {path}",
        "history_score_label": "Skóre",

        "ctx_cost_title": "Náklady relace",
        "ctx_cost_calls_template": "{calls} volání · {tokens} tokenů",
        "ctx_cost_session_template": "~${cost:.2f} v této relaci",
        "ctx_activity_title": "Aktivita",
        "ctx_activity_ready": "Připraveno",
        "ctx_activity_scraping": "Stahuji...",
        "ctx_activity_parsing": "Parsuji soubory...",
        "ctx_activity_analyzing": "Analyzuji...",
        "ctx_activity_followups": "Hledám nejasnosti...",
        "ctx_activity_waiting_user": "Čekám na tvé odpovědi...",
        "ctx_activity_generating": "Generuji...",
        "ctx_activity_exporting": "Ukládám...",
        "ctx_activity_error": "Chyba",
        "ctx_quick_actions_title": "Rychlé akce",
        "ctx_qa_new_run": "Nová analýza",
        "ctx_qa_show_history": "Otevřít historii",
        "ctx_qa_open_how_to": "Jak používat tohoto asistenta",
        "menu_new_run": "Nová analýza",
        "menu_save_full": "Uložit kompletní analýzu",
        "menu_open_folder": "Otevřít složku s dokumenty",
        "menu_show_history": "Zobrazit historii",
        "menu_how_to": "Jak používat tohoto asistenta",
        "menu_demo_load": "Zobrazit demo data",
        "menu_demo_clear": "Skrýt demo data",
        "demo_pill": "DEMO",
        "menu_save_no_run": "Nejdřív spusť analýzu - zatím není co uložit.",
        "menu_save_running": "Ukládám kompletní analýzu...",
        "menu_save_done_template": "Uloženo do {path}",
        "menu_open_folder_no_run": "Složka s dokumenty zatím není - vygeneruj dokumenty a ulož analýzu.",
        "ctx_provider_template": "{provider} · {model}",
        "ctx_run_status_idle": "Před spuštěním",
        "ctx_run_status_active": "Probíhá běh",
        "ctx_run_status_done": "Běh dokončen",

        "how_to_title": "Jak používat tohoto asistenta",
        "how_to_section_what": "Co tahle sekce dělá",
        "how_to_what_text": "AI Career porovná tvůj životopis s konkrétním inzerátem a vytvoří poctivý report shody, životopis na míru, motivační dopis, přípravu na pohovor a plán doplnění mezer, podle kterého můžeš jednat. Všechno staví jen na důkazech, které jsi dodal - AI nesmí vymýšlet.",
        "how_to_section_inputs": "Co si připravit",
        "how_to_inputs_text": "Vlož svůj životopis (PDF, DOCX, TXT nebo HTML) a buď stáhni inzerát z URL, nebo ho vlož ručně. Volitelně přidej LinkedIn export a GitHub uživatelské jméno - důkazů bude víc. Čím víc kontextu, tím přesnější analýza.",
        "how_to_section_quality": "Tipy ke kvalitě",
        "how_to_quality_text": "Vyber nejlevnější model, který stále drží kvalitu (gpt-5.4-mini je rozumný default). Ulož si OpenAI / Anthropic / GitHub klíč v Nastavení - jdou rovnou do úložiště OS. Vyzkoušej Demo režim, ať si projdeš celou cestu, než utratíš první token.",
        "how_to_close": "Rozumím",

        "chat_intro_text": "Jsem tvůj HR asistent. Až bude analýza shody hotová, zeptej se mě na cokoliv k roli, mezerám nebo k tomu, jak formulovat konkrétní bullet.",
        "chat_send_hint": "Zeptej se na roli, mezery, formulaci bulletů...",

        "chat_mode_greeting": "Ahoj! Jsem tvůj HR asistent. Řekni mi, na čem chceš pracovat - upravit CV na konkrétní pozici, napsat motivační dopis, připravit se na pohovor, nebo proklepnout LinkedIn. Inzerát i životopis můžeš kdykoli vložit.",
        "chat_mode_send_hint": "Napiš zprávu... (např. „Hlásím se na Frontend Engineera ve QualityWorks\")",
        "chat_mode_input_attach": "Připojit CV / inzerát (PDF, DOCX, TXT, MD, HTML)",
        "chat_attachments_label": "Přílohy",
        "chat_placeholder": "Zeptej se na roli, mezery, formulaci bulletů...",
        "chat_running": "Přemýšlím...",
        "chat_mode_input_clear": "Vymazat konverzaci",
        "chat_mode_attached_template": "Připojeno: {name}",
        "chat_mode_drop_hint": "Klikni sem a přilož CV nebo inzerát (PDF, DOCX, TXT)",
        "chat_mode_attachment_remove": "Odebrat přílohu",
        "chat_mode_paste_tooltip": "Vložit ze schránky",
        "chat_mode_paste_done": "Vloženo {chars} znaků ze schránky.",
        "chat_mode_paste_empty": "Schránka je prázdná - nejdřív něco zkopíruj.",
        "chat_mode_paste_failed": "Nepodařilo se přečíst schránku.",
        "chat_mode_running": "Přemýšlím...",
        "chat_mode_error_template": "Chat selhal: {error}",
        "chat_mode_quick_action_cv": "Vygeneruj CV na míru",
        "chat_mode_quick_action_letter": "Napiš motivační dopis",
        "chat_mode_quick_action_interview": "Připrav se na pohovor",
        "chat_mode_quick_action_gaps": "Ukaž mi moje největší mezery",
        "chat_mode_attached_docs_title": "Připojené dokumenty",
        "chat_mode_no_attachments": "Zatím nejsou připojené žádné dokumenty.",
        "chat_mode_clear_btn": "Vymazat chat",
        "chat_mode_open_form_btn": "Otevřít formulářový režim",
        "chat_mode_history_title": "Nedávné konverzace",
        "chat_mode_history_empty": "Uložené konverzace se tady objeví.",

        "qa_run_now": "Spustit analýzu",
        "qa_open_match": "Otevřít report shody",
        "qa_open_documents": "Otevřít dokumenty",

        "doc_no_evidence_title": "Důkazový dokument není dostupný",
        "doc_no_evidence_desc": "Vlož v kroku 3 svoje GitHub jméno, ať půjde Důkazy vygenerovat.",

        "ats_label_yes": "v životopise",
        "ats_label_no": "není v životopise",

        "history_run_role_template": "{role}",
        "history_run_company_template": "{company}",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
