"""EN + CS copy for the AI Career section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI CV / Career",
        "title": "AI CV / Career",
        "subtitle": "Build a professional CV, write cover letters and prepare for interviews.",
        "tab_chat": "Chat",
        "tab_form": "Form mode",
        "form_title": "Form mode",
        "form_desc": "Fill in the basics and we'll assemble your CV.",
        "form_field_name": "Full name",
        "form_field_name_hint": "e.g. Jan Novák",
        "form_field_email": "Contact email",
        "form_field_email_hint": "name@email.com",
        "form_field_position": "Target position",
        "form_field_position_hint": "Frontend Developer, Marketing Manager...",
        "form_field_experience": "Years of experience",
        "form_field_experience_hint": "0 / 1-3 / 3-5 / 5+",
        "form_field_skills": "Key skills",
        "form_field_skills_hint": "React, TypeScript, Figma...",
        "form_field_languages": "Languages",
        "form_field_languages_hint": "Czech (native), English (C1)...",
        "form_btn_generate": "Generate CV",
        "form_example_1": "Add up to 6 work experiences with dates and bullets.",
        "form_example_2": "Add education, certifications and side projects.",
        "form_example_3": "Pick from 4 ATS-friendly templates.",
        "msg1_user": "Build me a professional CV for a Frontend Developer role.",
        "msg2_text": "Sure, happy to help you put together a professional CV for a Frontend Developer role.\nI just need a few details first:",
        "msg2_bullet1": "Your name and contact details",
        "msg2_bullet2": "Work experience",
        "msg2_bullet3": "Education",
        "msg2_bullet4": "Skills (technologies, tools)",
        "msg2_bullet5": "Languages",
        "msg2_bullet6": "Projects (if you have any)",
        "msg2_footer": "You can also send me your current CV if you want me to refine it.",
        "action_template": "Generate template",
        "action_sample": "Sample CV",
        "action_form": "Form mode",
        "msg3_user": "I'm Jan Novák, 3 years of experience...",
        "msg4_text": "Thanks! Drafting your CV now...",
        "doc_my_cv": "My_CV_2024.pdf",
        "doc_cover_letter": "Cover_letter_template.docx",
        "attachment_name": "Jan_Novak_CV.docx",
        "qa_cover_letter": "Write a cover letter",
        "qa_interview": "Prepare for an interview",
        "qa_job_offer": "Analyze a job posting",
        "qa_linkedin": "Improve LinkedIn profile",
        "history_1": "CV - Frontend Developer",
        "history_2": "Cover letter - Marketing",
        "history_3": "Interview prep",
        "history_4": "Job posting analysis",
        "history_1_time": "2 hours ago",
        "history_2_time": "Yesterday",
        "history_3_time": "Yesterday",
        "history_4_time": "3 days ago",
    },
    "cs": {
        "nav_label": "AI Životopis / Kariéra",
        "title": "AI Životopis / Kariéra",
        "subtitle": "Vytvářejte profesionální životopisy, motivační dopisy a připravte se na pohovor.",
        "tab_chat": "Chat",
        "tab_form": "Formulářový režim",
        "form_title": "Formulářový režim",
        "form_desc": "Vyplň základní údaje a my složíme tvůj životopis.",
        "form_field_name": "Celé jméno",
        "form_field_name_hint": "např. Jan Novák",
        "form_field_email": "Kontaktní email",
        "form_field_email_hint": "jmeno@email.cz",
        "form_field_position": "Cílová pozice",
        "form_field_position_hint": "Frontend Developer, Marketing manažer...",
        "form_field_experience": "Roky praxe",
        "form_field_experience_hint": "0 / 1-3 / 3-5 / 5+",
        "form_field_skills": "Klíčové dovednosti",
        "form_field_skills_hint": "React, TypeScript, Figma...",
        "form_field_languages": "Jazyky",
        "form_field_languages_hint": "Čeština (rodilý), Angličtina (C1)...",
        "form_btn_generate": "Vygenerovat životopis",
        "form_example_1": "Přidej až 6 pracovních zkušeností s daty a bullety.",
        "form_example_2": "Doplň vzdělání, certifikáty a projekty.",
        "form_example_3": "Vyber z 4 šablon vhodných pro ATS.",
        "msg1_user": "Vytvoř mi profesionální životopis na pozici Frontend Developer.",
        "msg2_text": "Jasně, rád ti pomohu vytvořit profesionální životopis na pozici Frontend Developer.\nNejprve potřebuji pár informací:",
        "msg2_bullet1": "Tvé jméno a kontaktní údaje",
        "msg2_bullet2": "Pracovní zkušenosti",
        "msg2_bullet3": "Vzdělání",
        "msg2_bullet4": "Dovednosti (technologie, nástroje)",
        "msg2_bullet5": "Jazykové znalosti",
        "msg2_bullet6": "Projekty (pokud máš)",
        "msg2_footer": "Můžeš mi také poslat svůj současný životopis, pokud chceš, abych ho upravil.",
        "action_template": "Vygenerovat šablonu",
        "action_sample": "Ukázka životopisu",
        "action_form": "Formulářový režim",
        "msg3_user": "Jmenuji se Jan Novák, mám 3 roky praxe...",
        "msg4_text": "Děkuji za informace! Připravuji tvůj životopis...",
        "doc_my_cv": "Muj_zivotopis_2024.pdf",
        "doc_cover_letter": "Motivacni_dopis_vzor.docx",
        "attachment_name": "Jan_Novak_Zivotopis.docx",
        "qa_cover_letter": "Vytvořit motivační dopis",
        "qa_interview": "Připravit se na pohovor",
        "qa_job_offer": "Analyzovat pracovní nabídku",
        "qa_linkedin": "Vylepšit LinkedIn profil",
        "history_1": "Životopis - Frontend Developer",
        "history_2": "Motivační dopis - Marketing",
        "history_3": "Příprava na pohovor",
        "history_4": "Analýza pracovní nabídky",
        "history_1_time": "Před 2 hodinami",
        "history_2_time": "Včera",
        "history_3_time": "Včera",
        "history_4_time": "3 dny zpět",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
