"""EN + CS copy for the AI Marketing section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Marketing",
        "title": "AI Marketing",
        "subtitle": "I write marketing copy, campaigns and strategies that grab attention and sell.",
        "tab_chat": "Chat",
        "tab_social": "Social posts",
        "tab_ads": "Ads",
        "tab_email": "Email campaigns",
        "tab_landing": "Landing page copy",
        "tab_strategy": "Campaign strategy",
        "tab_templates": "Templates",
        "social_title": "Social posts",
        "social_desc": "Pick a channel and we'll draft the headline, body and hashtags.",
        "social_field_topic_hint": "Launching a new personal-finance app",
        "social_field_channel": "Channel",
        "social_field_channel_hint": "Instagram, LinkedIn, X, Facebook...",
        "social_field_body": "Key message",
        "social_field_body_hint": "What's the one thing the post must say?",
        "social_example_1": "Insert hooks tuned per channel.",
        "social_example_2": "Generate matching hashtags.",
        "social_example_3": "Suggest a hero image direction.",
        "ads_title": "Ad copy",
        "ads_desc": "Quickly draft headlines, descriptions and CTAs for paid ads.",
        "ads_field_product": "Product / service",
        "ads_field_product_hint": "What are you advertising?",
        "ads_field_goal": "Campaign goal",
        "ads_field_goal_hint": "Awareness, leads, sales...",
        "ads_field_format": "Ad format",
        "ads_field_format_hint": "Search, Display, Reels, Stories...",
        "ads_example_1": "3 headline variants per ad.",
        "ads_example_2": "Compliant character counts.",
        "ads_example_3": "Suggested keywords and audiences.",
        "email_title": "Email campaigns",
        "email_desc": "Draft a full campaign - subject line, preview, body and CTA.",
        "email_field_subject": "Subject line",
        "email_field_subject_hint": "Catchy and short, ideally < 50 chars",
        "email_field_audience_hint": "Existing customers, cold leads...",
        "email_field_intro": "Opening sentence",
        "email_field_intro_hint": "How do you want to greet them?",
        "email_example_1": "A/B test 2 subject lines side by side.",
        "email_example_2": "Plain text + HTML versions.",
        "email_example_3": "Suggested send time per audience.",
        "landing_title": "Landing page copy",
        "landing_desc": "Hero, value props and FAQ - in your tone of voice.",
        "landing_field_offer": "Main offer",
        "landing_field_offer_hint": "What is the page selling?",
        "landing_field_audience_hint": "Who lands here from your ads?",
        "landing_field_pains": "Top customer pains",
        "landing_field_pains_hint": "List 2-4 pains the offer solves.",
        "landing_example_1": "5 hero headline variants.",
        "landing_example_2": "Value-prop cards with icons.",
        "landing_example_3": "Suggested FAQ entries.",
        "strategy_title": "Campaign strategy",
        "strategy_desc": "Outline goals, channels, budget split and a rough timeline.",
        "strategy_field_brand": "Brand",
        "strategy_field_brand_hint": "Brand or product name",
        "strategy_field_goal": "Main goal",
        "strategy_field_goal_hint": "Awareness, launch, retention...",
        "strategy_field_budget": "Budget range",
        "strategy_field_budget_hint": "Monthly or total",
        "strategy_field_duration": "Duration",
        "strategy_field_duration_hint": "2 weeks, 1 quarter...",
        "strategy_example_1": "Channel split with rationale.",
        "strategy_example_2": "Weekly schedule outline.",
        "strategy_example_3": "KPIs to track per channel.",
        "templates_title": "Templates",
        "templates_desc": "Pick a starting point - we'll adapt it to your brief.",
        "tpl_instagram_title": "Instagram launch",
        "tpl_instagram_desc": "Carousel + caption for product launches.",
        "tpl_facebook_title": "Facebook ad set",
        "tpl_facebook_desc": "Awareness creative + 3 headline variants.",
        "tpl_linkedin_title": "LinkedIn announcement",
        "tpl_linkedin_desc": "Long-form post with bullets and CTA.",
        "tpl_x_title": "X (Twitter) thread",
        "tpl_x_desc": "5-tweet thread with hook and conclusion.",
        "tpl_email_title": "Cold outreach email",
        "tpl_email_desc": "Personalised intro + value prop + CTA.",
        "tpl_landing_title": "Landing page wireframe",
        "tpl_landing_desc": "Hero, social proof, features, FAQ.",
        "tpl_use": "Use template",
        "msg1_user": "Help me create an Instagram post launching a new personal-finance app. We're targeting young professionals 25-35.",
        "msg2_intro": "Sure! Here's a draft Instagram post launching the new personal-finance app:",
        "msg2_headline_title": "Headline",
        "msg2_headline_text": "Your money. Your future.",
        "msg2_post_title": "Post text",
        "msg2_post_intro": "Meet [App name] - a smart app that helps you stay on top of your money, save easily and reach your goals.",
        "msg2_check1": "Clear budget overview",
        "msg2_check2": "Real-time expense tracking",
        "msg2_check3": "Smart saving tips",
        "msg2_check4": "Safe and simple",
        "msg2_cta": "Download now and take control of your finances!",
        "msg2_hashtags": "#FinanceSimplified #SmartFinance #NewApp",
        "action_copy": "Copy text",
        "action_image": "Generate image",
        "action_shorten": "Shorten text",
        "action_tone": "Different tone (more casual)",
        "action_translate": "Translate to Czech",
        "phone_headline_top": "Your money.",
        "phone_headline_bottom": "Your future.",
        "phone_subtitle": "A smart app for managing money that gives you control and freedom.",
        "phone_overview": "Overview",
        "phone_balance": "23,456 USD",
        "phone_cta": "Download now",
        "phone_app_store": "App Store",
        "phone_play_store": "Google Play",
        "phone_app_store_caption": "Download on the",
        "phone_play_store_caption": "Get it on",
        "brief_title": "Marketing brief",
        "brief_product_label": "Product / service",
        "brief_product": "Personal finance management app",
        "brief_audience_label": "Target audience",
        "brief_audience": "Young professionals 25-35",
        "brief_goal_label": "Main goal",
        "brief_goal": "Launch a new app",
        "brief_tone_label": "Tone of voice",
        "brief_tone": "Friendly, motivating",
        "brief_lang_label": "Language",
        "brief_lang": "English",
        "qa_social": "Create a social media post",
        "qa_ad": "Create ad copy",
        "qa_email": "Create an email campaign",
        "qa_landing": "Create landing page copy",
        "qa_strategy": "Marketing strategy outline",
        "history_1": "Instagram post - new app",
        "history_1_time": "10:42",
        "history_2": "Facebook Ads copy",
        "history_2_time": "Yesterday",
        "history_3": "Email campaign - product launch",
        "history_3_time": "2 days ago",
        "history_4": "Awareness campaign idea",
        "history_4_time": "3 days ago",
    },
    "cs": {
        "nav_label": "AI Marketing",
        "title": "AI Marketing",
        "subtitle": "Vytvářím marketingové texty, kampaně a strategie, které zaujímou a prodávají.",
        "tab_chat": "Chat",
        "tab_social": "Texty na sociální sítě",
        "tab_ads": "Reklamy",
        "tab_email": "E-mailové kampaně",
        "tab_landing": "Landing page copy",
        "tab_strategy": "Strategie kampaní",
        "tab_templates": "Šablony",
        "social_title": "Texty na sociální sítě",
        "social_desc": "Vyber kanál a my připravíme nadpis, tělo a hashtagy.",
        "social_field_topic_hint": "Spuštění nové aplikace pro osobní finance",
        "social_field_channel": "Kanál",
        "social_field_channel_hint": "Instagram, LinkedIn, X, Facebook...",
        "social_field_body": "Hlavní sdělení",
        "social_field_body_hint": "Co musí příspěvek říct především?",
        "social_example_1": "Nasadíme hooky šité na míru kanálu.",
        "social_example_2": "Vygenerujeme odpovídající hashtagy.",
        "social_example_3": "Navrhneme směr pro hero obrázek.",
        "ads_title": "Reklamní text",
        "ads_desc": "Rychle připravíme nadpisy, popisky a CTA pro placené reklamy.",
        "ads_field_product": "Produkt / služba",
        "ads_field_product_hint": "Co inzeruješ?",
        "ads_field_goal": "Cíl kampaně",
        "ads_field_goal_hint": "Povědomí, leady, prodeje...",
        "ads_field_format": "Formát reklamy",
        "ads_field_format_hint": "Search, Display, Reels, Stories...",
        "ads_example_1": "3 varianty nadpisu na reklamu.",
        "ads_example_2": "Hlídání limitu znaků.",
        "ads_example_3": "Návrh klíčových slov a publik.",
        "email_title": "E-mailové kampaně",
        "email_desc": "Připravíme celou kampaň - předmět, preview, tělo i CTA.",
        "email_field_subject": "Předmět e-mailu",
        "email_field_subject_hint": "Krátce a chytlavě, ideálně do 50 znaků",
        "email_field_audience_hint": "Stávající zákazníci, cold leady...",
        "email_field_intro": "Úvodní věta",
        "email_field_intro_hint": "Jak chceš začít?",
        "email_example_1": "A/B test 2 předmětů vedle sebe.",
        "email_example_2": "Plain text + HTML verze.",
        "email_example_3": "Doporučený čas odeslání pro publikum.",
        "landing_title": "Landing page copy",
        "landing_desc": "Hero, hodnoty a FAQ - tvým tónem.",
        "landing_field_offer": "Hlavní nabídka",
        "landing_field_offer_hint": "Co stránka prodává?",
        "landing_field_audience_hint": "Kdo přijde z reklam?",
        "landing_field_pains": "Hlavní bolesti zákazníka",
        "landing_field_pains_hint": "Vypiš 2-4 bolesti, které nabídka řeší.",
        "landing_example_1": "5 variant hero nadpisu.",
        "landing_example_2": "Karty s hodnotami a ikonkami.",
        "landing_example_3": "Návrh FAQ otázek.",
        "strategy_title": "Strategie kampaně",
        "strategy_desc": "Cíle, kanály, rozpočet a hrubý časový plán na jednom místě.",
        "strategy_field_brand": "Značka",
        "strategy_field_brand_hint": "Název značky nebo produktu",
        "strategy_field_goal": "Hlavní cíl",
        "strategy_field_goal_hint": "Povědomí, launch, retence...",
        "strategy_field_budget": "Rozpočet",
        "strategy_field_budget_hint": "Měsíční nebo celkový",
        "strategy_field_duration": "Doba trvání",
        "strategy_field_duration_hint": "2 týdny, 1 kvartál...",
        "strategy_example_1": "Rozdělení mezi kanály se zdůvodněním.",
        "strategy_example_2": "Týdenní časový plán.",
        "strategy_example_3": "KPI pro každý kanál.",
        "templates_title": "Šablony",
        "templates_desc": "Vyber startovní bod - šablonu přizpůsobíme tvému briefu.",
        "tpl_instagram_title": "Instagram launch",
        "tpl_instagram_desc": "Carousel + caption pro spuštění produktu.",
        "tpl_facebook_title": "Facebook ad set",
        "tpl_facebook_desc": "Awareness kreativa + 3 varianty nadpisu.",
        "tpl_linkedin_title": "LinkedIn oznámení",
        "tpl_linkedin_desc": "Dlouhý příspěvek s bullety a CTA.",
        "tpl_x_title": "X (Twitter) thread",
        "tpl_x_desc": "Vlákno o 5 tweetech - hook + závěr.",
        "tpl_email_title": "Cold outreach email",
        "tpl_email_desc": "Personalizovaný úvod + value prop + CTA.",
        "tpl_landing_title": "Wireframe landing page",
        "tpl_landing_desc": "Hero, social proof, features, FAQ.",
        "tpl_use": "Použít šablonu",
        "msg1_user": "Pomoz mi vytvořit příspěvek na Instagram pro uvedení nové aplikace na správu osobních financí. Cílíme na mladé profesionály 25-35 let.",
        "msg2_intro": "Jasně! Tady máš návrh příspěvku na Instagram pro uvedení nové aplikace na správu osobních financí:",
        "msg2_headline_title": "Nadpis",
        "msg2_headline_text": "Tvoje finance. Tvoje budoucnost.",
        "msg2_post_title": "Text příspěvku",
        "msg2_post_intro": "Představujeme [Název aplikace] - chytrou aplikaci, která ti pomůže mít přehled o penězích, šetřit snadno a dosahovat svých cílů.",
        "msg2_check1": "Přehledný rozpočet",
        "msg2_check2": "Sledování výdajů v reálném čase",
        "msg2_check3": "Chytré tipy na úspory",
        "msg2_check4": "Bezpečně a jednoduše",
        "msg2_cta": "Stáhni teď a převezmi kontrolu nad svými financemi!",
        "msg2_hashtags": "#FinanceSimplified #ChytreFinance #NovaAplikace",
        "action_copy": "Zkopírovat text",
        "action_image": "Vygenerovat obrázek",
        "action_shorten": "Zkrátit text",
        "action_tone": "Jiný tón (více casual)",
        "action_translate": "Přeložit do angličtiny",
        "phone_headline_top": "Tvoje finance.",
        "phone_headline_bottom": "Tvoje budoucnost.",
        "phone_subtitle": "Chytrá aplikace pro správu peněz, která ti dává kontrolu a svobodu.",
        "phone_overview": "Přehled",
        "phone_balance": "23 456 Kč",
        "phone_cta": "Stáhni nyní",
        "phone_app_store": "App Store",
        "phone_play_store": "Google Play",
        "phone_app_store_caption": "Stáhněte z",
        "phone_play_store_caption": "Získat na",
        "brief_title": "Marketingový brief",
        "brief_product_label": "Produkt / služba",
        "brief_product": "Aplikace pro správu osobních financí",
        "brief_audience_label": "Cílová skupina",
        "brief_audience": "Mladí profesionálové 25-35 let",
        "brief_goal_label": "Hlavní cíl",
        "brief_goal": "Uvedení nové aplikace",
        "brief_tone_label": "Tón komunikace",
        "brief_tone": "Přátelský, motivační",
        "brief_lang_label": "Jazyk",
        "brief_lang": "Čeština",
        "qa_social": "Vytvořit příspěvek na sociální sítě",
        "qa_ad": "Vytvořit reklamní text",
        "qa_email": "Vytvořit e-mailovou kampaň",
        "qa_landing": "Vytvořit landing page copy",
        "qa_strategy": "Návrh marketingové strategie",
        "history_1": "Instagram příspěvek - nová aplikace",
        "history_1_time": "10:42",
        "history_2": "Reklamní text pro Facebook Ads",
        "history_2_time": "Včera",
        "history_3": "E-mail kampaň - spuštění produktu",
        "history_3_time": "2 dny zpět",
        "history_4": "Návrh kampaně pro zvýšení povědomí",
        "history_4_time": "3 dny zpět",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
