"""EN + CS copy for the AI Marketing section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Marketing",
        "title": "AI Marketing",
        "subtitle": "I write marketing copy, campaigns and strategies that grab attention and sell.",
        "tab_chat": "Chat",
        "tab_social": "Social posts",
        "tab_ads": "Ads",
        "tab_email": "Email campaigns",
        "tab_landing": "Landing page copy",
        "tab_strategy": "Campaign strategy",
        "tab_templates": "Templates",
        "msg1_user": "Help me create an Instagram post launching a new personal-finance app. We're targeting young professionals 25-35.",
        "msg2_intro": "Sure! Here's a draft Instagram post launching the new personal-finance app:",
        "msg2_headline_title": "Headline",
        "msg2_headline_text": "Your money. Your future.",
        "msg2_post_title": "Post text",
        "msg2_post_intro": "Meet [App name] - a smart app that helps you stay on top of your money, save easily and reach your goals.",
        "msg2_check1": "Clear budget overview",
        "msg2_check2": "Real-time expense tracking",
        "msg2_check3": "Smart saving tips",
        "msg2_check4": "Safe and simple",
        "msg2_cta": "Download now and take control of your finances!",
        "msg2_hashtags": "#FinanceSimplified #SmartFinance #NewApp",
        "action_copy": "Copy text",
        "action_image": "Generate image",
        "action_shorten": "Shorten text",
        "action_tone": "Different tone (more casual)",
        "action_translate": "Translate to Czech",
        "phone_headline_top": "Your money.",
        "phone_headline_bottom": "Your future.",
        "phone_subtitle": "A smart app for managing money that gives you control and freedom.",
        "phone_overview": "Overview",
        "phone_balance": "23,456 USD",
        "phone_cta": "Download now",
        "phone_app_store": "App Store",
        "phone_play_store": "Google Play",
        "phone_app_store_caption": "Download on the",
        "phone_play_store_caption": "Get it on",
        "brief_title": "Marketing brief",
        "brief_product_label": "Product / service",
        "brief_product": "Personal finance management app",
        "brief_audience_label": "Target audience",
        "brief_audience": "Young professionals 25-35",
        "brief_goal_label": "Main goal",
        "brief_goal": "Launch a new app",
        "brief_tone_label": "Tone of voice",
        "brief_tone": "Friendly, motivating",
        "brief_lang_label": "Language",
        "brief_lang": "English",
        "qa_social": "Create a social media post",
        "qa_ad": "Create ad copy",
        "qa_email": "Create an email campaign",
        "qa_landing": "Create landing page copy",
        "qa_strategy": "Marketing strategy outline",
        "history_1": "Instagram post - new app",
        "history_1_time": "10:42",
        "history_2": "Facebook Ads copy",
        "history_2_time": "Yesterday",
        "history_3": "Email campaign - product launch",
        "history_3_time": "2 days ago",
        "history_4": "Awareness campaign idea",
        "history_4_time": "3 days ago",
    },
    "cs": {
        "nav_label": "AI Marketing",
        "title": "AI Marketing",
        "subtitle": "Vytvářím marketingové texty, kampaně a strategie, které zaujímou a prodávají.",
        "tab_chat": "Chat",
        "tab_social": "Texty na sociální sítě",
        "tab_ads": "Reklamy",
        "tab_email": "E-mailové kampaně",
        "tab_landing": "Landing page copy",
        "tab_strategy": "Strategie kampaní",
        "tab_templates": "Šablony",
        "msg1_user": "Pomoz mi vytvořit příspěvek na Instagram pro uvedení nové aplikace na správu osobních financí. Cílíme na mladé profesionály 25-35 let.",
        "msg2_intro": "Jasně! Tady máš návrh příspěvku na Instagram pro uvedení nové aplikace na správu osobních financí:",
        "msg2_headline_title": "Nadpis",
        "msg2_headline_text": "Tvoje finance. Tvoje budoucnost.",
        "msg2_post_title": "Text příspěvku",
        "msg2_post_intro": "Představujeme [Název aplikace] - chytrou aplikaci, která ti pomůže mít přehled o penězích, šetřit snadno a dosahovat svých cílů.",
        "msg2_check1": "Přehledný rozpočet",
        "msg2_check2": "Sledování výdajů v reálném čase",
        "msg2_check3": "Chytré tipy na úspory",
        "msg2_check4": "Bezpečně a jednoduše",
        "msg2_cta": "Stáhni teď a převezmi kontrolu nad svými financemi!",
        "msg2_hashtags": "#FinanceSimplified #ChytreFinance #NovaAplikace",
        "action_copy": "Zkopírovat text",
        "action_image": "Vygenerovat obrázek",
        "action_shorten": "Zkrátit text",
        "action_tone": "Jiný tón (více casual)",
        "action_translate": "Přeložit do angličtiny",
        "phone_headline_top": "Tvoje finance.",
        "phone_headline_bottom": "Tvoje budoucnost.",
        "phone_subtitle": "Chytrá aplikace pro správu peněz, která ti dává kontrolu a svobodu.",
        "phone_overview": "Přehled",
        "phone_balance": "23 456 Kč",
        "phone_cta": "Stáhni nyní",
        "phone_app_store": "App Store",
        "phone_play_store": "Google Play",
        "phone_app_store_caption": "Stáhněte z",
        "phone_play_store_caption": "Získat na",
        "brief_title": "Marketingový brief",
        "brief_product_label": "Produkt / služba",
        "brief_product": "Aplikace pro správu osobních financí",
        "brief_audience_label": "Cílová skupina",
        "brief_audience": "Mladí profesionálové 25-35 let",
        "brief_goal_label": "Hlavní cíl",
        "brief_goal": "Uvedení nové aplikace",
        "brief_tone_label": "Tón komunikace",
        "brief_tone": "Přátelský, motivační",
        "brief_lang_label": "Jazyk",
        "brief_lang": "Čeština",
        "qa_social": "Vytvořit příspěvek na sociální sítě",
        "qa_ad": "Vytvořit reklamní text",
        "qa_email": "Vytvořit e-mailovou kampaň",
        "qa_landing": "Vytvořit landing page copy",
        "qa_strategy": "Návrh marketingové strategie",
        "history_1": "Instagram příspěvek - nová aplikace",
        "history_1_time": "10:42",
        "history_2": "Reklamní text pro Facebook Ads",
        "history_2_time": "Včera",
        "history_3": "E-mail kampaň - spuštění produktu",
        "history_3_time": "2 dny zpět",
        "history_4": "Návrh kampaně pro zvýšení povědomí",
        "history_4_time": "3 dny zpět",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
