"""EN + CS copy for the AI LinkedIn section.

Every visible string has both ``en`` and ``cs`` keys per the section
contract. Keys are grouped by area: header, mode tabs, builder tabs,
section labels, audience / tone labels, posts kinds, completeness
labels, evidence labels, chat copy, footer, error messages, how-to
texts, ctx_activity_*, brand fallback.
"""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # Sidebar / header
        "nav_label": "AI LinkedIn",
        "title": "AI LinkedIn",
        "subtitle": (
            "Turn your CV, LinkedIn export and GitHub into a recruiter-ready"
            " LinkedIn profile - or just polish a single section."
        ),
        "header_help": "How to use this assistant",
        # Mode tabs
        "mode_tab_chat": "Chat",
        "mode_tab_builder": "Builder",
        # Builder sub-tabs
        "builder_tab_setup": "Setup",
        "builder_tab_sections": "Sections",
        "builder_tab_output": "Output",
        "builder_tab_history": "History",
        # Header menu
        "menu_new_build": "New profile build",
        "menu_save_full": "Save complete profile",
        "menu_open_folder": "Open run folder",
        "menu_show_history": "Show history",
        "menu_how_to": "How to use",
        # Setup tab
        "setup_step1_title": "Step 1 — Targeting",
        "setup_step1_desc": "Tell the AI who this profile is aimed at.",
        "setup_target_roles_label": "Target roles",
        "setup_target_roles_hint": "One per line — e.g. Senior Software QA Engineer, QA Automation Lead",
        "setup_audience_label": "Audience",
        "setup_tone_label": "Tone",
        "setup_offer_services_label": "Offer freelance services on LinkedIn",
        "setup_offer_services_hint": "Toggles the optional Services section.",
        "setup_step2_title": "Step 2 — Inputs",
        "setup_step2_desc": "Drop a CV, paste a LinkedIn export and (optionally) a GitHub URL.",
        "setup_resume_title": "Resume / CV",
        "setup_resume_hint": "PDF, DOCX, TXT, MD or HTML.",
        "setup_linkedin_title": "LinkedIn export",
        "setup_linkedin_hint": "Optional. PDF, HTML or TXT - export from LinkedIn → Settings.",
        "upload_paste_path_btn": "Paste path",
        "upload_paste_path_tooltip": "Tip on Windows: Shift+Right-click a file in Explorer -> Copy as path, then click here.",
        "upload_cta_label": "Click to browse",
        "setup_github_label": "GitHub username or URL",
        "setup_github_hint": "Optional. Empty = skip.",
        "setup_github_skip": "Skip GitHub",
        "setup_notes_label": "Free-form notes (optional)",
        "setup_notes_hint": "Anything else the AI should know — preferred roles, scope numbers, mentoring stories.",
        "setup_step3_title": "Step 3 — Output",
        "setup_step3_desc": "Pick output language and decide whether to ask clarifying questions.",
        "setup_lang_label": "Output language",
        "setup_lang_en": "English",
        "setup_lang_cs": "Čeština",
        "setup_followups_label": "Ask clarifying questions before generating",
        "setup_followups_hint": "Recommended. The AI surfaces gaps before it writes anything.",
        "setup_continue_button": "Continue to sections",
        # Sections tab
        "sections_title": "Pick what to build",
        "sections_desc": "Choose a preset or pick individual sections. Press Run to fire the pipeline.",
        "sections_preset_just_headline": "Just the headline",
        "sections_preset_just_about": "Just the About",
        "sections_preset_just_posts": "Just posts",
        "sections_preset_everything": "Everything",
        "sections_preset_custom": "Custom",
        "sections_post_kinds_title": "Post kinds",
        "sections_post_kinds_desc": "Pick which post kinds the Posts generator should emit.",
        "sections_run_button": "Run profile build",
        "sections_run_running": "Running…",
        "sections_followup_button": "Ask clarifying questions first",
        # Output tab
        "output_empty_title": "Nothing built yet",
        "output_empty_desc": "Run the profile build to see results here.",
        "output_save_button": "Save complete profile package",
        "output_open_folder_button": "Open last run folder",
        "output_score_card_title": "Profile score",
        "output_score_card_desc": "Deterministic score from the cached state — no extra LLM call.",
        "output_score_breakdown_label": "Breakdown",
        "output_headlines_title": "Headlines",
        "output_about_title": "About / Intro",
        "output_about_short": "Short",
        "output_about_medium": "Medium",
        "output_about_long": "Long",
        "output_about_technical": "Technical",
        "output_about_recruiter": "Recruiter-friendly",
        "output_chars_suffix": "chars",
        "output_experience_title": "Experience rewrite",
        "output_skills_title": "Skills recommendation",
        "output_skill_bucket_core": "Claim now",
        "output_skill_bucket_to_verify": "Verify first",
        "output_skill_bucket_to_learn": "Learn next",
        "output_skill_bucket_do_not_claim": "Do not claim",
        "output_featured_title": "Featured suggestions",
        "output_projects_title": "Projects",
        "output_certifications_title": "Certifications",
        "output_education_title": "Education rewrite",
        "output_services_title": "Services",
        "output_courses_title": "Courses & training",
        "output_recommendations_title": "Recommendation requests",
        "output_posts_title": "LinkedIn posts",
        "output_checklist_title": "Profile completeness",
        "output_unsupported_title": "Unsupported claims",
        "output_languages_title": "Languages",
        "output_volunteer_title": "Volunteer experience",
        "output_publications_title": "Publications",
        "output_honors_title": "Honors & awards",
        "output_no_evidence_skip": "No evidence found — skip until you have something concrete.",
        "output_copy": "Copy",
        "output_refine": "Refine with AI",
        "output_chars_left": "chars left",
        # Section labels (used by picker + checklist)
        "section_headline": "Headline / motto",
        "section_headline_hint": "3-6 variants in different focuses + char counts.",
        "section_about": "About / Intro",
        "section_about_hint": "Short, medium, long, technical and recruiter-friendly variants.",
        "section_experience": "Experience rewrite",
        "section_experience_hint": "Per role: LinkedIn description, 3-6 bullets, suggested skills, do-not-claim notes.",
        "section_education": "Education rewrite",
        "section_education_hint": "Per entry: LinkedIn description + relevant coursework + connection to target.",
        "section_certifications": "Certifications",
        "section_certifications_hint": "Existing certs + recommended next certs (no hallucination).",
        "section_skills": "Skills",
        "section_skills_hint": "4 buckets: claim now / verify / learn next / do not claim.",
        "section_featured": "Featured",
        "section_featured_hint": "What to pin at the top of your profile.",
        "section_projects": "Projects",
        "section_projects_hint": "Per project: title, description, stack, role, link.",
        "section_services": "Services",
        "section_services_hint": "Optional - only if you want freelance leads.",
        "section_courses": "Courses & training",
        "section_courses_hint": "Existing courses + 3-6 recommendations aligned with target roles.",
        "section_recommendations": "Recommendation requests",
        "section_recommendations_hint": "Templates you can send to former managers / peers - never fakes.",
        "section_posts": "LinkedIn posts",
        "section_posts_hint": "Choose post kinds (learning update, project launch, job search, …).",
        # Audience labels
        "audience_recruiter": "Recruiter",
        "audience_hiring": "Hiring manager",
        "audience_founder": "Founder / lead",
        "audience_peer": "Peer / community",
        # Tone labels
        "tone_professional": "Professional",
        "tone_junior_friendly": "Junior-friendly",
        "tone_senior": "Senior",
        "tone_confident_honest": "Confident but honest",
        "tone_technical": "Technical",
        "tone_simple": "Simple",
        "tone_recruiter_friendly": "Recruiter-friendly",
        # Post kinds
        "post_kind_learning_update": "Learning update",
        "post_kind_project_launch": "Project launch",
        "post_kind_job_search": "Open to roles / job search",
        "post_kind_recruiter_outreach": "Recruiter outreach DM",
        "post_kind_networking": "Networking message",
        "post_kind_comment": "Comment suggestion",
        # Completeness priority labels
        "priority_high": "High priority",
        "priority_medium": "Medium priority",
        "priority_low": "Low priority",
        "priority_skip": "Skip",
        "checklist_high_remaining": "High-priority items left",
        "checklist_medium_remaining": "Medium-priority items left",
        "checklist_low_remaining": "Low-priority items left",
        # Evidence labels
        "evidence_resume": "Resume",
        "evidence_linkedin_export": "LinkedIn export",
        "evidence_github": "GitHub",
        "evidence_user_confirmed": "You confirmed",
        "evidence_target_role": "Target role",
        "evidence_missing_evidence": "Missing evidence",
        # Right-hand panel
        "ctx_brand_title": "Brand profile",
        "ctx_quick_actions_title": "Quick actions",
        "ctx_recent_title": "Recent profile builds",
        "ctx_attachments_title": "Attached documents",
        "ctx_activity_title": "Activity",
        "ctx_activity_ready": "Ready",
        "ctx_activity_scraping": "Fetching GitHub / external data…",
        "ctx_activity_parsing": "Parsing your documents…",
        "ctx_activity_extracting": "Extracting profile from your sources…",
        "ctx_activity_analyzing": "Analysing fit and gaps…",
        "ctx_activity_generating": "Generating LinkedIn copy…",
        "ctx_activity_scoring": "Scoring profile completeness…",
        "ctx_activity_saving": "Saving the profile package…",
        "ctx_activity_error": "Last action failed - check Settings → Debug logs.",
        "ctx_cost_title": "Run cost",
        # Brand fallback
        "brand_name_label": "Name",
        "brand_role_label": "Role",
        "brand_industry_label": "Industry",
        "brand_audience_label": "Audience",
        "brand_tone_label": "Tone",
        "brand_fallback_name": "(extract a profile to see your name)",
        "brand_fallback_role": "(target role unset)",
        "brand_fallback_industry": "(industry unset)",
        # Quick actions
        "qa_build_full": "Build complete profile",
        "qa_improve_headline": "Improve headline",
        "qa_write_post": "Write a post",
        "qa_show_history": "Show history",
        "qa_how_to": "How to use this assistant",
        # Recent runs
        "recent_default_title": "Profile build",
        "recent_empty_title": "No saved runs yet",
        # Chat tab
        "chat_placeholder": "Ask anything about your LinkedIn profile…",
        "chat_attachments_label": "Attachments",
        "chat_quick_actions_title": "Try a quick prompt",
        "chat_qa_improve_headline": "Improve my headline",
        "chat_qa_write_learning_post": "Write a learning-update post",
        "chat_qa_critique_about": "Critique my About",
        "chat_qa_recruiter_dm": "Draft a recruiter outreach DM",
        "chat_running": "Thinking…",
        # History tab
        "history_empty_title": "Nothing saved yet",
        "history_empty_desc": "Save a complete profile build and it'll show up here.",
        "history_open": "Open folder",
        "history_score": "Score",
        # Errors
        "error_no_inputs": "Add a CV, a LinkedIn export or paste some notes before running the build.",
        "error_no_target_role": "Add at least one target role first.",
        "error_run_failed_title": "Profile build failed",
        # How-to texts
        "howto_title": "How to use AI LinkedIn",
        "howto_what_title": "What this section does",
        "howto_what_text": (
            "Builds a complete recruiter-ready LinkedIn profile from your CV, LinkedIn export and GitHub. "
            "You can also generate single sections (headline, About, posts, recruiter DMs) or chat with"
            " the LinkedIn voice expert."
        ),
        "howto_prepare_title": "What to bring",
        "howto_prepare_text": (
            "A CV PDF, optionally a LinkedIn data export, optionally a GitHub username, and a list of"
            " roles you want to attract. The richer the input, the more grounded the output."
        ),
        "howto_quality_title": "Quality tips",
        "howto_quality_text": (
            "Turn on 'Ask clarifying questions' on the first run — it asks before inventing. Pick the"
            " audience that matches your goal (recruiter vs. peer). Use 'Refine with AI' on any card to"
            " make it tighter."
        ),
        "howto_wont_title": "What it will NOT do",
        "howto_wont_text": (
            "It will never invent certifications, awards, patents or quotes. Anything missing evidence"
            " ends up in the 'Verify' / 'Do not claim' bucket so you can confirm before publishing."
        ),
        "howto_close": "Got it",
        # Followup dialog (shared copy)
        "followup_dialog_title": "Quick clarifications",
        "followup_dialog_subtitle": "Answer a few questions so I can ground the profile in your real signals.",
        "followup_dialog_skip": "Skip",
        "followup_dialog_submit": "Continue",
        "followup_dialog_cancel": "Cancel",
        "followup_dialog_other_label": "Other",
        "followup_dialog_other_hint": "Type your own answer…",
        "followup_dialog_skip_all": "Skip all",
        "followup_dialog_answer_hint": "Your answer (optional)",
    },
    "cs": {
        # Sidebar / header
        "nav_label": "AI LinkedIn",
        "title": "AI LinkedIn",
        "subtitle": (
            "Z tvého CV, LinkedIn exportu a GitHubu udělám recruiter-ready"
            " LinkedIn profil - nebo doladí jen jednu sekci."
        ),
        "header_help": "Jak tohoto asistenta používat",
        # Mode tabs
        "mode_tab_chat": "Chat",
        "mode_tab_builder": "Builder",
        # Builder sub-tabs
        "builder_tab_setup": "Setup",
        "builder_tab_sections": "Sekce",
        "builder_tab_output": "Výstup",
        "builder_tab_history": "Historie",
        # Header menu
        "menu_new_build": "Nový profile build",
        "menu_save_full": "Uložit kompletní profil",
        "menu_open_folder": "Otevřít složku runu",
        "menu_show_history": "Zobrazit historii",
        "menu_how_to": "Jak používat",
        # Setup tab
        "setup_step1_title": "Krok 1 — Cílení",
        "setup_step1_desc": "Řekni AI, na koho profil cílí.",
        "setup_target_roles_label": "Cílové pozice",
        "setup_target_roles_hint": "Po jedné na řádek - např. Senior Software QA Engineer, QA Automation Lead",
        "setup_audience_label": "Publikum",
        "setup_tone_label": "Tón",
        "setup_offer_services_label": "Nabízet freelance služby na LinkedInu",
        "setup_offer_services_hint": "Zapne volitelnou sekci Služby.",
        "setup_step2_title": "Krok 2 — Vstupy",
        "setup_step2_desc": "Vlož CV, případně LinkedIn export a GitHub URL.",
        "setup_resume_title": "Životopis / CV",
        "setup_resume_hint": "PDF, DOCX, TXT, MD nebo HTML.",
        "setup_linkedin_title": "LinkedIn export",
        "setup_linkedin_hint": "Volitelné. PDF, HTML nebo TXT - export z LinkedIn → Settings.",
        "upload_paste_path_btn": "Vložit cestu",
        "upload_paste_path_tooltip": "Tip pro Windows: ve Průzkumníku Shift+pravý klik na soubor -> Kopírovat jako cestu, pak klikni sem.",
        "upload_cta_label": "Klikni a vyber soubor",
        "setup_github_label": "GitHub uživatel nebo URL",
        "setup_github_hint": "Volitelné. Prázdné = přeskočit.",
        "setup_github_skip": "Přeskočit GitHub",
        "setup_notes_label": "Volné poznámky (volitelné)",
        "setup_notes_hint": "Cokoliv dalšího, co by AI měla vědět - preferované role, scope čísla, mentoring příběhy.",
        "setup_step3_title": "Krok 3 — Výstup",
        "setup_step3_desc": "Vyber jazyk výstupu a rozhodni, jestli se má AI doptat.",
        "setup_lang_label": "Jazyk výstupu",
        "setup_lang_en": "English",
        "setup_lang_cs": "Čeština",
        "setup_followups_label": "Doptat se na chybějící informace",
        "setup_followups_hint": "Doporučeno. AI před generováním upozorní na mezery.",
        "setup_continue_button": "Pokračovat na sekce",
        # Sections tab
        "sections_title": "Vyber, co se má vyrobit",
        "sections_desc": "Vyber preset nebo jednotlivé sekce. Stiskni Spustit a pipeline jede.",
        "sections_preset_just_headline": "Jen headline",
        "sections_preset_just_about": "Jen About",
        "sections_preset_just_posts": "Jen posty",
        "sections_preset_everything": "Všechno",
        "sections_preset_custom": "Vlastní",
        "sections_post_kinds_title": "Typy postů",
        "sections_post_kinds_desc": "Vyber, jaké typy postů má generátor vyrobit.",
        "sections_run_button": "Spustit profile build",
        "sections_run_running": "Generuji…",
        "sections_followup_button": "Nejdřív se doptat",
        # Output tab
        "output_empty_title": "Zatím nic vyrobeno",
        "output_empty_desc": "Spusť profile build, ať tu něco vidíš.",
        "output_save_button": "Uložit kompletní profil package",
        "output_open_folder_button": "Otevřít složku posledního runu",
        "output_score_card_title": "Skóre profilu",
        "output_score_card_desc": "Deterministické skóre - žádné další LLM volání.",
        "output_score_breakdown_label": "Rozpis",
        "output_headlines_title": "Headliny",
        "output_about_title": "About / Úvod",
        "output_about_short": "Krátká",
        "output_about_medium": "Střední",
        "output_about_long": "Dlouhá",
        "output_about_technical": "Technická",
        "output_about_recruiter": "Recruiter-friendly",
        "output_chars_suffix": "znaků",
        "output_experience_title": "Přepis zkušeností",
        "output_skills_title": "Doporučení skills",
        "output_skill_bucket_core": "Uveď hned",
        "output_skill_bucket_to_verify": "Nejdřív ověř",
        "output_skill_bucket_to_learn": "Naučit se příště",
        "output_skill_bucket_do_not_claim": "Neuvádět",
        "output_featured_title": "Featured návrhy",
        "output_projects_title": "Projekty",
        "output_certifications_title": "Certifikace",
        "output_education_title": "Přepis vzdělání",
        "output_services_title": "Služby",
        "output_courses_title": "Kurzy & školení",
        "output_recommendations_title": "Žádosti o doporučení",
        "output_posts_title": "LinkedIn posty",
        "output_checklist_title": "Úplnost profilu",
        "output_unsupported_title": "Nepodložená tvrzení",
        "output_languages_title": "Jazyky",
        "output_volunteer_title": "Dobrovolnictví",
        "output_publications_title": "Publikace",
        "output_honors_title": "Ocenění",
        "output_no_evidence_skip": "Žádné důkazy - vynech, dokud nemáš něco konkrétního.",
        "output_copy": "Kopírovat",
        "output_refine": "Doladit s AI",
        "output_chars_left": "znaků zbývá",
        # Section labels (used by picker + checklist)
        "section_headline": "Headline / motto",
        "section_headline_hint": "3-6 variant v různých zaměřeních + počet znaků.",
        "section_about": "About / Úvod",
        "section_about_hint": "Krátká, střední, dlouhá, technická a recruiter-friendly varianta.",
        "section_experience": "Přepis zkušeností",
        "section_experience_hint": "Pro každou roli: LinkedIn popis, 3-6 bullet pointů, suggested skills, do-not-claim poznámky.",
        "section_education": "Přepis vzdělání",
        "section_education_hint": "Pro každý záznam: LinkedIn popis + relevantní předměty + napojení na cíl.",
        "section_certifications": "Certifikace",
        "section_certifications_hint": "Stávající certifikáty + doporučené další (žádné halucinace).",
        "section_skills": "Skills",
        "section_skills_hint": "4 koše: uveď hned / nejdřív ověř / naučit se / neuvádět.",
        "section_featured": "Featured",
        "section_featured_hint": "Co připnout nahoru profilu.",
        "section_projects": "Projekty",
        "section_projects_hint": "Pro každý projekt: název, popis, stack, role, odkaz.",
        "section_services": "Služby",
        "section_services_hint": "Volitelné - jen pokud chceš freelance.",
        "section_courses": "Kurzy & školení",
        "section_courses_hint": "Stávající kurzy + 3-6 doporučení podle cílových rolí.",
        "section_recommendations": "Žádosti o doporučení",
        "section_recommendations_hint": "Šablony pro bývalé manažery / kolegy - žádné fake doporučení.",
        "section_posts": "LinkedIn posty",
        "section_posts_hint": "Vyber typy postů (učení, launch, job search, …).",
        # Audience labels
        "audience_recruiter": "Recruiter",
        "audience_hiring": "Hiring manager",
        "audience_founder": "Founder / lead",
        "audience_peer": "Kolegové / komunita",
        # Tone labels
        "tone_professional": "Profesionální",
        "tone_junior_friendly": "Junior-friendly",
        "tone_senior": "Senior",
        "tone_confident_honest": "Sebevědomý ale upřímný",
        "tone_technical": "Technický",
        "tone_simple": "Jednoduchý",
        "tone_recruiter_friendly": "Recruiter-friendly",
        # Post kinds
        "post_kind_learning_update": "Učební update",
        "post_kind_project_launch": "Launch projektu",
        "post_kind_job_search": "Open to roles / hledání práce",
        "post_kind_recruiter_outreach": "DM na recruitera",
        "post_kind_networking": "Networking zpráva",
        "post_kind_comment": "Návrh komentáře",
        # Completeness priority labels
        "priority_high": "Vysoká priorita",
        "priority_medium": "Střední priorita",
        "priority_low": "Nízká priorita",
        "priority_skip": "Vynechat",
        "checklist_high_remaining": "Vysokoprioritních zbývá",
        "checklist_medium_remaining": "Středně-prioritních zbývá",
        "checklist_low_remaining": "Nízkoprioritních zbývá",
        # Evidence labels
        "evidence_resume": "Životopis",
        "evidence_linkedin_export": "LinkedIn export",
        "evidence_github": "GitHub",
        "evidence_user_confirmed": "Potvrdil/a jsi",
        "evidence_target_role": "Cílová role",
        "evidence_missing_evidence": "Chybí důkaz",
        # Right-hand panel
        "ctx_brand_title": "Profil značky",
        "ctx_quick_actions_title": "Rychlé akce",
        "ctx_recent_title": "Poslední profile buildy",
        "ctx_attachments_title": "Připojené dokumenty",
        "ctx_activity_title": "Aktivita",
        "ctx_activity_ready": "Připraveno",
        "ctx_activity_scraping": "Stahuju GitHub / externí data…",
        "ctx_activity_parsing": "Parsuju dokumenty…",
        "ctx_activity_extracting": "Extrahuju profil ze zdrojů…",
        "ctx_activity_analyzing": "Analyzuju shodu a mezery…",
        "ctx_activity_generating": "Generuji LinkedIn texty…",
        "ctx_activity_scoring": "Skóruju úplnost profilu…",
        "ctx_activity_saving": "Ukládám balíček profilu…",
        "ctx_activity_error": "Poslední akce selhala - viz Nastavení → Debug logs.",
        "ctx_cost_title": "Cena runu",
        # Brand fallback
        "brand_name_label": "Jméno",
        "brand_role_label": "Role",
        "brand_industry_label": "Obor",
        "brand_audience_label": "Publikum",
        "brand_tone_label": "Tón",
        "brand_fallback_name": "(po extrakci tu uvidíš jméno)",
        "brand_fallback_role": "(cílová role nenastavena)",
        "brand_fallback_industry": "(obor nenastaven)",
        # Quick actions
        "qa_build_full": "Postavit kompletní profil",
        "qa_improve_headline": "Vylepšit headline",
        "qa_write_post": "Napsat post",
        "qa_show_history": "Zobrazit historii",
        "qa_how_to": "Jak používat asistenta",
        # Recent runs
        "recent_default_title": "Profile build",
        "recent_empty_title": "Žádné uložené runy",
        # Chat tab
        "chat_placeholder": "Zeptej se na cokoliv ohledně tvého LinkedIn profilu…",
        "chat_attachments_label": "Přílohy",
        "chat_quick_actions_title": "Zkus rychlý prompt",
        "chat_qa_improve_headline": "Vylepši můj headline",
        "chat_qa_write_learning_post": "Napiš learning-update post",
        "chat_qa_critique_about": "Zhodnoť moji About sekci",
        "chat_qa_recruiter_dm": "Naváhej recruiter outreach DM",
        "chat_running": "Přemýšlím…",
        # History tab
        "history_empty_title": "Zatím nic uloženo",
        "history_empty_desc": "Ulož kompletní profile build a objeví se tu.",
        "history_open": "Otevřít složku",
        "history_score": "Skóre",
        # Errors
        "error_no_inputs": "Přidej CV, LinkedIn export nebo poznámky před spuštěním buildu.",
        "error_no_target_role": "Přidej alespoň jednu cílovou pozici.",
        "error_run_failed_title": "Profile build selhal",
        # How-to texts
        "howto_title": "Jak používat AI LinkedIn",
        "howto_what_title": "Co tahle sekce dělá",
        "howto_what_text": (
            "Postaví kompletní recruiter-ready LinkedIn profil z tvého CV, LinkedIn exportu a GitHubu."
            " Můžeš taky generovat jen jednu sekci (headline, About, posty, recruiter DM) nebo si"
            " povídat s LinkedIn voice expertem."
        ),
        "howto_prepare_title": "Co si připravit",
        "howto_prepare_text": (
            "PDF životopis, případně LinkedIn data export, případně GitHub uživatele a seznam pozic,"
            " na které cílíš. Čím bohatší vstup, tím podloženější výstup."
        ),
        "howto_quality_title": "Tipy ke kvalitě",
        "howto_quality_text": (
            "Při prvním běhu zapni 'Doptat se' - AI se nejdřív zeptá, než si začne vymýšlet. Vyber"
            " publikum podle cíle (recruiter vs. kolegové). Na každé kartě je 'Doladit s AI', když"
            " chceš sevřenější verzi."
        ),
        "howto_wont_title": "Co NEUDĚLÁ",
        "howto_wont_text": (
            "Nikdy si nevymyslí certifikát, ocenění, patent ani citát. Co nemá důkaz, skončí v koši"
            " 'Ověř' / 'Neuvádět', ať si to potvrdíš před zveřejněním."
        ),
        "howto_close": "Rozumím",
        # Followup dialog (shared copy)
        "followup_dialog_title": "Rychlé doplnění",
        "followup_dialog_subtitle": "Odpověz na pár otázek, ať profil opřu o tvé reálné signály.",
        "followup_dialog_skip": "Přeskočit",
        "followup_dialog_submit": "Pokračovat",
        "followup_dialog_cancel": "Zrušit",
        "followup_dialog_other_label": "Jiné",
        "followup_dialog_other_hint": "Napiš vlastní odpověď…",
        "followup_dialog_skip_all": "Přeskočit vše",
        "followup_dialog_answer_hint": "Tvoje odpověď (volitelné)",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
