"""EN + CS copy for the AI LinkedIn section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI LinkedIn",
        "title": "AI LinkedIn",
        "subtitle": "I turn your raw notes into LinkedIn posts, articles and headlines that get noticed.",
        "tab_chat": "Chat",
        "tab_post": "Post writer",
        "tab_carousel": "Carousel",
        "tab_article": "Article",
        "tab_headlines": "Headlines",
        "tab_comments": "Comments",
        "tab_templates": "Templates",
        "msg1_user": "I shipped our new onboarding flow this week and signups jumped 18%. Help me turn that into a LinkedIn post.",
        "msg2_intro": "Nice win - here's a draft post tuned for LinkedIn:",
        "msg2_hook_title": "Hook",
        "msg2_hook_text": "We rebuilt onboarding in two weeks. Signups jumped 18%. Here's what we changed.",
        "msg2_body_title": "Body",
        "msg2_body_text": "We had been blaming traffic. The real problem was friction in step 3 - users dropped off when we asked for a credit card before they saw a single 'aha' moment.",
        "msg2_bullets_title": "Three changes that moved the needle",
        "msg2_bullet1": "Reordered the steps - value first, payment last.",
        "msg2_bullet2": "Cut copy by 40% on every screen.",
        "msg2_bullet3": "Added a one-click sample workspace.",
        "msg2_cta_title": "Call to action",
        "msg2_cta_text": "What's the highest-friction step in your onboarding right now? Curious how others tackled it.",
        "msg2_hashtags_title": "Hashtags",
        "msg2_hashtags_text": "#Product #Onboarding #SaaS #StartupLessons",
        "action_copy": "Copy post",
        "action_shorten": "Shorten",
        "action_hashtags": "More hashtags",
        "action_tone": "Different tone",
        "action_schedule": "Schedule",
        "post_title": "Post writer",
        "post_desc": "Drop in a few notes and we'll structure a LinkedIn post around them.",
        "post_field_idea": "Your idea",
        "post_field_idea_hint": "What happened, what you learned, what to ask...",
        "post_field_goal": "Post goal",
        "post_field_goal_hint": "Awareness, hiring, thought leadership...",
        "post_field_format": "Format",
        "post_field_format_hint": "Story, list, contrarian take, lessons learned...",
        "post_example_1": "Hook + body + CTA structure.",
        "post_example_2": "Optimised line length for mobile reading.",
        "post_example_3": "Hashtag suggestions tuned to your industry.",
        "carousel_title": "Carousel",
        "carousel_desc": "Outline a 6-10 slide carousel from a single topic.",
        "carousel_field_topic_hint": "5 lessons from launching our first product",
        "carousel_field_takeaway": "Main takeaway",
        "carousel_field_takeaway_hint": "What should the reader remember?",
        "carousel_field_slides": "Slide count",
        "carousel_field_slides_hint": "6 / 8 / 10 slides",
        "carousel_example_1": "Title slide + outro slide auto-included.",
        "carousel_example_2": "Each slide has a hook + body + visual hint.",
        "carousel_example_3": "Suggested colour palette per topic.",
        "article_title": "Article",
        "article_desc": "Long-form draft with intro, sections and a clear closer.",
        "article_field_thesis": "Thesis",
        "article_field_thesis_hint": "What's the argument in one sentence?",
        "article_field_outline": "Outline (optional)",
        "article_field_outline_hint": "Bullet the sections you want covered.",
        "article_field_audience_hint": "Founders, marketers, engineers...",
        "article_example_1": "1200-1800 word structure with H2s.",
        "article_example_2": "Auto-generated TL;DR at the top.",
        "article_example_3": "Suggested cover image direction.",
        "headlines_title": "Headlines",
        "headlines_desc": "Generate 10 hook variants in your tone of voice.",
        "headlines_field_topic_hint": "Why we left Notion for Linear",
        "headlines_field_angles": "Angles to try",
        "headlines_field_angles_hint": "Contrarian, story, listicle, data-driven...",
        "headlines_example_1": "Mix of question, story and data hooks.",
        "headlines_example_2": "Character-count badge per headline.",
        "headlines_example_3": "Predicted scroll-stop score.",
        "comments_title": "Comments",
        "comments_desc": "Draft thoughtful replies that add value (no generic 'great post!').",
        "comments_field_post": "The post you're replying to",
        "comments_field_post_hint": "Paste the post or its key idea.",
        "comments_field_angle": "Your angle",
        "comments_field_angle_hint": "Agree, disagree, share an example...",
        "comments_example_1": "3 comment variants per post.",
        "comments_example_2": "Suggested follow-up question.",
        "comments_example_3": "Tone matched to the original poster.",
        "tpl_title": "Templates",
        "tpl_desc": "Pick a starting point - we'll tune it to your brand.",
        "tpl_use": "Use template",
        "tpl_announcement_title": "Product announcement",
        "tpl_announcement_desc": "Hook + features + social proof + CTA.",
        "tpl_lesson_title": "Lesson learned",
        "tpl_lesson_desc": "Story-driven post with one clear takeaway.",
        "tpl_hiring_title": "We're hiring",
        "tpl_hiring_desc": "Role + team + apply link, no jargon.",
        "tpl_milestone_title": "Milestone post",
        "tpl_milestone_desc": "Celebrate without sounding boastful.",
        "tpl_thread_title": "Comment thread starter",
        "tpl_thread_desc": "Question post designed to drive replies.",
        "tpl_personal_title": "Personal story",
        "tpl_personal_desc": "Vulnerable opener with a professional twist.",
        "brief_title": "Brand profile",
        "brief_name_label": "Name",
        "brief_name": "Jan Novák",
        "brief_role_label": "Role",
        "brief_role": "Senior Product Manager @ Acme",
        "brief_industry_label": "Industry",
        "brief_industry": "B2B SaaS",
        "brief_audience_label": "Audience",
        "brief_audience": "Founders, PMs, growth marketers",
        "brief_tone_label": "Tone",
        "brief_tone": "Direct, warm, lightly contrarian",
        "qa_post": "Write a post",
        "qa_polish": "Polish article",
        "qa_headlines": "Headline ideas",
        "qa_comment": "Comment helper",
        "qa_connection": "Connection note",
        "history_1": "Onboarding rebuild post",
        "history_1_time": "10:42",
        "history_2": "Carousel - 5 launch lessons",
        "history_2_time": "Yesterday",
        "history_3": "Article - PM hiring loop",
        "history_3_time": "2 days ago",
        "history_4": "Comment helper - growth post",
        "history_4_time": "3 days ago",
    },
    "cs": {
        "nav_label": "AI LinkedIn",
        "title": "AI LinkedIn",
        "subtitle": "Z tvých poznámek udělám LinkedIn posty, články a nadpisy, které si lidi všimnou.",
        "tab_chat": "Chat",
        "tab_post": "Tvůrce postu",
        "tab_carousel": "Carousel",
        "tab_article": "Článek",
        "tab_headlines": "Nadpisy",
        "tab_comments": "Komentáře",
        "tab_templates": "Šablony",
        "msg1_user": "Tenhle týden jsme nasadili nový onboarding a registrace vyskočily o 18 %. Pomoz mi z toho udělat LinkedIn post.",
        "msg2_intro": "Pěkná výhra - tady je draft postu šitý LinkedInu na míru:",
        "msg2_hook_title": "Hook",
        "msg2_hook_text": "Předělali jsme onboarding za dva týdny. Registrace vyskočily o 18 %. Co jsme změnili.",
        "msg2_body_title": "Tělo",
        "msg2_body_text": "Dlouho jsme to sváděli na traffic. Skutečný problém byl ve 3. kroku - lidi odpadali, když jsme chtěli platební kartu dřív, než vůbec viděli nějaký 'aha' moment.",
        "msg2_bullets_title": "Tři změny, které posunuly čísla",
        "msg2_bullet1": "Přerovnali jsme kroky - hodnota první, platba poslední.",
        "msg2_bullet2": "Zkrátili jsme texty na každé obrazovce o 40 %.",
        "msg2_bullet3": "Přidali jsme ukázkový workspace na jeden klik.",
        "msg2_cta_title": "Výzva k akci",
        "msg2_cta_text": "Jaký je teď nejtěžší krok ve vašem onboardingu? Zajímá mě, jak to řešíte.",
        "msg2_hashtags_title": "Hashtagy",
        "msg2_hashtags_text": "#Produkt #Onboarding #SaaS #StartupLessons",
        "action_copy": "Zkopírovat post",
        "action_shorten": "Zkrátit",
        "action_hashtags": "Další hashtagy",
        "action_tone": "Jiný tón",
        "action_schedule": "Naplánovat",
        "post_title": "Tvůrce postu",
        "post_desc": "Vlož pár poznámek a my z nich postavíme LinkedIn post.",
        "post_field_idea": "Tvůj nápad",
        "post_field_idea_hint": "Co se stalo, co jsi se naučil, co se chceš zeptat...",
        "post_field_goal": "Cíl postu",
        "post_field_goal_hint": "Povědomí, nábor, thought leadership...",
        "post_field_format": "Formát",
        "post_field_format_hint": "Příběh, list, kontroverze, lessons learned...",
        "post_example_1": "Struktura hook + tělo + CTA.",
        "post_example_2": "Optimalizovaná délka řádku pro mobil.",
        "post_example_3": "Návrhy hashtagů podle oboru.",
        "carousel_title": "Carousel",
        "carousel_desc": "Vytvoř osnovu 6-10 slidů z jednoho tématu.",
        "carousel_field_topic_hint": "5 lekcí ze spuštění našeho prvního produktu",
        "carousel_field_takeaway": "Hlavní myšlenka",
        "carousel_field_takeaway_hint": "Co si má čtenář zapamatovat?",
        "carousel_field_slides": "Počet slidů",
        "carousel_field_slides_hint": "6 / 8 / 10 slidů",
        "carousel_example_1": "Titulní + závěrečný slide automaticky.",
        "carousel_example_2": "Každý slide má hook + tělo + návrh vizuálu.",
        "carousel_example_3": "Doporučená barevná paleta podle tématu.",
        "article_title": "Článek",
        "article_desc": "Dlouhá forma s úvodem, sekcemi a jasným závěrem.",
        "article_field_thesis": "Hlavní myšlenka",
        "article_field_thesis_hint": "O co ti jde - jednou větou?",
        "article_field_outline": "Osnova (volitelné)",
        "article_field_outline_hint": "Vypiš sekce, které mají zaznít.",
        "article_field_audience_hint": "Zakladatelé, marketéři, vývojáři...",
        "article_example_1": "Struktura na 1200-1800 slov s H2.",
        "article_example_2": "Auto-vygenerované TL;DR na začátku.",
        "article_example_3": "Návrh směru pro hero obrázek.",
        "headlines_title": "Nadpisy",
        "headlines_desc": "Vygeneruj 10 variant hooku v tvém tónu.",
        "headlines_field_topic_hint": "Proč jsme přešli z Notionu na Linear",
        "headlines_field_angles": "Úhly pohledu",
        "headlines_field_angles_hint": "Kontroverzní, příběh, listicle, datový...",
        "headlines_example_1": "Mix otázky, příběhu a datového hooku.",
        "headlines_example_2": "Počet znaků u každého nadpisu.",
        "headlines_example_3": "Odhadované 'scroll-stop' skóre.",
        "comments_title": "Komentáře",
        "comments_desc": "Smysluplné odpovědi, které přidávají hodnotu (žádné 'super post!').",
        "comments_field_post": "Post, na který odpovídáš",
        "comments_field_post_hint": "Vlož post nebo jeho hlavní myšlenku.",
        "comments_field_angle": "Tvůj úhel",
        "comments_field_angle_hint": "Souhlasím, nesouhlasím, sdílím příklad...",
        "comments_example_1": "3 varianty komentáře na jeden post.",
        "comments_example_2": "Návrh navazující otázky.",
        "comments_example_3": "Tón sladěný s původním autorem.",
        "tpl_title": "Šablony",
        "tpl_desc": "Vyber startovní bod - šablonu doladíme k tvé značce.",
        "tpl_use": "Použít šablonu",
        "tpl_announcement_title": "Oznámení produktu",
        "tpl_announcement_desc": "Hook + features + social proof + CTA.",
        "tpl_lesson_title": "Lesson learned",
        "tpl_lesson_desc": "Příběh s jednou jasnou pointou.",
        "tpl_hiring_title": "Nabíráme",
        "tpl_hiring_desc": "Role + tým + odkaz na hlášení, bez frází.",
        "tpl_milestone_title": "Milník",
        "tpl_milestone_desc": "Oslav, aniž to znělo namyšleně.",
        "tpl_thread_title": "Otázkový post",
        "tpl_thread_desc": "Post navržený k vyvolání odpovědí.",
        "tpl_personal_title": "Osobní příběh",
        "tpl_personal_desc": "Otevřený úvod s profesionálním přesahem.",
        "brief_title": "Profil značky",
        "brief_name_label": "Jméno",
        "brief_name": "Jan Novák",
        "brief_role_label": "Role",
        "brief_role": "Senior Product Manager @ Acme",
        "brief_industry_label": "Obor",
        "brief_industry": "B2B SaaS",
        "brief_audience_label": "Publikum",
        "brief_audience": "Zakladatelé, PM, growth marketéři",
        "brief_tone_label": "Tón",
        "brief_tone": "Přímý, vřelý, lehce kontroverzní",
        "qa_post": "Napsat post",
        "qa_polish": "Doladit článek",
        "qa_headlines": "Nápady na nadpisy",
        "qa_comment": "Pomocník na komentáře",
        "qa_connection": "Žádost o spojení",
        "history_1": "Post - rebuild onboardingu",
        "history_1_time": "10:42",
        "history_2": "Carousel - 5 lekcí z launche",
        "history_2_time": "Včera",
        "history_3": "Článek - PM hiring loop",
        "history_3_time": "2 dny zpět",
        "history_4": "Pomocník - growth post",
        "history_4_time": "3 dny zpět",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
