"""EN + CS copy for the AI Finance section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Smart financial assistant for managing money, investments and planning.",
        "tab_chat": "Chat",
        "tab_budget": "Budget",
        "tab_invest": "Investments",
        "tab_analysis": "Analysis",
        "tab_taxes": "Taxes",
        "tab_insurance": "Insurance",
        "tab_calculators": "Calculators",
        "tab_templates": "Templates",
        "budget_mock_title": "Build a budget",
        "budget_mock_desc": "Plug in income and goals - we'll suggest a 50/30/20 split.",
        "budget_field_income": "Monthly income (net)",
        "budget_field_income_hint": "$2,000",
        "budget_field_savings": "Savings goal",
        "budget_field_savings_hint": "How much do you want to save?",
        "budget_field_essentials": "Top essentials",
        "budget_field_essentials_hint": "Rent, utilities, groceries...",
        "budget_field_lifestyle": "Lifestyle priorities",
        "budget_field_lifestyle_hint": "Travel, hobbies, fitness...",
        "budget_example_1": "Donut chart with category split.",
        "budget_example_2": "Auto-detect categories from past spend.",
        "budget_example_3": "Compare to recommended ranges.",
        "invest_title": "Investment ideas",
        "invest_desc": "Personalised ideas for your risk profile and horizon.",
        "invest_field_amount": "Amount to invest",
        "invest_field_amount_hint": "$5,000",
        "invest_field_horizon": "Horizon",
        "invest_field_horizon_hint": "1 year, 5 years, 20+ years",
        "invest_field_risk": "Risk appetite",
        "invest_field_risk_hint": "Low / medium / high",
        "invest_field_focus": "Focus",
        "invest_field_focus_hint": "ETFs, individual stocks, crypto, mix",
        "invest_example_1": "3 portfolio templates with allocations.",
        "invest_example_2": "Estimated yield with compounding.",
        "invest_example_3": "Risk warning + rebalancing notes.",
        "analysis_title": "Spend analysis",
        "analysis_desc": "Upload statements and get a breakdown by category and merchant.",
        "analysis_field_period": "Period",
        "analysis_field_period_hint": "Last 30 days, this quarter, YTD",
        "analysis_field_focus": "Focus",
        "analysis_field_focus_hint": "Subscriptions, eating out, transport...",
        "analysis_field_goal": "What do you want to know?",
        "analysis_field_goal_hint": "Where can I cut $200?",
        "analysis_example_1": "Sankey diagram of cash flow.",
        "analysis_example_2": "Outliers vs your monthly baseline.",
        "analysis_example_3": "Auto-flagged duplicate subscriptions.",
        "taxes_title": "Tax helper",
        "taxes_desc": "Walk through your situation and get a checklist.",
        "taxes_field_country": "Country",
        "taxes_field_country_hint": "Czech Republic, Slovakia, Germany...",
        "taxes_field_status": "Filing status",
        "taxes_field_status_hint": "Employee, self-employed, both",
        "taxes_field_year": "Tax year",
        "taxes_field_year_hint": "e.g. 2024",
        "taxes_field_notes": "Anything special?",
        "taxes_field_notes_hint": "Crypto, foreign income, mortgage...",
        "taxes_example_1": "Step-by-step deduction checklist.",
        "taxes_example_2": "Estimated refund preview.",
        "taxes_example_3": "Reminders for upcoming deadlines.",
        "insurance_title": "Insurance review",
        "insurance_desc": "See what you're missing or overpaying for.",
        "insurance_field_household": "Household size",
        "insurance_field_household_hint": "1, 2, family of 4...",
        "insurance_field_assets": "Main assets",
        "insurance_field_assets_hint": "Apartment, car, equipment...",
        "insurance_field_existing": "Existing policies",
        "insurance_field_existing_hint": "Liability, life, auto, travel...",
        "insurance_field_concerns": "Top concerns",
        "insurance_field_concerns_hint": "Medical, accidents, theft...",
        "insurance_example_1": "Coverage gap heatmap.",
        "insurance_example_2": "Premium benchmarks vs market.",
        "insurance_example_3": "Suggested policy bundles.",
        "calc_title": "Calculators",
        "calc_desc": "Quick-use calculators for the most common decisions.",
        "calc_compound_title": "Compound interest",
        "calc_compound_desc": "Project savings over time at any rate.",
        "calc_mortgage_title": "Mortgage payment",
        "calc_mortgage_desc": "Monthly payment for any rate and term.",
        "calc_loan_title": "Loan affordability",
        "calc_loan_desc": "How much can you safely borrow?",
        "calc_retirement_title": "Retirement planner",
        "calc_retirement_desc": "Goal income vs current pace.",
        "calc_currency_title": "Currency converter",
        "calc_currency_desc": "Live FX with historical chart.",
        "calc_savings_title": "Savings goal",
        "calc_savings_desc": "Plan deposits to hit a target by a date.",
        "fin_tpl_title": "Templates",
        "fin_tpl_desc": "Spreadsheets and trackers ready to download.",
        "fin_tpl_use": "Open template",
        "fin_tpl_budget_title": "50/30/20 budget tracker",
        "fin_tpl_budget_desc": "Monthly tracker with category split.",
        "fin_tpl_invest_title": "Portfolio overview",
        "fin_tpl_invest_desc": "Holdings, allocation and YTD return.",
        "fin_tpl_debt_title": "Debt payoff plan",
        "fin_tpl_debt_desc": "Snowball vs avalanche side by side.",
        "fin_tpl_emergency_title": "Emergency fund plan",
        "fin_tpl_emergency_desc": "Calculate target + timeline to get there.",
        "msg1_user": "Help me put together a monthly budget. I earn $2,000 and want to save and invest more.",
        "msg2_intro": "Sure! Here is a monthly budget proposal for $2,000 with a focus on saving and investing.",
        "budget_title": "Recommended 50/30/20 budget",
        "budget_subtitle": "A proven rule for healthy finances.",
        "donut_caption_top": "$2,000",
        "donut_caption_bottom": "/ month",
        "needs_label": "50% Needs",
        "needs_value": "$1,000",
        "needs_note": "Housing, food, transport, utilities...",
        "wants_label": "30% Wants",
        "wants_value": "$600",
        "wants_note": "Entertainment, travel, hobbies...",
        "saving_label": "20% Saving & Investing",
        "saving_value": "$400",
        "saving_note": "Emergency fund, investments, future...",
        "breakdown_title": "Detailed breakdown",
        "col_category": "Category",
        "col_recommended": "Recommended",
        "col_amount": "Your amount",
        "col_note": "Note",
        "row_housing": "Housing",
        "row_housing_note": "Rent, utilities, internet",
        "row_food": "Food",
        "row_food_note": "Groceries, dining out",
        "row_transport": "Transport",
        "row_transport_note": "Fuel, public transit, insurance",
        "row_other_needs": "Other essentials",
        "row_other_needs_note": "Healthcare, clothing, services",
        "row_wants": "Wants",
        "row_wants_note": "Entertainment, hobbies, travel",
        "row_saving": "Saving & Investing",
        "row_saving_note": "Emergency, investments, future",
        "action_edit_budget": "Edit budget",
        "action_create_chart": "Create chart",
        "action_save_plan": "Saving plan",
        "action_invest_plan": "Investment plan",
        "action_export": "Export",
        "input_hint": "Type your question...",
        "quick_title": "Quick actions",
        "quick_create_budget": "Create a budget",
        "quick_analyze_expenses": "Analyse expenses",
        "quick_invest_advice": "Investment recommendations",
        "quick_tax_guide": "Tax guide",
        "quick_calculators": "Calculators",
        "markets_title": "Market overview",
        "markets_show_detail": "Show detail",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / USD",
        "analyses_title": "Recent analyses",
        "analyses_show_all": "Show all",
        "analysis_1": "Monthly budget - May 2024",
        "analysis_1_time": "Today 10:15",
        "analysis_2": "Investment portfolio analysis",
        "analysis_2_time": "Yesterday",
        "analysis_3": "Savings account comparison",
        "analysis_3_time": "2 days ago",
        "analysis_4": "Tax return - guide",
        "analysis_4_time": "3 days ago",
        "tip_title": "Tip of the day",
        "tip_text": "Investing small amounts regularly lets you harness the power of compound interest.",
    },
    "cs": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Chytrý finanční asistent pro správu financí, investice a plánování.",
        "tab_chat": "Chat",
        "tab_budget": "Rozpočet",
        "tab_invest": "Investice",
        "tab_analysis": "Analýza",
        "tab_taxes": "Daně",
        "tab_insurance": "Pojištění",
        "tab_calculators": "Kalkulačky",
        "tab_templates": "Šablony",
        "budget_mock_title": "Sestavit rozpočet",
        "budget_mock_desc": "Zadej příjmy a cíle - navrhneme rozdělení 50/30/20.",
        "budget_field_income": "Měsíční příjem (čistý)",
        "budget_field_income_hint": "45 000 Kč",
        "budget_field_savings": "Cíl spoření",
        "budget_field_savings_hint": "Kolik chceš měsíčně odkládat?",
        "budget_field_essentials": "Hlavní výdaje",
        "budget_field_essentials_hint": "Nájem, energie, jídlo...",
        "budget_field_lifestyle": "Co si chceš dopřát",
        "budget_field_lifestyle_hint": "Cestování, koníčky, fitness...",
        "budget_example_1": "Donut graf s rozdělením kategorií.",
        "budget_example_2": "Auto-detekce kategorií z minulých výdajů.",
        "budget_example_3": "Porovnání s doporučenými hodnotami.",
        "invest_title": "Investiční nápady",
        "invest_desc": "Personalizované nápady podle rizikovosti a horizontu.",
        "invest_field_amount": "Částka k investici",
        "invest_field_amount_hint": "120 000 Kč",
        "invest_field_horizon": "Horizont",
        "invest_field_horizon_hint": "1 rok, 5 let, 20+ let",
        "invest_field_risk": "Tolerance rizika",
        "invest_field_risk_hint": "Nízká / střední / vysoká",
        "invest_field_focus": "Zaměření",
        "invest_field_focus_hint": "ETF, jednotlivé akcie, krypto, mix",
        "invest_example_1": "3 šablony portfolií s alokací.",
        "invest_example_2": "Odhad výnosu se složeným úročením.",
        "invest_example_3": "Upozornění na rizika + rebalanc.",
        "analysis_title": "Analýza výdajů",
        "analysis_desc": "Nahraj výpisy a získej rozbor podle kategorií a obchodníků.",
        "analysis_field_period": "Období",
        "analysis_field_period_hint": "Posledních 30 dní, kvartál, YTD",
        "analysis_field_focus": "Zaměření",
        "analysis_field_focus_hint": "Předplatné, restaurace, doprava...",
        "analysis_field_goal": "Co chceš zjistit?",
        "analysis_field_goal_hint": "Kde můžu uspořit 5 000 Kč?",
        "analysis_example_1": "Sankey diagram cash flow.",
        "analysis_example_2": "Odlehlé hodnoty oproti průměru.",
        "analysis_example_3": "Auto-detekce duplicitních předplatných.",
        "taxes_title": "Daňový pomocník",
        "taxes_desc": "Projdi svou situaci a získej checklist.",
        "taxes_field_country": "Země",
        "taxes_field_country_hint": "Česko, Slovensko, Německo...",
        "taxes_field_status": "Status",
        "taxes_field_status_hint": "Zaměstnanec, OSVČ, oboje",
        "taxes_field_year": "Daňový rok",
        "taxes_field_year_hint": "např. 2024",
        "taxes_field_notes": "Něco specifického?",
        "taxes_field_notes_hint": "Krypto, příjem ze zahraničí, hypotéka...",
        "taxes_example_1": "Krok-za-krokem checklist odpočtů.",
        "taxes_example_2": "Náhled odhadovaného přeplatku.",
        "taxes_example_3": "Připomenutí blížících se termínů.",
        "insurance_title": "Pojištění",
        "insurance_desc": "Zjisti, kde ti chybí pojistka nebo platíš zbytečně.",
        "insurance_field_household": "Velikost domácnosti",
        "insurance_field_household_hint": "1, 2, rodina 4 osoby...",
        "insurance_field_assets": "Hlavní majetek",
        "insurance_field_assets_hint": "Byt, auto, vybavení...",
        "insurance_field_existing": "Stávající smlouvy",
        "insurance_field_existing_hint": "Odpovědnost, životní, auto, cesťák...",
        "insurance_field_concerns": "Hlavní obavy",
        "insurance_field_concerns_hint": "Zdraví, úrazy, krádež...",
        "insurance_example_1": "Heatmapa mezer v krytí.",
        "insurance_example_2": "Porovnání pojistného s trhem.",
        "insurance_example_3": "Doporučené balíčky pojistek.",
        "calc_title": "Kalkulačky",
        "calc_desc": "Rychlé kalkulačky pro nejčastější rozhodnutí.",
        "calc_compound_title": "Složené úročení",
        "calc_compound_desc": "Spočti zhodnocení v čase při libovolné sazbě.",
        "calc_mortgage_title": "Splátka hypotéky",
        "calc_mortgage_desc": "Měsíční splátka pro libovolnou sazbu a délku.",
        "calc_loan_title": "Bonita půjčky",
        "calc_loan_desc": "Kolik si můžeš bezpečně půjčit?",
        "calc_retirement_title": "Důchodový plán",
        "calc_retirement_desc": "Cílový důchod vs. aktuální tempo.",
        "calc_currency_title": "Převodník měn",
        "calc_currency_desc": "Aktuální FX + historický graf.",
        "calc_savings_title": "Cíl spoření",
        "calc_savings_desc": "Naplánuj vklady tak, aby ses k cíli dostal v čas.",
        "fin_tpl_title": "Šablony",
        "fin_tpl_desc": "Tabulky a trackery ke stažení.",
        "fin_tpl_use": "Otevřít šablonu",
        "fin_tpl_budget_title": "Tracker rozpočtu 50/30/20",
        "fin_tpl_budget_desc": "Měsíční tracker s rozdělením kategorií.",
        "fin_tpl_invest_title": "Přehled portfolia",
        "fin_tpl_invest_desc": "Pozice, alokace a YTD výnos.",
        "fin_tpl_debt_title": "Plán splacení dluhů",
        "fin_tpl_debt_desc": "Snowball vs. avalanche vedle sebe.",
        "fin_tpl_emergency_title": "Plán rezervy",
        "fin_tpl_emergency_desc": "Spočti cíl + čas, za který tam dojdeš.",
        "msg1_user": "Pomoz mi vytvořit měsíční rozpočet. Mám příjem 45 000 Kč a chci víc spořit a investovat.",
        "msg2_intro": "Jasně! Tady je návrh měsíčního rozpočtu 45 000 Kč s důrazem na spoření a investice.",
        "budget_title": "Doporučený rozpočet 50/30/20",
        "budget_subtitle": "Osvědčené pravidlo pro zdravé finance.",
        "donut_caption_top": "45 000 Kč",
        "donut_caption_bottom": "měsíčně",
        "needs_label": "50% Potřeby",
        "needs_value": "22 500 Kč",
        "needs_note": "Bydlení, jídlo, doprava, energie...",
        "wants_label": "30% Přání",
        "wants_value": "13 500 Kč",
        "wants_note": "Zábava, cestování, koníčky...",
        "saving_label": "20% Spoření & Investice",
        "saving_value": "9 000 Kč",
        "saving_note": "Rezerva, investice, budoucnost...",
        "breakdown_title": "Detailní rozpis",
        "col_category": "Kategorie",
        "col_recommended": "Doporučeno",
        "col_amount": "Vaše částka",
        "col_note": "Poznámka",
        "row_housing": "Bydlení",
        "row_housing_note": "Nájem, energie, internet",
        "row_food": "Jídlo",
        "row_food_note": "Potraviny, stravování",
        "row_transport": "Doprava",
        "row_transport_note": "Palivo, MHD, pojištění",
        "row_other_needs": "Ostatní potřeby",
        "row_other_needs_note": "Zdraví, oblečení, služby",
        "row_wants": "Přání",
        "row_wants_note": "Zábava, koníčky, cestování",
        "row_saving": "Spoření & Investice",
        "row_saving_note": "Rezerva, investice, budoucnost",
        "action_edit_budget": "Upravit rozpočet",
        "action_create_chart": "Vytvořit graf",
        "action_save_plan": "Návrh spoření",
        "action_invest_plan": "Investiční plán",
        "action_export": "Exportovat",
        "input_hint": "Napište svou otázku...",
        "quick_title": "Rychlé akce",
        "quick_create_budget": "Vytvořit rozpočet",
        "quick_analyze_expenses": "Analyzovat výdaje",
        "quick_invest_advice": "Investiční doporučení",
        "quick_tax_guide": "Daňový průvodce",
        "quick_calculators": "Kalkulačky",
        "markets_title": "Přehled trhů",
        "markets_show_detail": "Zobrazit detail",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / CZK",
        "analyses_title": "Nedávné analýzy",
        "analyses_show_all": "Zobrazit vše",
        "analysis_1": "Měsíční rozpočet - květen 2024",
        "analysis_1_time": "Dnes 10:15",
        "analysis_2": "Investiční analýza portfolia",
        "analysis_2_time": "Včera",
        "analysis_3": "Srovnání spořicích účtů",
        "analysis_3_time": "2 dny zpět",
        "analysis_4": "Daňové přiznání - průvodce",
        "analysis_4_time": "3 dny zpět",
        "tip_title": "Tip dne",
        "tip_text": "Pravidelným investováním i menších částek využijete sílu složeného úročení.",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
