"""EN + CS copy for the AI Finance section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Smart financial assistant for managing money, investments and planning.",
        "tab_chat": "Chat",
        "tab_budget": "Budget",
        "tab_invest": "Investments",
        "tab_analysis": "Analysis",
        "tab_taxes": "Taxes",
        "tab_insurance": "Insurance",
        "tab_calculators": "Calculators",
        "tab_templates": "Templates",
        "msg1_user": "Help me put together a monthly budget. I earn $2,000 and want to save and invest more.",
        "msg2_intro": "Sure! Here is a monthly budget proposal for $2,000 with a focus on saving and investing.",
        "budget_title": "Recommended 50/30/20 budget",
        "budget_subtitle": "A proven rule for healthy finances.",
        "donut_caption_top": "$2,000",
        "donut_caption_bottom": "/ month",
        "needs_label": "50% Needs",
        "needs_value": "$1,000",
        "needs_note": "Housing, food, transport, utilities...",
        "wants_label": "30% Wants",
        "wants_value": "$600",
        "wants_note": "Entertainment, travel, hobbies...",
        "saving_label": "20% Saving & Investing",
        "saving_value": "$400",
        "saving_note": "Emergency fund, investments, future...",
        "breakdown_title": "Detailed breakdown",
        "col_category": "Category",
        "col_recommended": "Recommended",
        "col_amount": "Your amount",
        "col_note": "Note",
        "row_housing": "Housing",
        "row_housing_note": "Rent, utilities, internet",
        "row_food": "Food",
        "row_food_note": "Groceries, dining out",
        "row_transport": "Transport",
        "row_transport_note": "Fuel, public transit, insurance",
        "row_other_needs": "Other essentials",
        "row_other_needs_note": "Healthcare, clothing, services",
        "row_wants": "Wants",
        "row_wants_note": "Entertainment, hobbies, travel",
        "row_saving": "Saving & Investing",
        "row_saving_note": "Emergency, investments, future",
        "action_edit_budget": "Edit budget",
        "action_create_chart": "Create chart",
        "action_save_plan": "Saving plan",
        "action_invest_plan": "Investment plan",
        "action_export": "Export",
        "input_hint": "Type your question...",
        "quick_title": "Quick actions",
        "quick_create_budget": "Create a budget",
        "quick_analyze_expenses": "Analyse expenses",
        "quick_invest_advice": "Investment recommendations",
        "quick_tax_guide": "Tax guide",
        "quick_calculators": "Calculators",
        "markets_title": "Market overview",
        "markets_show_detail": "Show detail",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / USD",
        "analyses_title": "Recent analyses",
        "analyses_show_all": "Show all",
        "analysis_1": "Monthly budget - May 2024",
        "analysis_1_time": "Today 10:15",
        "analysis_2": "Investment portfolio analysis",
        "analysis_2_time": "Yesterday",
        "analysis_3": "Savings account comparison",
        "analysis_3_time": "2 days ago",
        "analysis_4": "Tax return - guide",
        "analysis_4_time": "3 days ago",
        "tip_title": "Tip of the day",
        "tip_text": "Investing small amounts regularly lets you harness the power of compound interest.",
    },
    "cs": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Chytrý finanční asistent pro správu financí, investice a plánování.",
        "tab_chat": "Chat",
        "tab_budget": "Rozpočet",
        "tab_invest": "Investice",
        "tab_analysis": "Analýza",
        "tab_taxes": "Daně",
        "tab_insurance": "Pojištění",
        "tab_calculators": "Kalkulačky",
        "tab_templates": "Šablony",
        "msg1_user": "Pomoz mi vytvořit měsíční rozpočet. Mám příjem 45 000 Kč a chci víc spořit a investovat.",
        "msg2_intro": "Jasně! Tady je návrh měsíčního rozpočtu 45 000 Kč s důrazem na spoření a investice.",
        "budget_title": "Doporučený rozpočet 50/30/20",
        "budget_subtitle": "Osvědčené pravidlo pro zdravé finance.",
        "donut_caption_top": "45 000 Kč",
        "donut_caption_bottom": "měsíčně",
        "needs_label": "50% Potřeby",
        "needs_value": "22 500 Kč",
        "needs_note": "Bydlení, jídlo, doprava, energie...",
        "wants_label": "30% Přání",
        "wants_value": "13 500 Kč",
        "wants_note": "Zábava, cestování, koníčky...",
        "saving_label": "20% Spoření & Investice",
        "saving_value": "9 000 Kč",
        "saving_note": "Rezerva, investice, budoucnost...",
        "breakdown_title": "Detailní rozpis",
        "col_category": "Kategorie",
        "col_recommended": "Doporučeno",
        "col_amount": "Vaše částka",
        "col_note": "Poznámka",
        "row_housing": "Bydlení",
        "row_housing_note": "Nájem, energie, internet",
        "row_food": "Jídlo",
        "row_food_note": "Potraviny, stravování",
        "row_transport": "Doprava",
        "row_transport_note": "Palivo, MHD, pojištění",
        "row_other_needs": "Ostatní potřeby",
        "row_other_needs_note": "Zdraví, oblečení, služby",
        "row_wants": "Přání",
        "row_wants_note": "Zábava, koníčky, cestování",
        "row_saving": "Spoření & Investice",
        "row_saving_note": "Rezerva, investice, budoucnost",
        "action_edit_budget": "Upravit rozpočet",
        "action_create_chart": "Vytvořit graf",
        "action_save_plan": "Návrh spoření",
        "action_invest_plan": "Investiční plán",
        "action_export": "Exportovat",
        "input_hint": "Napište svou otázku...",
        "quick_title": "Rychlé akce",
        "quick_create_budget": "Vytvořit rozpočet",
        "quick_analyze_expenses": "Analyzovat výdaje",
        "quick_invest_advice": "Investiční doporučení",
        "quick_tax_guide": "Daňový průvodce",
        "quick_calculators": "Kalkulačky",
        "markets_title": "Přehled trhů",
        "markets_show_detail": "Zobrazit detail",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / CZK",
        "analyses_title": "Nedávné analýzy",
        "analyses_show_all": "Zobrazit vše",
        "analysis_1": "Měsíční rozpočet - květen 2024",
        "analysis_1_time": "Dnes 10:15",
        "analysis_2": "Investiční analýza portfolia",
        "analysis_2_time": "Včera",
        "analysis_3": "Srovnání spořicích účtů",
        "analysis_3_time": "2 dny zpět",
        "analysis_4": "Daňové přiznání - průvodce",
        "analysis_4_time": "3 dny zpět",
        "tip_title": "Tip dne",
        "tip_text": "Pravidelným investováním i menších částek využijete sílu složeného úročení.",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
