"""EN + CS copy for the AI Finance section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Finance assistant for budgeting, investing and planning.",
        "tab_chat": "Chat",
        "tab_budget": "Budget",
        "tab_invest": "Investments",
        "tab_analysis": "Analysis",
        "tab_taxes": "Taxes",
        "tab_insurance": "Insurance",
        "tab_calculators": "Calculators",
        "tab_templates": "Templates",
        "budget_mock_title": "Build a budget",
        "budget_mock_desc": "Plug in income and goals - we'll suggest a 50/30/20 split.",
        "budget_field_income": "Monthly income (net)",
        "budget_field_income_hint": "$2,000",
        "budget_field_savings": "Savings goal",
        "budget_field_savings_hint": "How much do you want to save?",
        "budget_field_essentials": "Top essentials",
        "budget_field_essentials_hint": "Rent, utilities, groceries...",
        "budget_field_lifestyle": "Lifestyle priorities",
        "budget_field_lifestyle_hint": "Travel, hobbies, fitness...",
        "budget_example_1": "Donut chart with category split.",
        "budget_example_2": "Auto-detect categories from past spend.",
        "budget_example_3": "Compare to recommended ranges.",
        "invest_title": "Investment ideas",
        "invest_desc": "Personalised ideas for your risk profile and horizon.",
        "invest_field_amount": "Amount to invest",
        "invest_field_amount_hint": "$5,000",
        "invest_field_horizon": "Horizon",
        "invest_field_horizon_hint": "1 year, 5 years, 20+ years",
        "invest_field_risk": "Risk appetite",
        "invest_field_risk_hint": "Low / medium / high",
        "invest_field_focus": "Focus",
        "invest_field_focus_hint": "ETFs, individual stocks, crypto, mix",
        "invest_example_1": "3 portfolio templates with allocations.",
        "invest_example_2": "Estimated yield with compounding.",
        "invest_example_3": "Risk warning + rebalancing notes.",
        "analysis_title": "Spend analysis",
        "analysis_desc": "Upload statements and get a breakdown by category and merchant.",
        "analysis_field_period": "Period",
        "analysis_field_period_hint": "Last 30 days, this quarter, YTD",
        "analysis_field_focus": "Focus",
        "analysis_field_focus_hint": "Subscriptions, eating out, transport...",
        "analysis_field_goal": "What do you want to know?",
        "analysis_field_goal_hint": "Where can I cut $200?",
        "analysis_example_1": "Sankey diagram of cash flow.",
        "analysis_example_2": "Outliers vs your monthly baseline.",
        "analysis_example_3": "Auto-flagged duplicate subscriptions.",
        "taxes_title": "Tax helper",
        "taxes_desc": "Walk through your situation and get a checklist.",
        "taxes_field_country": "Country",
        "taxes_field_country_hint": "Czech Republic, Slovakia, Germany...",
        "taxes_field_status": "Filing status",
        "taxes_field_status_hint": "Employee, self-employed, both",
        "taxes_field_year": "Tax year",
        "taxes_field_year_hint": "e.g. 2024",
        "taxes_field_notes": "Anything special?",
        "taxes_field_notes_hint": "Crypto, foreign income, mortgage...",
        "taxes_example_1": "Step-by-step deduction checklist.",
        "taxes_example_2": "Estimated refund preview.",
        "taxes_example_3": "Reminders for upcoming deadlines.",
        "insurance_title": "Insurance review",
        "insurance_desc": "See what you're missing or overpaying for.",
        "insurance_field_household": "Household size",
        "insurance_field_household_hint": "1, 2, family of 4...",
        "insurance_field_assets": "Main assets",
        "insurance_field_assets_hint": "Apartment, car, equipment...",
        "insurance_field_existing": "Existing policies",
        "insurance_field_existing_hint": "Liability, life, auto, travel...",
        "insurance_field_concerns": "Top concerns",
        "insurance_field_concerns_hint": "Medical, accidents, theft...",
        "insurance_example_1": "Coverage gap heatmap.",
        "insurance_example_2": "Premium benchmarks vs market.",
        "insurance_example_3": "Suggested policy bundles.",
        "calc_title": "Calculators",
        "calc_desc": "Quick-use calculators for the most common decisions.",
        "calc_compound_title": "Compound interest",
        "calc_compound_desc": "Project savings over time at any rate.",
        "calc_mortgage_title": "Mortgage payment",
        "calc_mortgage_desc": "Monthly payment for any rate and term.",
        "calc_loan_title": "Loan affordability",
        "calc_loan_desc": "How much can you safely borrow?",
        "calc_retirement_title": "Retirement planner",
        "calc_retirement_desc": "Goal income vs current pace.",
        "calc_currency_title": "Currency converter",
        "calc_currency_desc": "Live FX with historical chart.",
        "calc_savings_title": "Savings goal",
        "calc_savings_desc": "Plan deposits to hit a target by a date.",
        "fin_tpl_title": "Templates",
        "fin_tpl_desc": "Spreadsheets and trackers ready to download.",
        "fin_tpl_use": "Open template",
        "fin_tpl_budget_title": "50/30/20 budget tracker",
        "fin_tpl_budget_desc": "Monthly tracker with category split.",
        "fin_tpl_invest_title": "Portfolio overview",
        "fin_tpl_invest_desc": "Holdings, allocation and YTD return.",
        "fin_tpl_debt_title": "Debt payoff plan",
        "fin_tpl_debt_desc": "Snowball vs avalanche side by side.",
        "fin_tpl_emergency_title": "Emergency fund plan",
        "fin_tpl_emergency_desc": "Calculate target + timeline to get there.",
        "msg2_intro": "Here is your latest budget plan - want me to refine anything?",
        "chat_greeting": (
            "Hi! Ask me anything about money, or open a tab on the left to "
            "build a budget, plan savings, sketch an investment scenario, "
            "review insurance or prep your tax checklist. I will only "
            "answer based on the inputs you give me."
        ),
        "budget_title": "Recommended 50/30/20 budget",
        "budget_subtitle": "A proven rule for healthy finances.",
        "donut_caption_top": "$2,000",
        "donut_caption_bottom": "/ month",
        "needs_label": "50% Needs",
        "needs_value": "$1,000",
        "needs_note": "Housing, food, transport, utilities...",
        "wants_label": "30% Wants",
        "wants_value": "$600",
        "wants_note": "Entertainment, travel, hobbies...",
        "saving_label": "20% Saving & Investing",
        "saving_value": "$400",
        "saving_note": "Emergency fund, investments, future...",
        "breakdown_title": "Detailed breakdown",
        "col_category": "Category",
        "col_recommended": "Recommended",
        "col_amount": "Your amount",
        "col_note": "Note",
        "row_housing": "Housing",
        "row_housing_note": "Rent, utilities, internet",
        "row_food": "Food",
        "row_food_note": "Groceries, dining out",
        "row_transport": "Transport",
        "row_transport_note": "Fuel, public transit, insurance",
        "row_other_needs": "Other essentials",
        "row_other_needs_note": "Healthcare, clothing, services",
        "row_wants": "Wants",
        "row_wants_note": "Entertainment, hobbies, travel",
        "row_saving": "Saving & Investing",
        "row_saving_note": "Emergency, investments, future",
        "action_edit_budget": "Edit budget",
        "action_create_chart": "Create chart",
        "action_save_plan": "Saving plan",
        "action_invest_plan": "Investment plan",
        "action_export": "Export",
        "input_hint": "Type your question...",
        "quick_title": "Quick actions",
        "quick_create_budget": "Create a budget",
        "quick_analyze_expenses": "Analyse expenses",
        "quick_invest_advice": "Investment recommendations",
        "quick_tax_guide": "Tax guide",
        "quick_calculators": "Calculators",
        "markets_title": "Markets",
        "markets_edit": "Edit",
        "markets_refresh": "Refresh",
        "markets_refresh_tooltip": "Re-fetch live quotes now",
        "markets_edit_title": "Edit your tickers",
        "markets_edit_hint": (
            "Add Yahoo Finance symbols (e.g. ^GSPC, BTC-USD, EURCZK=X). "
            "Empty list hides the card; values come straight from Yahoo "
            "and are not financial advice."
        ),
        "markets_edit_add": "Add",
        "markets_edit_add_hint": "Yahoo symbol (e.g. AAPL, EURUSD=X)",
        "markets_edit_save": "Save",
        "markets_edit_cancel": "Cancel",
        "markets_edit_empty": "No tickers yet - add the first symbol below.",
        "markets_empty_no_tickers": "Add your first ticker via the Edit button above.",
        "markets_empty_no_data": "No live data yet - check your connection or try the Edit button.",
        "markets_empty_response": (
            "Yahoo Finance returned no quotes. Check your connection, "
            "proxy, or whether the symbols still exist, then tap Refresh."
        ),
        "markets_error_generic": "Could not fetch live quotes: {error}",
        "markets_loading": "Fetching live quotes...",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / USD",
        "analyses_title": "Recent analyses",
        "analyses_empty": "No saved analyses yet - run a tab and Save complete analyses.",
        "tip_title": "Tip",
        "tip_empty": "A tip will appear here once you finish your first analysis - it always references your real numbers.",
        "tip_thinking": "Generating a personalised tip...",
        "tip_next_step_label": "Try this:",
        "tip_regenerate_btn": "New tip",
        "tip_regenerate_tooltip": "Generate a new tip from your latest numbers",
        "currency_symbol": "$",
        "currency_code": "USD",
        "menu_new_run": "Reset analyses",
        "menu_save_full": "Save analyses",
        "menu_open_folder": "Open output folder",
        "menu_show_history": "Open history",
        "menu_how_to": "How to use this",
        "menu_open_folder_no_run": "No saved analyses yet - run something first.",
        "menu_save_no_run": "Build at least one analysis before saving.",
        "menu_save_done_template": "Analyses saved to {path}",
        "menu_demo_load": "Show demo data",
        "menu_demo_clear": "Hide demo data",
        "demo_pill": "DEMO",
        "savings_card_title": "Savings plan",
        "savings_card_subtitle": "Milestones built from your goal and timeline",
        "savings_card_monthly": "Monthly contribution",
        "savings_card_months": "Months to goal",
        "savings_card_percent": "% of income",
        "savings_milestones_title": "Milestones",
        "savings_tips_title": "Tips",
        "savings_empty": "Set a goal amount and timeline below; the savings plan and milestones appear after generation.",
        "edit_budget_title": "Refine the budget",
        "edit_budget_hint": "Describe what to change (e.g. 'less Wants, more Saving' or 'add 1 500 Kč hobby budget').",
        "edit_budget_btn": "Apply edits",
        "edit_budget_running": "Refining the budget...",
        "templates_title": "Saved analyses",
        "templates_desc": "Every run you saved lands in outputs/ai_finance/. Open a folder to grab the PDFs and Markdown.",
        "templates_open_folder": "Open folder",
        "templates_empty_title": "No saved analyses yet",
        "templates_empty_body": "Run a Budget / Investment / Tax / Insurance analysis and click 'Save analyses' in the section menu - the run lands here.",
        "templates_create_btn": "Build your first budget",
        "disclaimer_short": "Educational only - not licensed financial advice.",
        "disclaimer_long": (
            "AI Finance is here to help you think about money - it is not "
            "licensed financial, tax, insurance, or legal advice. Verify "
            "anything important with a qualified professional in your "
            "country."
        ),
        "web_search_on": "Web: ON",
        "web_search_off": "Web: OFF",
        "web_search_hint": "Web search is opt-in (Settings - extra cost).",
        "activity_ready": "Ready",
        "activity_thinking": "Thinking...",
        "activity_analyzing": "Analysing...",
        "activity_generating": "Generating...",
        "activity_exporting": "Exporting...",
        "activity_error": "Error",
        "form_run": "Run",
        "form_clear": "Reset form",
        "form_apply_edit": "Apply edit",
        "form_currency": "Currency",
        "budget_method_label": "Budget method",
        "budget_method_50_30_20": "50/30/20 (classic)",
        "budget_method_60_20_20": "60/20/20",
        "budget_method_70_20_10": "70/20/10",
        "budget_method_zero_based": "Zero-based",
        "budget_method_custom": "Custom",
        "budget_run_button": "Build budget",
        "budget_edit_title": "Edit the plan",
        "budget_edit_hint": "Type what should change (e.g. 'My rent is 18 000 Kč', 'I need 12 000 Kč for groceries').",
        "budget_warnings_title": "Heads up",
        "budget_suggestions_title": "Next steps",
        "budget_summary_title": "Plan summary",
        "savings_title": "Savings plan",
        "savings_desc": "Pick a goal and we'll work out the monthly contribution.",
        "savings_field_current": "Current savings",
        "savings_field_current_hint": "How much have you saved already?",
        "savings_field_goal_amount": "Goal amount",
        "savings_field_goal_amount_hint": "How much do you want to save?",
        "savings_field_goal_label": "Goal label",
        "savings_field_goal_label_hint": "What is the money for?",
        "savings_field_months": "Target timeframe (months)",
        "savings_field_months_hint": "How long do you want to take?",
        "savings_run_button": "Build savings plan",
        "savings_card_monthly": "Monthly contribution",
        "savings_card_months": "Months to goal",
        "savings_card_percent": "% of income",
        "savings_milestones_title": "Milestones",
        "savings_tips_title": "Tips",
        "invest_run_button": "Generate scenarios",
        "invest_scenario_return": "Annual return (est.)",
        "invest_scenario_projected": "Projected value",
        "invest_scenario_allocation": "Allocation",
        "invest_projection_label": "Projection (compound monthly)",
        "invest_risk_label_conservative": "Conservative",
        "invest_risk_label_moderate": "Moderate",
        "invest_risk_label_growth": "Growth",
        "invest_diversification_title": "Diversification",
        "insurance_severity_high": "High",
        "insurance_severity_medium": "Medium",
        "insurance_severity_low": "Low",
        "insurance_heatmap_title": "Coverage gap heatmap",
        "taxes_timeline_title": "Deadlines this year",
        "invest_risk_title": "Risk note",
        "analysis_field_currency": "Currency",
        "analysis_field_currency_hint": "USD, EUR, CZK...",
        "analysis_upload_title": "Statement / receipts",
        "analysis_upload_hint": "Drop a CSV / PDF statement (optional). All parsing is local.",
        "analysis_run_button": "Analyse",
        "analysis_totals_income": "Income",
        "analysis_totals_expenses": "Expenses",
        "analysis_totals_net": "Net cash flow",
        "analysis_categories_title": "Spend by category",
        "analysis_top_outflows_title": "Top outflows",
        "analysis_recurring_title": "Recurring payments",
        "analysis_suggestions_title": "Ways to save",
        "taxes_run_button": "Build checklist",
        "taxes_checklist_title": "Checklist",
        "taxes_deadlines_title": "Deadlines",
        "taxes_documents_title": "Documents to gather",
        "taxes_tips_title": "Optimisations",
        "insurance_upload_title": "Policy document",
        "insurance_upload_hint": "Drop a policy PDF / DOCX (optional). Parsed locally.",
        "insurance_run_button": "Review insurance",
        "insurance_policies_title": "Policies on file",
        "insurance_gaps_title": "Coverage gaps",
        "insurance_duplicates_title": "Possible duplicates",
        "insurance_watch_outs_title": "Read carefully",
        "insurance_suggestions_title": "Next steps",
        "calc_section_compound": "Compound interest",
        "calc_section_mortgage": "Mortgage payment",
        "calc_section_loan": "Loan affordability",
        "calc_section_retirement": "Retirement planner",
        "calc_section_savings": "Savings goal",
        "calc_section_currency": "Currency converter",
        "calc_field_principal": "Starting amount",
        "calc_field_monthly_contribution": "Monthly contribution",
        "calc_field_rate": "Annual rate (%)",
        "calc_field_years": "Years",
        "calc_field_price": "Property price",
        "calc_field_down_payment": "Down payment",
        "calc_field_term_years": "Term (years)",
        "calc_field_income": "Monthly net income",
        "calc_field_debt": "Existing monthly debt",
        "calc_field_dti": "Max DTI (%)",
        "calc_field_current": "Current savings",
        "calc_field_target": "Target amount",
        "calc_field_target_months": "Months",
        "calc_field_fx_amount": "Amount",
        "calc_field_fx_pair": "Pair (Yahoo format)",
        "calc_field_fx_pair_hint": "USDCZK=X, EURUSD=X, BTC-USD",
        "calc_field_retirement_age": "Current age",
        "calc_field_retirement_target_age": "Retirement age",
        "calc_field_retirement_savings_now": "Savings today",
        "calc_field_retirement_monthly": "Monthly contribution",
        "calc_field_retirement_rate": "Annual rate (%)",
        "calc_result_future_value": "Future value",
        "calc_result_total_interest": "Interest earned",
        "calc_result_monthly_payment": "Monthly payment",
        "calc_result_total_cost": "Total cost",
        "calc_result_max_loan": "Max loan you can carry",
        "calc_result_max_payment": "Max payment",
        "calc_result_monthly_needed": "Monthly needed",
        "calc_result_total_contributions": "Total contributions",
        "calc_result_converted": "Converted",
        "calc_run": "Calculate",
        "calc_compound_help": "Project savings over time at any rate. Assumes monthly compounding.",
        "calc_mortgage_help": "Standard amortising mortgage payment. Property tax / insurance not included.",
        "calc_loan_help": "Maximum monthly payment under your debt-to-income limit, and the principal it can carry at the stated rate.",
        "calc_retirement_help": "Future value of your existing savings plus monthly contributions until retirement age.",
        "calc_savings_help": "Required monthly deposit to reach a target by a specific month count.",
        "calc_currency_help": "Live FX via Yahoo Finance. Disable in Settings to keep AI Finance offline.",
        "calc_market_disabled": "Live market data is disabled in Settings.",
        "calc_market_unavailable": "Could not fetch live FX. Check your connection or try again later.",
        "drop_zone_hint": "Drop a file or click to choose",
        "drop_zone_attached": "Attached:",
        "drop_zone_clear": "Remove",
        "input_attach_label": "Attach a statement, invoice or contract",
        "chat_placeholder": "Type a message...",
        "chat_running_label": "Thinking...",
        "chat_canned_budget": "Help me build a 50/30/20 budget for my income.",
        "chat_canned_savings": "I want to save for an emergency fund - how should I structure it?",
        "chat_canned_invest": "Give me a high-level investment scenario for a moderate risk profile.",
        "chat_canned_taxes": "What should I prepare for my next tax return?",
        "chat_canned_calc": "Open the calculators tab.",
        "error_no_key": "Save an API key in Settings before running real AI calls.",
        "error_no_input": "Please fill in the required fields first.",
        "error_provider": "The AI provider returned an error: {error}",
        "section_disclaimer_pill": "Not financial advice",
    },
    "cs": {
        "nav_label": "AI Finance",
        "title": "AI Finance",
        "subtitle": "Asistent pro rozpočet, investice a plánování.",
        "tab_chat": "Chat",
        "tab_budget": "Rozpočet",
        "tab_invest": "Investice",
        "tab_analysis": "Analýza",
        "tab_taxes": "Daně",
        "tab_insurance": "Pojištění",
        "tab_calculators": "Kalkulačky",
        "tab_templates": "Šablony",
        "budget_mock_title": "Sestavit rozpočet",
        "budget_mock_desc": "Zadej příjmy a cíle - navrhneme rozdělení 50/30/20.",
        "budget_field_income": "Měsíční příjem (čistý)",
        "budget_field_income_hint": "45 000 Kč",
        "budget_field_savings": "Cíl spoření",
        "budget_field_savings_hint": "Kolik chceš měsíčně odkládat?",
        "budget_field_essentials": "Hlavní výdaje",
        "budget_field_essentials_hint": "Nájem, energie, jídlo...",
        "budget_field_lifestyle": "Co si chceš dopřát",
        "budget_field_lifestyle_hint": "Cestování, koníčky, fitness...",
        "budget_example_1": "Donut graf s rozdělením kategorií.",
        "budget_example_2": "Auto-detekce kategorií z minulých výdajů.",
        "budget_example_3": "Porovnání s doporučenými hodnotami.",
        "invest_title": "Investiční nápady",
        "invest_desc": "Personalizované nápady podle rizikovosti a horizontu.",
        "invest_field_amount": "Částka k investici",
        "invest_field_amount_hint": "120 000 Kč",
        "invest_field_horizon": "Horizont",
        "invest_field_horizon_hint": "1 rok, 5 let, 20+ let",
        "invest_field_risk": "Tolerance rizika",
        "invest_field_risk_hint": "Nízká / střední / vysoká",
        "invest_field_focus": "Zaměření",
        "invest_field_focus_hint": "ETF, jednotlivé akcie, krypto, mix",
        "invest_example_1": "3 šablony portfolií s alokací.",
        "invest_example_2": "Odhad výnosu se složeným úročením.",
        "invest_example_3": "Upozornění na rizika + rebalanc.",
        "analysis_title": "Analýza výdajů",
        "analysis_desc": "Nahraj výpisy a získej rozbor podle kategorií a obchodníků.",
        "analysis_field_period": "Období",
        "analysis_field_period_hint": "Posledních 30 dní, kvartál, YTD",
        "analysis_field_focus": "Zaměření",
        "analysis_field_focus_hint": "Předplatné, restaurace, doprava...",
        "analysis_field_goal": "Co chceš zjistit?",
        "analysis_field_goal_hint": "Kde můžu uspořit 5 000 Kč?",
        "analysis_example_1": "Sankey diagram cash flow.",
        "analysis_example_2": "Odlehlé hodnoty oproti průměru.",
        "analysis_example_3": "Auto-detekce duplicitních předplatných.",
        "taxes_title": "Daňový pomocník",
        "taxes_desc": "Projdi svou situaci a získej checklist.",
        "taxes_field_country": "Země",
        "taxes_field_country_hint": "Česko, Slovensko, Německo...",
        "taxes_field_status": "Status",
        "taxes_field_status_hint": "Zaměstnanec, OSVČ, oboje",
        "taxes_field_year": "Daňový rok",
        "taxes_field_year_hint": "např. 2024",
        "taxes_field_notes": "Něco specifického?",
        "taxes_field_notes_hint": "Krypto, příjem ze zahraničí, hypotéka...",
        "taxes_example_1": "Krok-za-krokem checklist odpočtů.",
        "taxes_example_2": "Náhled odhadovaného přeplatku.",
        "taxes_example_3": "Připomenutí blížících se termínů.",
        "insurance_title": "Pojištění",
        "insurance_desc": "Zjisti, kde ti chybí pojistka nebo platíš zbytečně.",
        "insurance_field_household": "Velikost domácnosti",
        "insurance_field_household_hint": "1, 2, rodina 4 osoby...",
        "insurance_field_assets": "Hlavní majetek",
        "insurance_field_assets_hint": "Byt, auto, vybavení...",
        "insurance_field_existing": "Stávající smlouvy",
        "insurance_field_existing_hint": "Odpovědnost, životní, auto, cesťák...",
        "insurance_field_concerns": "Hlavní obavy",
        "insurance_field_concerns_hint": "Zdraví, úrazy, krádež...",
        "insurance_example_1": "Heatmapa mezer v krytí.",
        "insurance_example_2": "Porovnání pojistného s trhem.",
        "insurance_example_3": "Doporučené balíčky pojistek.",
        "calc_title": "Kalkulačky",
        "calc_desc": "Rychlé kalkulačky pro nejčastější rozhodnutí.",
        "calc_compound_title": "Složené úročení",
        "calc_compound_desc": "Spočti zhodnocení v čase při libovolné sazbě.",
        "calc_mortgage_title": "Splátka hypotéky",
        "calc_mortgage_desc": "Měsíční splátka pro libovolnou sazbu a délku.",
        "calc_loan_title": "Bonita půjčky",
        "calc_loan_desc": "Kolik si můžeš bezpečně půjčit?",
        "calc_retirement_title": "Důchodový plán",
        "calc_retirement_desc": "Cílový důchod vs. aktuální tempo.",
        "calc_currency_title": "Převodník měn",
        "calc_currency_desc": "Aktuální FX + historický graf.",
        "calc_savings_title": "Cíl spoření",
        "calc_savings_desc": "Naplánuj vklady tak, aby ses k cíli dostal v čas.",
        "fin_tpl_title": "Šablony",
        "fin_tpl_desc": "Tabulky a trackery ke stažení.",
        "fin_tpl_use": "Otevřít šablonu",
        "fin_tpl_budget_title": "Tracker rozpočtu 50/30/20",
        "fin_tpl_budget_desc": "Měsíční tracker s rozdělením kategorií.",
        "fin_tpl_invest_title": "Přehled portfolia",
        "fin_tpl_invest_desc": "Pozice, alokace a YTD výnos.",
        "fin_tpl_debt_title": "Plán splacení dluhů",
        "fin_tpl_debt_desc": "Snowball vs. avalanche vedle sebe.",
        "fin_tpl_emergency_title": "Plán rezervy",
        "fin_tpl_emergency_desc": "Spočti cíl + čas, za který tam dojdeš.",
        "msg2_intro": "Tady je tvůj poslední rozpočet - mám něco upravit?",
        "chat_greeting": (
            "Ahoj! Zeptej se na cokoli kolem peněz, nebo si v záložkách "
            "vlevo sestav rozpočet, naplánuj spoření, načrtni investiční "
            "scénář, projdi pojištění nebo si připrav daňový checklist. "
            "Odpovídám jen na základě toho, co mi pošleš."
        ),
        "budget_title": "Doporučený rozpočet 50/30/20",
        "budget_subtitle": "Osvědčené pravidlo pro zdravé finance.",
        "donut_caption_top": "45 000 Kč",
        "donut_caption_bottom": "měsíčně",
        "needs_label": "50% Potřeby",
        "needs_value": "22 500 Kč",
        "needs_note": "Bydlení, jídlo, doprava, energie...",
        "wants_label": "30% Přání",
        "wants_value": "13 500 Kč",
        "wants_note": "Zábava, cestování, koníčky...",
        "saving_label": "20% Spoření & Investice",
        "saving_value": "9 000 Kč",
        "saving_note": "Rezerva, investice, budoucnost...",
        "breakdown_title": "Detailní rozpis",
        "col_category": "Kategorie",
        "col_recommended": "Doporučeno",
        "col_amount": "Vaše částka",
        "col_note": "Poznámka",
        "row_housing": "Bydlení",
        "row_housing_note": "Nájem, energie, internet",
        "row_food": "Jídlo",
        "row_food_note": "Potraviny, stravování",
        "row_transport": "Doprava",
        "row_transport_note": "Palivo, MHD, pojištění",
        "row_other_needs": "Ostatní potřeby",
        "row_other_needs_note": "Zdraví, oblečení, služby",
        "row_wants": "Přání",
        "row_wants_note": "Zábava, koníčky, cestování",
        "row_saving": "Spoření & Investice",
        "row_saving_note": "Rezerva, investice, budoucnost",
        "action_edit_budget": "Upravit rozpočet",
        "action_create_chart": "Vytvořit graf",
        "action_save_plan": "Návrh spoření",
        "action_invest_plan": "Investiční plán",
        "action_export": "Exportovat",
        "input_hint": "Napište svou otázku...",
        "quick_title": "Rychlé akce",
        "quick_create_budget": "Vytvořit rozpočet",
        "quick_analyze_expenses": "Analyzovat výdaje",
        "quick_invest_advice": "Investiční doporučení",
        "quick_tax_guide": "Daňový průvodce",
        "quick_calculators": "Kalkulačky",
        "markets_title": "Přehled trhů",
        "markets_edit": "Upravit",
        "markets_refresh": "Obnovit",
        "markets_refresh_tooltip": "Stáhnout aktuální kurzy hned",
        "markets_edit_title": "Uprav si tickery",
        "markets_edit_hint": (
            "Přidej Yahoo Finance symboly (např. ^GSPC, BTC-USD, EURCZK=X). "
            "Prázdný seznam kartu schová; hodnoty chodí přímo z Yahoo a "
            "nejsou finančním poradenstvím."
        ),
        "markets_edit_add": "Přidat",
        "markets_edit_add_hint": "Yahoo symbol (např. AAPL, EURCZK=X)",
        "markets_edit_save": "Uložit",
        "markets_edit_cancel": "Zrušit",
        "markets_edit_empty": "Žádné tickery - přidej první symbol dole.",
        "markets_empty_no_tickers": "Přidej si první ticker tlačítkem Upravit nahoře.",
        "markets_empty_no_data": "Live data zatím nedorazila - zkontroluj připojení nebo zkus Upravit.",
        "markets_empty_response": (
            "Yahoo Finance nevrátil žádné kurzy. Zkontroluj připojení, "
            "proxy nebo platnost symbolů a klepni na Obnovit."
        ),
        "markets_error_generic": "Nepodařilo se stáhnout kurzy: {error}",
        "markets_loading": "Načítám aktuální kurzy...",
        "ticker_sp500": "S&P 500",
        "ticker_nasdaq": "NASDAQ",
        "ticker_dow": "DOW JONES",
        "ticker_btc": "BTC / USD",
        "ticker_eur": "EUR / CZK",
        "analyses_title": "Nedávné analýzy",
        "analyses_empty": "Zatím žádné uložené analýzy - spusť záložku a klikni na Uložit analýzy.",
        "tip_title": "Tip",
        "tip_empty": "Tip se objeví, až dokončíš první analýzu - vždycky vychází z tvých skutečných čísel.",
        "tip_thinking": "Generuji personalizovaný tip...",
        "tip_next_step_label": "Vyzkoušej:",
        "tip_regenerate_btn": "Nový tip",
        "tip_regenerate_tooltip": "Vytvoř nový tip z aktuálních čísel",
        "currency_symbol": "Kč",
        "currency_code": "CZK",
        "menu_new_run": "Resetovat analýzy",
        "menu_save_full": "Uložit analýzy",
        "menu_open_folder": "Otevřít složku výstupů",
        "menu_show_history": "Otevřít historii",
        "menu_how_to": "Jak používat",
        "menu_open_folder_no_run": "Zatím žádné uložené analýzy - nejdřív něco spusť.",
        "menu_save_no_run": "Před uložením nech AI alespoň jednu analýzu sestavit.",
        "menu_save_done_template": "Analýzy uloženy do {path}",
        "menu_demo_load": "Zobrazit demo data",
        "menu_demo_clear": "Skrýt demo data",
        "demo_pill": "DEMO",
        "savings_card_title": "Plán spoření",
        "savings_card_subtitle": "Milníky podle tvého cíle a doby",
        "savings_card_monthly": "Měsíční odkládání",
        "savings_card_months": "Měsíců do cíle",
        "savings_card_percent": "% z příjmu",
        "savings_milestones_title": "Milníky",
        "savings_tips_title": "Tipy",
        "savings_empty": "Zadej cílovou částku a dobu níže - plán spoření a milníky se objeví po vygenerování.",
        "edit_budget_title": "Upravit rozpočet",
        "edit_budget_hint": "Popiš co změnit (např. 'míň zábavy, víc spoření' nebo 'přidat 1 500 Kč na koníčky').",
        "edit_budget_btn": "Aplikovat úpravy",
        "edit_budget_running": "Upravuji rozpočet...",
        "templates_title": "Uložené analýzy",
        "templates_desc": "Každý uložený běh skončí v outputs/ai_finance/. Otevři složku a najdeš PDF i Markdown.",
        "templates_open_folder": "Otevřít složku",
        "templates_empty_title": "Zatím žádné uložené analýzy",
        "templates_empty_body": "Spusť analýzu (Rozpočet / Investice / Daně / Pojištění) a klikni v menu sekce na 'Uložit analýzy' - běh se zobrazí tady.",
        "templates_create_btn": "Sestav svůj první rozpočet",
        "disclaimer_short": "Pouze vzdělávací obsah - nejedná se o licencované finanční poradenství.",
        "disclaimer_long": (
            "AI Finance pomáhá přemýšlet o penězích - není to však licencované "
            "finanční, daňové, pojišťovací ani právní poradenství. Důležité "
            "kroky si vždy ověř u kvalifikovaného odborníka v tvé zemi."
        ),
        "web_search_on": "Web: ZAP",
        "web_search_off": "Web: VYP",
        "web_search_hint": "Vyhledávání na webu je opt-in (Nastavení - extra náklady).",
        "activity_ready": "Připraveno",
        "activity_thinking": "Přemýšlím...",
        "activity_analyzing": "Analyzuji...",
        "activity_generating": "Generuji...",
        "activity_exporting": "Exportuji...",
        "activity_error": "Chyba",
        "form_run": "Spustit",
        "form_clear": "Vyčistit",
        "form_apply_edit": "Aplikovat úpravu",
        "form_currency": "Měna",
        "budget_method_label": "Metoda rozpočtu",
        "budget_method_50_30_20": "50/30/20 (klasika)",
        "budget_method_60_20_20": "60/20/20",
        "budget_method_70_20_10": "70/20/10",
        "budget_method_zero_based": "Zero-based",
        "budget_method_custom": "Vlastní",
        "budget_run_button": "Sestavit rozpočet",
        "budget_edit_title": "Upravit plán",
        "budget_edit_hint": "Napiš, co se má změnit (např. 'Nájem mám 18 000 Kč', 'Na jídlo potřebuju 12 000 Kč').",
        "budget_warnings_title": "Pozor na",
        "budget_suggestions_title": "Co dál",
        "budget_summary_title": "Shrnutí plánu",
        "savings_title": "Plán spoření",
        "savings_desc": "Zvol cíl a my dopočítáme měsíční vklad.",
        "savings_field_current": "Aktuální úspory",
        "savings_field_current_hint": "Kolik už máš naspořeno?",
        "savings_field_goal_amount": "Cílová částka",
        "savings_field_goal_amount_hint": "Kolik chceš naspořit?",
        "savings_field_goal_label": "Označení cíle",
        "savings_field_goal_label_hint": "Na co peníze jsou?",
        "savings_field_months": "Cílový čas (měsíců)",
        "savings_field_months_hint": "Za jak dlouho to chceš stihnout?",
        "savings_run_button": "Vytvořit plán spoření",
        "savings_card_monthly": "Měsíční vklad",
        "savings_card_months": "Měsíců do cíle",
        "savings_card_percent": "% z příjmu",
        "savings_milestones_title": "Milníky",
        "savings_tips_title": "Tipy",
        "invest_run_button": "Vygenerovat scénáře",
        "invest_scenario_return": "Roční výnos (odhad)",
        "invest_scenario_projected": "Projektovaná hodnota",
        "invest_scenario_allocation": "Alokace",
        "invest_projection_label": "Projekce (měsíční úročení)",
        "insurance_severity_high": "Vysoká",
        "insurance_severity_medium": "Střední",
        "insurance_severity_low": "Nízká",
        "insurance_heatmap_title": "Heatmapa mezer v pokrytí",
        "taxes_timeline_title": "Termíny v tomto roce",
        "invest_risk_label_conservative": "Konzervativní",
        "invest_risk_label_moderate": "Vyvážený",
        "invest_risk_label_growth": "Růstový",
        "invest_diversification_title": "Diverzifikace",
        "invest_risk_title": "Riziko",
        "analysis_field_currency": "Měna",
        "analysis_field_currency_hint": "Kč, EUR, USD...",
        "analysis_upload_title": "Bankovní výpis / účtenky",
        "analysis_upload_hint": "Přetáhni CSV/PDF výpis (volitelné). Parsování proběhne lokálně.",
        "analysis_run_button": "Analyzovat",
        "analysis_totals_income": "Příjem",
        "analysis_totals_expenses": "Výdaje",
        "analysis_totals_net": "Cashflow",
        "analysis_categories_title": "Výdaje podle kategorií",
        "analysis_top_outflows_title": "Největší výdaje",
        "analysis_recurring_title": "Opakované platby",
        "analysis_suggestions_title": "Kde ušetřit",
        "taxes_run_button": "Sestavit checklist",
        "taxes_checklist_title": "Checklist",
        "taxes_deadlines_title": "Termíny",
        "taxes_documents_title": "Dokumenty k přípravě",
        "taxes_tips_title": "Optimalizace",
        "insurance_upload_title": "Pojistná smlouva",
        "insurance_upload_hint": "Přetáhni PDF/DOCX smlouvy (volitelné). Parsuje se lokálně.",
        "insurance_run_button": "Projít pojištění",
        "insurance_policies_title": "Aktuální pojistky",
        "insurance_gaps_title": "Mezery v krytí",
        "insurance_duplicates_title": "Možné duplicity",
        "insurance_watch_outs_title": "Pozor přečíst",
        "insurance_suggestions_title": "Další kroky",
        "calc_section_compound": "Složené úročení",
        "calc_section_mortgage": "Splátka hypotéky",
        "calc_section_loan": "Bonita půjčky",
        "calc_section_retirement": "Důchodový plán",
        "calc_section_savings": "Cíl spoření",
        "calc_section_currency": "Převodník měn",
        "calc_field_principal": "Počáteční částka",
        "calc_field_monthly_contribution": "Měsíční vklad",
        "calc_field_rate": "Roční úrok (%)",
        "calc_field_years": "Roky",
        "calc_field_price": "Cena nemovitosti",
        "calc_field_down_payment": "Vlastní vklad",
        "calc_field_term_years": "Doba splácení (roky)",
        "calc_field_income": "Měsíční čistý příjem",
        "calc_field_debt": "Stávající měsíční splátky",
        "calc_field_dti": "Max DTI (%)",
        "calc_field_current": "Aktuální úspory",
        "calc_field_target": "Cílová částka",
        "calc_field_target_months": "Měsíců",
        "calc_field_fx_amount": "Částka",
        "calc_field_fx_pair": "Pár (Yahoo formát)",
        "calc_field_fx_pair_hint": "USDCZK=X, EURCZK=X, BTC-USD",
        "calc_field_retirement_age": "Aktuální věk",
        "calc_field_retirement_target_age": "Důchodový věk",
        "calc_field_retirement_savings_now": "Úspory dnes",
        "calc_field_retirement_monthly": "Měsíční vklad",
        "calc_field_retirement_rate": "Roční úrok (%)",
        "calc_result_future_value": "Budoucí hodnota",
        "calc_result_total_interest": "Vydělaný úrok",
        "calc_result_monthly_payment": "Měsíční splátka",
        "calc_result_total_cost": "Celkové náklady",
        "calc_result_max_loan": "Max úvěr",
        "calc_result_max_payment": "Max splátka",
        "calc_result_monthly_needed": "Měsíční vklad",
        "calc_result_total_contributions": "Celkem vloženo",
        "calc_result_converted": "Převedeno",
        "calc_run": "Spočítat",
        "calc_compound_help": "Spočti zhodnocení v čase. Předpokládá měsíční úročení.",
        "calc_mortgage_help": "Standardní splátka hypotéky. Daň z nemovitosti a pojištění nejsou zahrnuty.",
        "calc_loan_help": "Maximální splátka při zadaném DTI a hlavní jistina, kterou unesete.",
        "calc_retirement_help": "Budoucí hodnota stávajících úspor plus měsíčních vkladů do důchodového věku.",
        "calc_savings_help": "Měsíční vklad potřebný k dosažení cíle v dané době.",
        "calc_currency_help": "Aktuální FX kurz z Yahoo Finance. V Nastavení můžeš live data úplně vypnout.",
        "calc_market_disabled": "Živá tržní data jsou vypnutá v Nastavení.",
        "calc_market_unavailable": "FX se nepodařilo načíst. Zkontroluj připojení a zkus to znovu.",
        "drop_zone_hint": "Přetáhni soubor nebo klikni pro výběr",
        "drop_zone_attached": "Připojeno:",
        "drop_zone_clear": "Odstranit",
        "input_attach_label": "Připojit výpis, fakturu nebo smlouvu",
        "chat_placeholder": "Napiš zprávu...",
        "chat_running_label": "Přemýšlím...",
        "chat_canned_budget": "Pomoz mi sestavit rozpočet 50/30/20 z mého příjmu.",
        "chat_canned_savings": "Chci spořit na rezervu - jak ji nastavit?",
        "chat_canned_invest": "Ukaž mi obecný investiční scénář pro vyvážený rizikový profil.",
        "chat_canned_taxes": "Co bych měl(a) připravit na další daňové přiznání?",
        "chat_canned_calc": "Otevři záložku Kalkulačky.",
        "error_no_key": "Než spustíš reálné AI volání, ulož si API klíč v Nastavení.",
        "error_no_input": "Nejdřív vyplň požadovaná pole.",
        "error_provider": "AI poskytovatel vrátil chybu: {error}",
        "section_disclaimer_pill": "Není to finanční poradenství",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
