"""EN + CS copy for the AI Study section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Study",
        "title": "AI Study",
        "subtitle": "Your smart study buddy. Learns with you, explains, summarises and helps you succeed.",
        "tab_chat": "Chat",
        "tab_summary": "Summarise topic",
        "tab_explain": "Explain",
        "tab_tasks": "Tasks & plan",
        "tab_quizzes": "Quizzes",
        "tab_sources": "Sources",
        "summary_title": "Summarise topic",
        "summary_desc": "Drop in a long topic and get a clean recap with key points.",
        "summary_field_topic_hint": "Quantum entanglement, French Revolution...",
        "summary_field_input": "Source text",
        "summary_field_input_hint": "Paste an article, your notes or a chapter.",
        "summary_field_format": "Format",
        "summary_field_format_hint": "Bullets, paragraph, mind map...",
        "summary_example_1": "TL;DR + key points + study questions.",
        "summary_example_2": "Highlight terminology with definitions.",
        "summary_example_3": "Side-by-side language version.",
        "explain_title": "Explain a term",
        "explain_desc": "Get a plain-language explanation tuned to your level.",
        "explain_field_term": "Term",
        "explain_field_term_hint": "What do you want explained?",
        "explain_field_level": "Your level",
        "explain_field_level_hint": "Beginner, intermediate, expert",
        "explain_field_context": "Context (optional)",
        "explain_field_context_hint": "Where did you encounter it?",
        "explain_example_1": "Three explanations: 5-year-old, student, expert.",
        "explain_example_2": "Real-world analogy + diagram suggestion.",
        "explain_example_3": "Common misconceptions called out.",
        "tasks_panel_title": "Tasks & plan",
        "tasks_panel_desc": "Sketch a study plan and break a topic into tasks with due dates.",
        "tasks_field_subject": "Subject",
        "tasks_field_subject_hint": "Physics, history, programming...",
        "tasks_field_deadline": "Deadline",
        "tasks_field_deadline_hint": "Exam date, project due...",
        "tasks_field_hours": "Hours per week",
        "tasks_field_hours_hint": "How much time can you give it?",
        "tasks_field_focus": "Focus areas",
        "tasks_field_focus_hint": "Where do you feel weakest?",
        "tasks_example_1": "Weekly plan with checkpoints.",
        "tasks_example_2": "Spaced repetition reminders.",
        "tasks_example_3": "Pomodoro-friendly task chunks.",
        "quizzes_panel_title": "Quizzes",
        "quizzes_panel_desc": "Pick a ready-made quiz or generate your own from notes.",
        "quiz_use": "Start quiz",
        "quiz_physics_title": "Quantum basics",
        "quiz_physics_desc": "10 questions, mix of MCQ and short answer.",
        "quiz_math_title": "Calculus warm-up",
        "quiz_math_desc": "8 derivatives + 4 word problems.",
        "quiz_code_title": "Python fundamentals",
        "quiz_code_desc": "12 questions on data types and control flow.",
        "quiz_econ_title": "Micro vs Macro",
        "quiz_econ_desc": "10 quick questions to calibrate.",
        "sources_panel_title": "Sources",
        "sources_panel_desc": "Curated reading and watching for the topic you're studying.",
        "sources_field_topic": "Topic",
        "sources_field_topic_hint": "What are you researching?",
        "sources_field_type": "Source types",
        "sources_field_type_hint": "Articles, videos, books, papers",
        "sources_field_lang": "Language",
        "sources_field_lang_hint": "EN, CS, both",
        "sources_example_1": "Mix of free + paywalled sources.",
        "sources_example_2": "Citations ready to copy.",
        "sources_example_3": "Quality score and reading time.",
        "msg1_user": "Explain quantum entanglement to me, simply.",
        "msg2_intro": "Sure! Quantum entanglement is when two particles stay connected in such a way that changing the state of one instantly affects the state of the other - even if they are an enormous distance apart.",
        "section_simple_title": "In simple terms",
        "section_simple_text": "Imagine two coins. You flip one and instantly know what the other shows, even though you never saw it. With quantum particles it works similarly, only much more strangely.",
        "section_keypoints_title": "Key points",
        "key_bullet1": "Particles are entangled at creation.",
        "key_bullet2": "Changing the state of one particle instantly affects the other.",
        "key_bullet3": "Information does not travel faster than light (it does not break relativity).",
        "key_bullet4": "It is one of the most surprising phenomena of quantum mechanics.",
        "section_example_title": "Example",
        "section_example_text": "You have two entangled particles. You measure the spin of the first and find it is \"up\". You instantly know the second one must be \"down\", no matter where it is in the universe.",
        "action_simpler": "Simplify further",
        "action_real": "Real-world example",
        "action_diagram": "Create a diagram",
        "action_more": "More questions",
        "sources_title": "Recommended sources",
        "source_show_more": "Show more",
        "source_khan_title": "Quantum physics - Khan Academy",
        "source_khan_domain": "khanacademy.org",
        "source_youtube_title": "Quantum Entanglement Explained",
        "source_youtube_domain": "youtube.com",
        "source_wiki_title": "Quantum entanglement (article)",
        "source_wiki_domain": "en.wikipedia.org",
        "input_hint": "Type your study question...",
        "today_title": "Today's study overview",
        "today_topics_label": "Topics",
        "today_topics_value": "3",
        "today_time_label": "Studied",
        "today_time_value": "2h 15m",
        "today_progress_label": "Progress",
        "today_progress_value": "85%",
        "subjects_title": "My subjects",
        "subject_physics": "Physics",
        "subject_math": "Mathematics",
        "subject_programming": "Programming",
        "subject_economics": "Economics",
        "add_subject": "Add subject",
        "tools_title": "Quick tools",
        "tool_summarise": "Summarise text",
        "tool_explain": "Explain terms",
        "tool_quiz": "Create a quiz",
        "tool_assignment": "Assignment draft",
        "tool_mindmap": "Mind map",
        "tool_translate": "Translate text",
        "tasks_title": "Upcoming tasks",
        "task_show_all": "Show all",
        "task_math": "Mathematics - Homework",
        "task_math_due": "Tomorrow",
        "task_physics": "Physics - Project",
        "task_physics_due": "Jun 3, 2024",
        "task_programming": "Programming - Test",
        "task_programming_due": "Jun 5, 2024",
        "add_task": "Add task",
    },
    "cs": {
        "nav_label": "AI Studium",
        "title": "AI Studium",
        "subtitle": "Tvůj chytrý studijní parťák. Učí se s tebou, vysvětluje, shrnuje a pomáhá ti uspět.",
        "tab_chat": "Chat",
        "tab_summary": "Shrnutí tématu",
        "tab_explain": "Vysvětlit",
        "tab_tasks": "Úkoly & plán",
        "tab_quizzes": "Kvízy",
        "tab_sources": "Zdroje",
        "summary_title": "Shrnutí tématu",
        "summary_desc": "Vlož delší text a získej čistý souhrn s klíčovými body.",
        "summary_field_topic_hint": "Kvantová provázanost, Velká francouzská revoluce...",
        "summary_field_input": "Zdrojový text",
        "summary_field_input_hint": "Vlož článek, poznámky nebo kapitolu.",
        "summary_field_format": "Formát",
        "summary_field_format_hint": "Bullety, odstavec, myšlenková mapa...",
        "summary_example_1": "TL;DR + klíčové body + studijní otázky.",
        "summary_example_2": "Označení odborných pojmů s definicí.",
        "summary_example_3": "Verze v druhém jazyce vedle sebe.",
        "explain_title": "Vysvětlit pojem",
        "explain_desc": "Vysvětlení v lidské řeči přizpůsobené tvé úrovni.",
        "explain_field_term": "Pojem",
        "explain_field_term_hint": "Co chceš vysvětlit?",
        "explain_field_level": "Tvá úroveň",
        "explain_field_level_hint": "Začátečník, pokročilý, expert",
        "explain_field_context": "Kontext (volitelné)",
        "explain_field_context_hint": "Kde jsi na to narazil?",
        "explain_example_1": "Tři vysvětlení: jako pětiletému, studentovi, expertovi.",
        "explain_example_2": "Analogie z reálu + návrh diagramu.",
        "explain_example_3": "Upozornění na běžné mýty.",
        "tasks_panel_title": "Úkoly & plán",
        "tasks_panel_desc": "Naplánuj studium a rozsekej téma na úkoly s termíny.",
        "tasks_field_subject": "Předmět",
        "tasks_field_subject_hint": "Fyzika, dějepis, programování...",
        "tasks_field_deadline": "Termín",
        "tasks_field_deadline_hint": "Datum zkoušky, odevzdání...",
        "tasks_field_hours": "Hodin týdně",
        "tasks_field_hours_hint": "Kolik času na to máš?",
        "tasks_field_focus": "Slabá místa",
        "tasks_field_focus_hint": "Kde si nejsi jistý?",
        "tasks_example_1": "Týdenní plán s checkpointy.",
        "tasks_example_2": "Připomenutí opakování s odstupem.",
        "tasks_example_3": "Úkoly velikosti pomodoro.",
        "quizzes_panel_title": "Kvízy",
        "quizzes_panel_desc": "Vyber hotový kvíz nebo si nech vygenerovat z poznámek.",
        "quiz_use": "Spustit kvíz",
        "quiz_physics_title": "Základy kvantovky",
        "quiz_physics_desc": "10 otázek, mix ABCD a krátkých odpovědí.",
        "quiz_math_title": "Rozcvička z analýzy",
        "quiz_math_desc": "8 derivací + 4 slovní úlohy.",
        "quiz_code_title": "Základy Pythonu",
        "quiz_code_desc": "12 otázek na datové typy a řízení toku.",
        "quiz_econ_title": "Mikro vs makro",
        "quiz_econ_desc": "10 rychlých otázek pro orientaci.",
        "sources_panel_title": "Zdroje",
        "sources_panel_desc": "Vybrané čtení a videa pro téma, které studuješ.",
        "sources_field_topic": "Téma",
        "sources_field_topic_hint": "Co rešeršuješ?",
        "sources_field_type": "Typy zdrojů",
        "sources_field_type_hint": "Články, videa, knihy, papery",
        "sources_field_lang": "Jazyk",
        "sources_field_lang_hint": "CS, EN, oba",
        "sources_example_1": "Mix volných a placených zdrojů.",
        "sources_example_2": "Citace připravené ke zkopírování.",
        "sources_example_3": "Skóre kvality a doba čtení.",
        "msg1_user": "Vysvětli mi kvantovou provázanost jednoduše.",
        "msg2_intro": "Jasně! Kvantová provázanost je jev, kdy dvě částice zůstávají propojené takovým způsobem, že změna stavu jedné částice okamžitě ovlivní stav druhé, i když jsou od sebe na obrovskou vzdálenost.",
        "section_simple_title": "Jednoduše řečeno",
        "section_simple_text": "Představ si dvě mince. Otočíš jednu a okamžitě víš, jaká je druhá, i když ji nevidíš. U kvantových částic to funguje podobně, ale mnohem podivuhodněji.",
        "section_keypoints_title": "Klíčové body",
        "key_bullet1": "Částice jsou provázané při vzniku.",
        "key_bullet2": "Změna stavu jedné částice okamžitě ovlivní druhou.",
        "key_bullet3": "Informace se nepřenáší rychleji než světlo (neporušuje relativitu).",
        "key_bullet4": "Je to jeden z nejpodivnějších jevů kvantové mechaniky.",
        "section_example_title": "Příklad",
        "section_example_text": "Máš dvě provázané částice. Změříš spin první částice a zjistíš, že je „nahoru\". Okamžitě víš, že druhá musí být „dolů\", ať jsou kdekoli ve vesmíru.",
        "action_simpler": "Zjednodušit více",
        "action_real": "Dát příklad z praxe",
        "action_diagram": "Vytvořit diagram",
        "action_more": "Další otázky",
        "sources_title": "Doporučené zdroje",
        "source_show_more": "Zobrazit více",
        "source_khan_title": "Kvantová fyzika - Khan Academy",
        "source_khan_domain": "khanacademy.org",
        "source_youtube_title": "Quantum Entanglement Explained",
        "source_youtube_domain": "youtube.com",
        "source_wiki_title": "Kvantová provázanost (článek)",
        "source_wiki_domain": "cs.wikipedia.org",
        "input_hint": "Napište svou otázku ke studiu...",
        "today_title": "Dnešní studijní přehled",
        "today_topics_label": "Témata",
        "today_topics_value": "3",
        "today_time_label": "Studováno",
        "today_time_value": "2h 15m",
        "today_progress_label": "Pokrok",
        "today_progress_value": "85%",
        "subjects_title": "Moje předměty",
        "subject_physics": "Fyzika",
        "subject_math": "Matematika",
        "subject_programming": "Programování",
        "subject_economics": "Ekonomie",
        "add_subject": "Přidat předmět",
        "tools_title": "Rychlé nástroje",
        "tool_summarise": "Shrnout text",
        "tool_explain": "Vysvětlit pojmy",
        "tool_quiz": "Vytvořit kvíz",
        "tool_assignment": "Návrh úkolu",
        "tool_mindmap": "Myšlenková mapa",
        "tool_translate": "Přeložit text",
        "tasks_title": "Nadcházející úkoly",
        "task_show_all": "Zobrazit vše",
        "task_math": "Matematika - Domácí úkol",
        "task_math_due": "Zítra",
        "task_physics": "Fyzika - Projekt",
        "task_physics_due": "3. 6. 2024",
        "task_programming": "Programování - Test",
        "task_programming_due": "5. 6. 2024",
        "add_task": "Přidat úkol",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
