"""EN + CS copy for the AI Study section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Study",
        "title": "AI Study",
        "subtitle": "Your smart study buddy. Learns with you, explains, summarises and helps you succeed.",
        "tab_chat": "Chat",
        "tab_summary": "Summarise topic",
        "tab_explain": "Explain",
        "tab_tasks": "Tasks & plan",
        "tab_quizzes": "Quizzes",
        "tab_sources": "Sources",
        "msg1_user": "Explain quantum entanglement to me, simply.",
        "msg2_intro": "Sure! Quantum entanglement is when two particles stay connected in such a way that changing the state of one instantly affects the state of the other - even if they are an enormous distance apart.",
        "section_simple_title": "In simple terms",
        "section_simple_text": "Imagine two coins. You flip one and instantly know what the other shows, even though you never saw it. With quantum particles it works similarly, only much more strangely.",
        "section_keypoints_title": "Key points",
        "key_bullet1": "Particles are entangled at creation.",
        "key_bullet2": "Changing the state of one particle instantly affects the other.",
        "key_bullet3": "Information does not travel faster than light (it does not break relativity).",
        "key_bullet4": "It is one of the most surprising phenomena of quantum mechanics.",
        "section_example_title": "Example",
        "section_example_text": "You have two entangled particles. You measure the spin of the first and find it is \"up\". You instantly know the second one must be \"down\", no matter where it is in the universe.",
        "action_simpler": "Simplify further",
        "action_real": "Real-world example",
        "action_diagram": "Create a diagram",
        "action_more": "More questions",
        "sources_title": "Recommended sources",
        "source_show_more": "Show more",
        "source_khan_title": "Quantum physics - Khan Academy",
        "source_khan_domain": "khanacademy.org",
        "source_youtube_title": "Quantum Entanglement Explained",
        "source_youtube_domain": "youtube.com",
        "source_wiki_title": "Quantum entanglement (article)",
        "source_wiki_domain": "en.wikipedia.org",
        "input_hint": "Type your study question...",
        "today_title": "Today's study overview",
        "today_topics_label": "Topics",
        "today_topics_value": "3",
        "today_time_label": "Studied",
        "today_time_value": "2h 15m",
        "today_progress_label": "Progress",
        "today_progress_value": "85%",
        "subjects_title": "My subjects",
        "subject_physics": "Physics",
        "subject_math": "Mathematics",
        "subject_programming": "Programming",
        "subject_economics": "Economics",
        "add_subject": "Add subject",
        "tools_title": "Quick tools",
        "tool_summarise": "Summarise text",
        "tool_explain": "Explain terms",
        "tool_quiz": "Create a quiz",
        "tool_assignment": "Assignment draft",
        "tool_mindmap": "Mind map",
        "tool_translate": "Translate text",
        "tasks_title": "Upcoming tasks",
        "task_show_all": "Show all",
        "task_math": "Mathematics - Homework",
        "task_math_due": "Tomorrow",
        "task_physics": "Physics - Project",
        "task_physics_due": "Jun 3, 2024",
        "task_programming": "Programming - Test",
        "task_programming_due": "Jun 5, 2024",
        "add_task": "Add task",
    },
    "cs": {
        "nav_label": "AI Studium",
        "title": "AI Studium",
        "subtitle": "Tvůj chytrý studijní parťák. Učí se s tebou, vysvětluje, shrnuje a pomáhá ti uspět.",
        "tab_chat": "Chat",
        "tab_summary": "Shrnutí tématu",
        "tab_explain": "Vysvětlit",
        "tab_tasks": "Úkoly & plán",
        "tab_quizzes": "Kvízy",
        "tab_sources": "Zdroje",
        "msg1_user": "Vysvětli mi kvantovou provázanost jednoduše.",
        "msg2_intro": "Jasně! Kvantová provázanost je jev, kdy dvě částice zůstávají propojené takovým způsobem, že změna stavu jedné částice okamžitě ovlivní stav druhé, i když jsou od sebe na obrovskou vzdálenost.",
        "section_simple_title": "Jednoduše řečeno",
        "section_simple_text": "Představ si dvě mince. Otočíš jednu a okamžitě víš, jaká je druhá, i když ji nevidíš. U kvantových částic to funguje podobně, ale mnohem podivuhodněji.",
        "section_keypoints_title": "Klíčové body",
        "key_bullet1": "Částice jsou provázané při vzniku.",
        "key_bullet2": "Změna stavu jedné částice okamžitě ovlivní druhou.",
        "key_bullet3": "Informace se nepřenáší rychleji než světlo (neporušuje relativitu).",
        "key_bullet4": "Je to jeden z nejpodivnějších jevů kvantové mechaniky.",
        "section_example_title": "Příklad",
        "section_example_text": "Máš dvě provázané částice. Změříš spin první částice a zjistíš, že je „nahoru\". Okamžitě víš, že druhá musí být „dolů\", ať jsou kdekoli ve vesmíru.",
        "action_simpler": "Zjednodušit více",
        "action_real": "Dát příklad z praxe",
        "action_diagram": "Vytvořit diagram",
        "action_more": "Další otázky",
        "sources_title": "Doporučené zdroje",
        "source_show_more": "Zobrazit více",
        "source_khan_title": "Kvantová fyzika - Khan Academy",
        "source_khan_domain": "khanacademy.org",
        "source_youtube_title": "Quantum Entanglement Explained",
        "source_youtube_domain": "youtube.com",
        "source_wiki_title": "Kvantová provázanost (článek)",
        "source_wiki_domain": "cs.wikipedia.org",
        "input_hint": "Napište svou otázku ke studiu...",
        "today_title": "Dnešní studijní přehled",
        "today_topics_label": "Témata",
        "today_topics_value": "3",
        "today_time_label": "Studováno",
        "today_time_value": "2h 15m",
        "today_progress_label": "Pokrok",
        "today_progress_value": "85%",
        "subjects_title": "Moje předměty",
        "subject_physics": "Fyzika",
        "subject_math": "Matematika",
        "subject_programming": "Programování",
        "subject_economics": "Ekonomie",
        "add_subject": "Přidat předmět",
        "tools_title": "Rychlé nástroje",
        "tool_summarise": "Shrnout text",
        "tool_explain": "Vysvětlit pojmy",
        "tool_quiz": "Vytvořit kvíz",
        "tool_assignment": "Návrh úkolu",
        "tool_mindmap": "Myšlenková mapa",
        "tool_translate": "Přeložit text",
        "tasks_title": "Nadcházející úkoly",
        "task_show_all": "Zobrazit vše",
        "task_math": "Matematika - Domácí úkol",
        "task_math_due": "Zítra",
        "task_physics": "Fyzika - Projekt",
        "task_physics_due": "3. 6. 2024",
        "task_programming": "Programování - Test",
        "task_programming_due": "5. 6. 2024",
        "add_task": "Přidat úkol",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
