"""EN + CS copy for the My Profile section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "My Profile",
        "title": "My Profile",
        "subtitle": "Upload your CV once - AI CV, Job Search and LinkedIn all reuse it.",
        # Intro / status
        "intro_title": "One profile, shared everywhere",
        "intro_desc": "Add your CV (and optionally a LinkedIn export, GitHub and notes) once. The other AI tools read this profile instead of asking you to upload again.",
        "used_by": "Used by: AI CV · AI Job Search · AI LinkedIn",
        "saved_at": "Saved {when}",
        "demo_label": "Demo mode (no API calls)",
        "clear_btn": "Clear profile",
        # Inputs
        "inputs_title": "Source materials",
        "inputs_desc": "Your CV is required. LinkedIn export, GitHub and notes are optional but improve the result.",
        "resume_title": "Drop your CV / resume",
        "resume_hint": "PDF, DOCX, TXT, MD or HTML",
        "linkedin_title": "LinkedIn export (optional)",
        "linkedin_hint": "PDF or text export of your LinkedIn profile",
        "github_label": "GitHub profile (optional)",
        "github_hint": "https://github.com/your-username",
        "github_skip": "Skip GitHub",
        "notes_label": "Notes (optional)",
        "notes_hint": "Anything the documents won't capture: goals, target roles, preferences...",
        "clear_file_tooltip": "Remove file",
        # Build
        "build_btn": "Build my profile",
        "rebuild_btn": "Re-extract profile",
        "building_btn": "Building...",
        "err_resume_missing": "Add your CV first - it's the one required input.",
        "err_no_json": "The AI did not return a valid profile. Try again.",
        "err_generic": "Could not build the profile. See Settings -> Debug logs.",
        # Result
        "result_title": "Your parsed profile",
        "empty_title": "No profile yet",
        "empty_desc": "Add your CV above and click \"Build my profile\". Or flip on Demo mode to preview with sample data.",
        "section_contact": "Contact",
        "section_summary": "Summary",
        "section_skills": "Skills",
        "section_experience": "Experience",
        "section_education": "Education",
        "section_certifications": "Certifications",
        "section_languages": "Languages",
        "section_projects": "Projects",
        "section_links": "Links",
        "none": "Not provided",
        # Context panel
        "ctx_status_title": "Profile status",
        "ctx_status_ready": "Profile ready",
        "ctx_status_none": "No profile saved yet",
        "ctx_status_demo": "Demo profile (not saved)",
        "ctx_activity_title": "Activity",
        "ctx_activity_ready": "Ready",
        "ctx_activity_scraping": "Fetching GitHub...",
        "ctx_activity_analyzing": "Extracting profile...",
        "ctx_activity_error": "Something went wrong",
        "ctx_actions_title": "Open in",
        "ctx_open_career": "AI CV",
        "ctx_open_jobs": "AI Job Search",
        "ctx_open_linkedin": "AI LinkedIn",
    },
    "cs": {
        "nav_label": "Můj profil",
        "title": "Můj profil",
        "subtitle": "Nahraj svůj životopis jednou - AI Životopis, Hledání práce i LinkedIn ho znovu použijí.",
        # Intro / status
        "intro_title": "Jeden profil, všude sdílený",
        "intro_desc": "Přidej svůj životopis (a volitelně export z LinkedInu, GitHub a poznámky) jednou. Ostatní AI nástroje čtou tento profil, místo aby tě nutily nahrávat znovu.",
        "used_by": "Používá: AI Životopis · AI Hledání práce · AI LinkedIn",
        "saved_at": "Uloženo {when}",
        "demo_label": "Demo režim (bez API volání)",
        "clear_btn": "Vymazat profil",
        # Inputs
        "inputs_title": "Zdrojové materiály",
        "inputs_desc": "Životopis je povinný. Export z LinkedInu, GitHub a poznámky jsou volitelné, ale vylepší výsledek.",
        "resume_title": "Nahraj svůj životopis",
        "resume_hint": "PDF, DOCX, TXT, MD nebo HTML",
        "linkedin_title": "Export z LinkedInu (volitelné)",
        "linkedin_hint": "PDF nebo textový export tvého LinkedIn profilu",
        "github_label": "GitHub profil (volitelné)",
        "github_hint": "https://github.com/tvoje-jmeno",
        "github_skip": "Přeskočit GitHub",
        "notes_label": "Poznámky (volitelné)",
        "notes_hint": "Cokoliv, co dokumenty nezachytí: cíle, vysněné pozice, preference...",
        "clear_file_tooltip": "Odebrat soubor",
        # Build
        "build_btn": "Sestavit profil",
        "rebuild_btn": "Znovu extrahovat profil",
        "building_btn": "Sestavuji...",
        "err_resume_missing": "Nejdřív přidej životopis - je to jediný povinný vstup.",
        "err_no_json": "AI nevrátila platný profil. Zkus to znovu.",
        "err_generic": "Profil se nepodařilo sestavit. Viz Nastavení -> Záznamy ladění.",
        # Result
        "result_title": "Tvůj zpracovaný profil",
        "empty_title": "Zatím žádný profil",
        "empty_desc": "Přidej výše životopis a klikni na „Sestavit profil“. Nebo zapni Demo režim a prohlédni si ukázková data.",
        "section_contact": "Kontakt",
        "section_summary": "Shrnutí",
        "section_skills": "Dovednosti",
        "section_experience": "Praxe",
        "section_education": "Vzdělání",
        "section_certifications": "Certifikace",
        "section_languages": "Jazyky",
        "section_projects": "Projekty",
        "section_links": "Odkazy",
        "none": "Neuvedeno",
        # Context panel
        "ctx_status_title": "Stav profilu",
        "ctx_status_ready": "Profil připraven",
        "ctx_status_none": "Zatím žádný uložený profil",
        "ctx_status_demo": "Demo profil (neuložený)",
        "ctx_activity_title": "Aktivita",
        "ctx_activity_ready": "Připraveno",
        "ctx_activity_scraping": "Načítám GitHub...",
        "ctx_activity_analyzing": "Extrahuji profil...",
        "ctx_activity_error": "Něco se pokazilo",
        "ctx_actions_title": "Otevřít v",
        "ctx_open_career": "AI Životopis",
        "ctx_open_jobs": "AI Hledání práce",
        "ctx_open_linkedin": "AI LinkedIn",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
