"""EN + CS copy for the AI Legal section."""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_label": "AI Legal assistant",
        "title": "AI Legal assistant",
        "subtitle": "Plain-language explanations of legal documents and simple suggestions.",
        "warning_pill_title": "Important notice",
        "warning_pill_text": "This is not legal advice and does not replace a lawyer.",

        "tab_chat": "Chat",
        "tab_analysis": "Document analysis",
        "tab_drafts": "Document drafts",
        "tab_templates": "Templates",

        "chat_action_summarize": "Summarise",
        "chat_action_risks": "Find risks",
        "chat_action_explain": "Explain terms",
        "chat_action_changes": "Suggest changes",
        "chat_empty_prompt": "Type your request for the attached document.",
        "chat_input_placeholder": "Type a message…",
        "chat_user_attachment_label": "Attached file:",
        "chat_attached_announcement": "I've read **{name}**. Ask anything, or pick one of the quick actions below.",
        "chat_no_document_warning": "Please attach a document first — drop a PDF / DOCX / HTML / TXT into the right panel.",
        "chat_demo_reply_template": "**Demo answer** — turn off Demo mode in Settings to call the real AI provider.\n\nIn production I would answer your question about **{name}** here based on the extracted text ({chars} characters).",
        "chat_error_prefix": "Couldn't get an answer:",

        "analysis_view_document": "Document",
        "analysis_view_chat": "Chat",
        "analysis_doc_title": "Document analysis summary",
        "analysis_doc_subtitle": "Side-by-side comparison of strengths and risks.",
        "analysis_correct_title": "What's in order",
        "analysis_wrong_title": "Risks and issues",
        "analysis_recommendations_title": "Recommended changes",
        "analysis_right_1": "Subject of work is clearly defined",
        "analysis_right_2": "Total price is fixed and includes VAT clause",
        "analysis_right_3": "Payment schedule is split into 3 milestones",
        "analysis_right_4": "Defect liability period is specified (24 months)",
        "analysis_risk_1": "No clear penalty for delayed delivery from contractor",
        "analysis_risk_2": "Confidentiality clause is too broad and lacks expiry",
        "analysis_risk_3": "Termination conditions favor the contractor",
        "analysis_recommendation_1": "Add a delay penalty of 0.05 % of price per day",
        "analysis_recommendation_2": "Limit confidentiality to 3 years after termination",
        "analysis_md_intro": "Below is the same analysis in a single readable summary.",
        "analysis_chat_intro": "I read the document and split my findings into three groups.",
        "analysis_chat_action_export": "Export as PDF",
        "analysis_chat_action_email": "Send to lawyer",

        "drafts_user_message": "Simplify the language and shorten it to one page.",
        "drafts_user_time": "11:08",
        "drafts_assistant_time": "11:08",
        "drafts_assistant_intro": "I prepared a simplified version of the work contract. You can preview it below.",
        "drafts_preview_title": "Rewritten document preview",
        "drafts_preview_paragraph_1": "The contractor will carry out the agreed work for the client.",
        "drafts_preview_paragraph_2": "The price is 120,000 CZK without VAT, paid in three instalments.",
        "drafts_preview_paragraph_3": "Defects must be reported within 24 months of delivery.",
        "drafts_preview_paragraph_4": "Either party may terminate the contract with 14 days' notice.",
        "drafts_preview_open": "Open full document",
        "drafts_assistant_diff_intro": "Changes I made:",
        "drafts_diff_1": "Replaced legal jargon with plain language",
        "drafts_diff_2": "Removed three duplicate clauses",
        "drafts_diff_3": "Shortened payment schedule into bullet points",
        "drafts_action_consumer": "Consumer-friendly version",
        "drafts_action_shorter": "Make it shorter",
        "drafts_action_gdpr": "Add GDPR clause",
        "drafts_action_revert": "Revert to original",
        "drafts_mock_response": "Mock response — no API yet. The text would be rewritten here.",
        "drafts_mock_user_label": "Your instruction",

        "templates_section_styles": "Templates",
        "templates_section_color": "Accent colour",
        "templates_section_font": "Font",
        "templates_section_default_title": "Default — match the input format",
        "templates_section_default_desc": "Return the document in the same format as the PDF you uploaded.",
        "template_modern_label": "Modern",
        "template_modern_desc": "Clean design with bold headings",
        "template_classic_label": "Classic",
        "template_classic_desc": "Traditional serif with numbering",
        "template_minimal_label": "Minimalist",
        "template_minimal_desc": "No decorations, just text",
        "template_legal_label": "Legal",
        "template_legal_desc": "Formal contract appearance",
        "template_corporate_label": "Corporate",
        "template_corporate_desc": "Structured sections with sidebar",
        "template_academic_label": "Academic",
        "template_academic_desc": "For scholarly documents",
        "font_sans_label": "Sans serif",
        "font_serif_label": "Serif",
        "font_mono_label": "Monospace",
        "font_display_label": "Display",
        "font_sample": "Aa Bb Cc 123",
        "preview_title": "Live preview",
        "preview_doc_heading": "Work contract",
        "preview_doc_subheading": "Article I — Subject of the contract",
        "preview_doc_paragraph_1": "The contractor undertakes to perform the work agreed by the parties under the conditions set out in this contract.",
        "preview_doc_paragraph_2": "The client undertakes to pay the agreed price for the duly delivered work.",
        "preview_doc_paragraph_3": "The work shall be carried out at the contractor's expense and risk and shall be delivered no later than the agreed deadline.",
        "preview_doc_footer": "Page 1 of 4",
        "btn_apply_template": "Apply template",
        "btn_download_sample": "Download sample",

        "drop_zone_title": "Drop a document here",
        "drop_zone_hint": "PDF, DOCX, HTML or TXT — or click to choose a file",
        "drop_zone_only_pdf": "Supported formats: PDF, DOCX, HTML, TXT.",
        "drop_zone_unsupported": "Supported formats: PDF, DOCX, HTML, TXT.",

        "ctx_attached_title": "Attached documents",
        "ctx_upload_btn": "Upload document",
        "ctx_no_doc": "No document uploaded yet.",
        "ctx_analysis_title": "Document analysis",
        "ctx_stat_summary": "Summary",
        "ctx_stat_summary_desc": "Document summarised into 12 points",
        "ctx_stat_risks": "Risks",
        "ctx_stat_risks_desc": "3 potential risks found",
        "ctx_stat_clauses": "Important clauses",
        "ctx_stat_clauses_desc": "7 key provisions",
        "ctx_stat_recommendations": "Recommendations",
        "ctx_stat_recommendations_desc": "2 suggested changes",
        "ctx_show_detail_btn": "Show detailed analysis",
        "ctx_quick_actions": "Quick actions",
        "ctx_qa_explain": "Explain this document",
        "ctx_qa_check_risks": "Check risks",
        "ctx_qa_suggest_changes": "Suggest contract changes",
        "ctx_qa_compare": "Compare with another document",
    },
    "cs": {
        "nav_label": "AI Právní asistent",
        "title": "AI Právní asistent",
        "subtitle": "Srozumitelně vysvětlí právní dokumenty a navrhnu jednoduchá řešení.",
        "warning_pill_title": "Důležité upozornění",
        "warning_pill_text": "Toto není právní poradenství a nenahrazuje služby advokáta.",

        "tab_chat": "Chat",
        "tab_analysis": "Analýza dokumentu",
        "tab_drafts": "Návrhy dokumentů",
        "tab_templates": "Šablony",

        "chat_action_summarize": "Shrnout",
        "chat_action_risks": "Najít rizika",
        "chat_action_explain": "Vysvětlit pojmy",
        "chat_action_changes": "Navrhnout úpravy",
        "chat_empty_prompt": "Napište svůj požadavek pro vložený dokument.",
        "chat_input_placeholder": "Napište zprávu…",
        "chat_user_attachment_label": "Přiložený soubor:",
        "chat_attached_announcement": "Přečetl jsem **{name}**. Ptej se na cokoliv nebo zvol jednu z rychlých akcí dole.",
        "chat_no_document_warning": "Nejdřív prosím přiložte dokument — přetáhněte PDF / DOCX / HTML / TXT do pravého panelu.",
        "chat_demo_reply_template": "**Ukázková odpověď** — vypněte Demo režim v Nastavení pro skutečné volání AI.\n\nV produkci bych zde odpověděl na vaši otázku ohledně **{name}** podle extrahovaného textu ({chars} znaků).",
        "chat_error_prefix": "Nepodařilo se získat odpověď:",

        "analysis_view_document": "Dokument",
        "analysis_view_chat": "Chat",
        "analysis_doc_title": "Souhrnná analýza dokumentu",
        "analysis_doc_subtitle": "Přehledné srovnání toho, co je v pořádku a co dělá problém.",
        "analysis_correct_title": "Co je v pořádku",
        "analysis_wrong_title": "Rizika a problémy",
        "analysis_recommendations_title": "Doporučení k úpravám",
        "analysis_right_1": "Předmět díla je jasně vymezen",
        "analysis_right_2": "Celková cena je pevná a obsahuje doložku o DPH",
        "analysis_right_3": "Platební kalendář je rozdělen na 3 milníky",
        "analysis_right_4": "Doba pro reklamace vad je specifikována (24 měsíců)",
        "analysis_risk_1": "Chybí jasná pokuta za prodlení zhotovitele",
        "analysis_risk_2": "Doložka o mlčenlivosti je příliš široká a bez ukončení",
        "analysis_risk_3": "Podmínky odstoupení zvýhodňují zhotovitele",
        "analysis_recommendation_1": "Doplnit pokutu z prodlení 0,05 % z ceny denně",
        "analysis_recommendation_2": "Omezit mlčenlivost na 3 roky po skončení smlouvy",
        "analysis_md_intro": "Níže najdete totéž v přehledném souvislém shrnutí.",
        "analysis_chat_intro": "Prošel jsem dokument a roztřídil zjištění do tří skupin.",
        "analysis_chat_action_export": "Exportovat jako PDF",
        "analysis_chat_action_email": "Odeslat advokátovi",

        "drafts_user_message": "Zjednoduš jazyk a zkrať na 1 stránku.",
        "drafts_user_time": "11:08",
        "drafts_assistant_time": "11:08",
        "drafts_assistant_intro": "Připravil jsem zjednodušenou verzi smlouvy o dílo. Můžete si ji prohlédnout níže.",
        "drafts_preview_title": "Náhled přepsaného dokumentu",
        "drafts_preview_paragraph_1": "Zhotovitel provede pro objednatele dohodnutou práci.",
        "drafts_preview_paragraph_2": "Cena je 120 000 Kč bez DPH a platí se ve třech splátkách.",
        "drafts_preview_paragraph_3": "Vady je nutné nahlásit do 24 měsíců od předání díla.",
        "drafts_preview_paragraph_4": "Kterákoliv strana může smlouvu vypovědět s 14denní výpovědní lhůtou.",
        "drafts_preview_open": "Otevřít celý dokument",
        "drafts_assistant_diff_intro": "Provedl jsem následující úpravy:",
        "drafts_diff_1": "Nahradil jsem právní hantýrku běžnou řečí",
        "drafts_diff_2": "Odstranil jsem tři duplicitní ustanovení",
        "drafts_diff_3": "Zkrátil jsem platební kalendář do odrážek",
        "drafts_action_consumer": "Verze pro spotřebitele",
        "drafts_action_shorter": "Zkrátit",
        "drafts_action_gdpr": "Přidat klauzuli o GDPR",
        "drafts_action_revert": "Vrátit původní",
        "drafts_mock_response": "Ukázková odpověď — bez API. Tady by se text přepsal podle vašeho pokynu.",
        "drafts_mock_user_label": "Váš pokyn",

        "templates_section_styles": "Šablony",
        "templates_section_color": "Barevný akcent",
        "templates_section_font": "Font",
        "templates_section_default_title": "Default — stejný formát jako vstup",
        "templates_section_default_desc": "Vrátit dokument ve stejném formátu jako PDF, který jste poslali.",
        "template_modern_label": "Moderní",
        "template_modern_desc": "Čistý design s tučnými nadpisy",
        "template_classic_label": "Klasický",
        "template_classic_desc": "Tradiční serif s číslováním",
        "template_minimal_label": "Minimalistický",
        "template_minimal_desc": "Bez ozdob, jen text",
        "template_legal_label": "Právní",
        "template_legal_desc": "Formální vzhled smluv",
        "template_corporate_label": "Korporátní",
        "template_corporate_desc": "Strukturované sekce s postranním pruhem",
        "template_academic_label": "Akademický",
        "template_academic_desc": "Pro odborné práce",
        "font_sans_label": "Sans serif",
        "font_serif_label": "Serif",
        "font_mono_label": "Monospace",
        "font_display_label": "Display",
        "font_sample": "Aa Bb Cc 123",
        "preview_title": "Živý náhled",
        "preview_doc_heading": "Smlouva o dílo",
        "preview_doc_subheading": "Článek I — Předmět smlouvy",
        "preview_doc_paragraph_1": "Zhotovitel se zavazuje provést pro objednatele dílo dle podmínek této smlouvy.",
        "preview_doc_paragraph_2": "Objednatel se zavazuje uhradit za řádně předané dílo dohodnutou cenu.",
        "preview_doc_paragraph_3": "Dílo bude provedeno na náklady a riziko zhotovitele a předáno nejpozději v dohodnutém termínu.",
        "preview_doc_footer": "Strana 1 ze 4",
        "btn_apply_template": "Použít šablonu",
        "btn_download_sample": "Stáhnout vzor",

        "drop_zone_title": "Přetáhněte dokument sem",
        "drop_zone_hint": "PDF, DOCX, HTML nebo TXT — nebo klikněte pro výběr souboru",
        "drop_zone_only_pdf": "Podporujeme PDF, DOCX, HTML a TXT.",
        "drop_zone_unsupported": "Podporujeme PDF, DOCX, HTML a TXT.",

        "ctx_attached_title": "Připojené dokumenty",
        "ctx_upload_btn": "Nahrát dokument",
        "ctx_no_doc": "Zatím žádný dokument.",
        "ctx_analysis_title": "Analýza dokumentu",
        "ctx_stat_summary": "Shrnutí",
        "ctx_stat_summary_desc": "Dokument shrnut do 12 bodů",
        "ctx_stat_risks": "Rizika",
        "ctx_stat_risks_desc": "Nalezeno 3 potenciálních rizika",
        "ctx_stat_clauses": "Důležité klauzule",
        "ctx_stat_clauses_desc": "7 klíčových ustanovení",
        "ctx_stat_recommendations": "Doporučení",
        "ctx_stat_recommendations_desc": "2 doporučení k úpravám",
        "ctx_show_detail_btn": "Zobrazit detailní analýzu",
        "ctx_quick_actions": "Rychlé akce",
        "ctx_qa_explain": "Vysvětlit tento dokument",
        "ctx_qa_check_risks": "Zkontrolovat rizika",
        "ctx_qa_suggest_changes": "Navrhnout úpravy smlouvy",
        "ctx_qa_compare": "Porovnat s jiným dokumentem",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
