"""EN + CS copy for the AI Jobs section.

Keep keys grouped roughly by where they appear in the UI:

* sidebar / header
* tab labels
* setup form (steps, hints, button labels, validation messages)
* location presets + work modes
* activity / status badges
* results tab (cards, save dialog, empty states)
* history tab
* how-to dialog
* shared menu / quick-action labels (mirrors the convention used by
  the ai_career and ai_finance sections)
"""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # sidebar / header ------------------------------------------------
        "nav_label": "AI Job Search",
        "title": "AI Job Search",
        "subtitle": "Describe the role (or upload your CV), pick a location, and let AI scour the web for active openings.",

        # tab labels ------------------------------------------------------
        "tab_setup": "Setup",
        "tab_results": "Results",
        "tab_skill_gap": "Skill gap",
        "tab_history": "History",

        # setup hero ------------------------------------------------------
        "setup_hero_title": "Find positions worth applying to",
        "setup_hero_desc": "Tell AI what you are looking for. The more context you give (CV, short bio, target keywords), the closer the matches. Active postings only - dead links are dropped before you see them.",

        # step 1 - keywords ----------------------------------------------
        "step_1_label": "STEP 1",
        "step_1_title": "What role are you after?",
        "step_1_desc": "Type the job title or keywords. AI auto-expands them with synonyms (e.g. 'QA Engineer' also matches 'Tester' and 'Quality Engineer').",
        "keywords_hint": "QA software engineer, Python backend developer, data analyst...",
        "keywords_synonyms_note": "Synonyms and adjacent roles are added automatically.",

        # step 2 - profile -----------------------------------------------
        "step_2_label": "STEP 2",
        "step_2_title": "Your profile (optional)",
        "step_2_desc": "Drop your CV, paste a short bio about yourself, or share a LinkedIn URL. Any combination works - AI uses whatever you give to refine the matches.",
        "profile_text_label": "About you (free text)",
        "profile_text_hint": "I am a QA engineer with 4 years of experience in API testing, automation in Playwright, and CI in GitLab. I am looking for a senior role...",
        "profile_file_label": "Upload your CV / LinkedIn export (PDF / DOCX / TXT / HTML)",
        "profile_file_drop_title": "Drop your CV here",
        "profile_file_drop_hint": "or click to browse the disk",
        "profile_file_no_file": "No file selected",
        "profile_file_unsupported": "Unsupported file type. Use PDF, DOCX, TXT or HTML.",
        "profile_file_clear": "Clear",
        "linkedin_label": "Public LinkedIn profile URL (optional)",
        "linkedin_hint": "https://www.linkedin.com/in/your-handle",

        # step 3 - location ----------------------------------------------
        "step_3_label": "STEP 3",
        "step_3_title": "Where should AI look?",
        "step_3_desc": "Pick a region or city. Postings outside the chosen location are ignored.",
        "location_preset_label": "Location",
        "location_custom_label": "Custom location",
        "location_custom_hint": "e.g. Prague + 30 km, or Berlin / Munich",

        # step 4 - technologies + seniority ------------------------------
        "step_4_label": "STEP 4",
        "step_4_title": "Technologies and skills",
        "step_4_desc": "Tools, frameworks, certificates or soft skills you are confident in. AI uses them to score how well each posting matches your profile.",
        "tech_skills_label": "Technologies / skills",
        "tech_skills_hint": "Python, FastAPI, Playwright, GitLab CI, SQL, Docker...",
        "additional_experience_label": "Other experience",
        "additional_experience_hint": "API testing, automated tests, database work, CI/CD pipelines...",
        "seniority_label": "Experience level",
        "seniority_any": "Any",
        "seniority_junior": "Junior",
        "seniority_medior": "Medior",
        "seniority_senior": "Senior",
        "seniority_lead": "Lead",
        "skills_helper_note": "AI uses these to compute the match score and to suggest what to highlight in your CV.",

        # step 5 - exclusions --------------------------------------------
        "step_5_label": "STEP 5",
        "step_5_title": "What do you NOT want to see?",
        "step_5_desc": "Roles, technologies, companies, or conditions you want to skip. AI hides matching postings or flags them as a poor fit.",
        "excluded_keywords_label": "Excluded keywords",
        "excluded_keywords_hint": "unpaid, sales, PHP, on-site only, call centre, senior only...",
        "excluded_companies_label": "Excluded companies",
        "excluded_companies_hint": "Company A, Company B, agencies...",
        "excluded_locations_label": "Excluded locations",
        "excluded_locations_hint": "Prague, USA, no relocation...",
        "excluded_work_types_label": "Excluded work types",
        "exclude_night": "Night shifts",
        "exclude_sales": "Pure sales",
        "exclude_unpaid": "Unpaid internship",
        "exclude_onsite_only": "Only on-site",
        "exclusions_helper_note": "Excluded postings are not removed from the count - they are surfaced with a 'why hidden' reason in the saved HTML.",

        # step 6 - sources -----------------------------------------------
        "step_6_label": "STEP 6",
        "step_6_title": "Where should AI search?",
        "step_6_desc": "Pick the boards and regions. Choose multiple sources - AI merges results, removes duplicates, and verifies every link.",
        "sources_helper_note": "Leave the 'Recommended for region' chip on to use the curated defaults for the picked location.",
        "sources_custom_urls_label": "Custom URLs (one per line)",
        "sources_custom_urls_hint": "https://company.com/careers\nhttps://greenhouse.io/company\n...",
        "src_category_recommended": "Recommended",
        "src_category_global": "Global portals",
        "src_category_remote": "Remote",
        "src_category_europe": "Europe",
        "src_category_cz_sk": "Czechia / Slovakia",
        "src_category_tech": "Tech / Startup",
        "src_category_freelance": "Freelance / Contracts",
        "src_recommended_for_region": "Recommended for region",
        "src_linkedin_jobs": "LinkedIn Jobs",
        "src_indeed": "Indeed",
        "src_glassdoor": "Glassdoor",
        "src_google_jobs": "Google Jobs",
        "src_jooble": "Jooble",
        "src_talent_com": "Talent.com",
        "src_monster": "Monster",
        "src_careerbuilder": "CareerBuilder",
        "src_ziprecruiter": "ZipRecruiter",
        "src_simplyhired": "SimplyHired",
        "src_adzuna": "Adzuna",
        "src_themuse": "The Muse",
        "src_we_work_remotely": "We Work Remotely",
        "src_remote_ok": "Remote OK",
        "src_remotive": "Remotive",
        "src_flexjobs": "FlexJobs",
        "src_working_nomads": "Working Nomads",
        "src_himalayas": "Himalayas",
        "src_wttj": "Welcome to the Jungle / Otta",
        "src_remote_co": "Remote.co",
        "src_justremote": "JustRemote",
        "src_nodesk": "NoDesk",
        "src_jobspresso": "Jobspresso",
        "src_fourdayweek": "4 Day Week",
        "src_eures": "EURES",
        "src_eurojobs": "Eurojobs",
        "src_euraxess": "Euraxess",
        "src_jobsinnetwork": "Jobs in Network",
        "src_europe_language_jobs": "Europe Language Jobs",
        "src_stepstone": "StepStone",
        "src_pracuj_pl": "Pracuj.pl",
        "src_xing_jobs": "Xing Jobs",
        "src_karriere_at": "karriere.at",
        "src_reed_uk": "Reed.co.uk",
        "src_totaljobs": "TotalJobs",
        "src_jobs_cz": "Jobs.cz",
        "src_prace_cz": "Prace.cz",
        "src_startupjobs_cz": "StartupJobs",
        "src_atmoskop": "Atmoskop",
        "src_dobra_prace": "Dobra prace",
        "src_profesia_sk": "Profesia",
        "src_kariera_sk": "Kariera.sk",
        "src_pretlak": "Pretlak",
        "src_jenprace": "JenPrace.cz",
        "src_it_jobs_cz": "IT.jobs.cz",
        "src_pracomat": "Pracomat",
        "src_easyjobs_cz": "EasyJobs.cz",
        "src_wttj_cz": "Welcome to the Jungle CZ",
        "src_praca_sk": "Praca.sk",
        "src_wellfound": "Wellfound / AngelList",
        "src_hn_who_is_hiring": "HN Who is Hiring",
        "src_yc_jobs": "Y Combinator Jobs",
        "src_github_hiring": "GitHub hiring posts",
        "src_stackoverflow_companies": "Stack Overflow companies",
        "src_no_fluff_jobs": "No Fluff Jobs",
        "src_landing_jobs": "Landing.jobs",
        "src_honeypot": "Honeypot",
        "src_dice": "Dice",
        "src_builtin": "Built In",
        "src_justjoinit": "JustJoin.IT",
        "src_otta": "Otta",
        "src_techstars_jobs": "Techstars Jobs",
        "src_upwork": "Upwork",
        "src_freelancer": "Freelancer",
        "src_fiverr": "Fiverr",
        "src_toptal": "Toptal",
        "src_contra": "Contra",
        "src_malt": "Malt",
        "src_peopleperhour": "PeoplePerHour",
        "src_arc_dev": "Arc.dev",
        "src_gun_io": "Gun.io",
        "src_guru": "Guru",

        # step 7 - job age -----------------------------------------------
        "step_7_label": "STEP 7",
        "step_7_title": "How old can the posting be?",
        "step_7_desc": "Older postings may already be filled. AI tries to verify each link is still live.",
        "age_label": "Posting age",
        "age_any": "Any",
        "age_24h": "Last 24 hours",
        "age_3d": "Last 3 days",
        "age_7d": "Last 7 days",
        "age_14d": "Last 14 days",
        "age_30d": "Last 30 days",
        "verify_links_label": "Verify links are still active",
        "show_without_date_label": "Show postings without a publish date",
        "age_helper_note": "Each result is HTTP-checked when verification is enabled. Dead links are dropped before you see them.",

        # step 8 - filters (work mode + contract + count) ---------------
        "step_8_label": "STEP 8",
        "step_8_title": "Work setup, contract and result count",
        "step_8_desc": "Optional filters. Leave on defaults to keep the search broad.",
        "work_mode_label": "Work setup",
        "contract_label": "Contract type",
        "contract_hpp": "Full-time (HPP)",
        "contract_ico": "Self-employed (ICO)",
        "contract_contract": "Contract",
        "contract_dpp_dpc": "DPP / DPC (CZ)",
        "contract_internship": "Internship",
        "contract_freelance": "Freelance",
        "max_results_label": "Number of active postings to fetch",
        "max_results_hint": "This is the target number of postings you can actually apply to. AI Hub over-fetches behind the scenes, verifies every link, and trims dead ones - so 15 here means up to 15 still-open postings (plus a few closed ones shown for reference). Larger numbers cost more tokens.",

        # location presets -----------------------------------------------
        "loc_any": "Anywhere",
        "loc_remote_world": "Remote (worldwide)",
        "loc_eu": "European Union",
        "loc_usa": "United States",
        "loc_uk": "United Kingdom",
        "loc_cz": "Czech Republic",
        "loc_sk": "Slovakia",
        "loc_de": "Germany",
        "loc_at": "Austria",
        "loc_pl": "Poland",
        "loc_praha": "Prague",
        "loc_brno": "Brno",
        "loc_ostrava": "Ostrava",
        "loc_custom": "Custom (free text)...",

        # work modes -----------------------------------------------------
        "mode_any": "Any",
        "mode_remote": "Remote",
        "mode_hybrid": "Hybrid",
        "mode_onsite": "On-site",

        # step 9 - search mode -------------------------------------------
        "step_9_label": "STEP 9",
        "step_9_title": "Search mode",
        "step_9_desc": "How widely should AI cast the net?",
        "mode_exact": "Exact matches",
        "mode_exact_desc": "Stick to the exact role title and listed technologies.",
        "mode_smart": "Smart similar roles",
        "mode_smart_desc": "Add synonyms and close variants of the role.",
        "mode_broad": "Broad search",
        "mode_broad_desc": "Include adjacent roles that could fit your background.",
        "mode_discovery": "Career discovery",
        "mode_discovery_desc": "Surface different career directions that might suit your profile.",

        # step 10 - salary + output language ----------------------------
        "step_10_label": "STEP 10",
        "step_10_title": "Salary and language",
        "step_10_desc": "Minimum salary is a soft filter - AI prefers higher-paid postings but does not drop ones without a listed salary.",
        "salary_min_label": "Minimum salary (per month)",
        "salary_currency_label": "Currency",
        "currency_any": "Don't filter",
        "salary_helper_note": "Set to 0 to ignore. Postings without a listed salary are kept but flagged in the HTML report.",
        "output_lang_label": "Output language",
        "output_lang_auto": "Auto (UI language)",
        "output_lang_en": "English",
        "output_lang_cs": "Czech",

        # step 11 - summary + run ---------------------------------------
        "step_11_label": "STEP 11",
        "step_11_title": "Review and run",
        "step_11_desc": "Double-check what AI will look for. Click Search to start.",
        "summary_role_label": "Role",
        "summary_location_label": "Location",
        "summary_seniority_label": "Seniority",
        "summary_work_mode_label": "Work mode",
        "summary_contract_label": "Contract",
        "summary_salary_label": "Minimum salary",
        "summary_sources_label": "Sources",
        "summary_results_label": "Results to fetch",
        "summary_mode_label": "Search mode",
        "summary_age_label": "Posting age",
        "summary_output_lang_label": "Output language",
        "summary_value_unset": "Not set",
        "summary_value_any": "Any",
        "summary_sources_recommended": "Recommended for region",
        "summary_sources_count_template": "{count} sources",
        "summary_salary_value_template": "{amount} {currency}",
        "run_more_btn_save_template": "Save as template",
        "run_more_btn_clear": "Clear form",
        "run_more_btn_load_last": "Load last search",

        # step 12 - saved profiles --------------------------------------
        "step_12_label": "STEP 12",
        "step_12_title": "Saved search profiles",
        "step_12_desc": "Save the current setup as a template and rerun it later with one click.",
        "profiles_empty": "No saved profiles yet. Use 'Save as template' above to keep this setup for next time.",
        "profile_save_dialog_title": "Save search profile",
        "profile_save_dialog_label": "Profile name",
        "profile_save_dialog_hint": "QA Automation Remote Europe",
        "profile_save_btn": "Save profile",
        "profile_cancel_btn": "Cancel",
        "profile_last_run_template": "Last run: {when}",
        "profile_never_run": "Not run yet",
        "profile_run_again": "Run again",
        "profile_edit": "Edit",
        "profile_duplicate": "Duplicate",
        "profile_delete": "Delete",
        "profile_saved_toast_template": "Saved profile '{name}'.",
        "profile_loaded_toast_template": "Loaded profile '{name}'.",
        "profile_deleted_toast_template": "Deleted profile '{name}'.",
        "profile_duplicate_suffix": " (copy)",
        "profile_save_failed_template": "Could not save profile: {error}",
        "profile_load_last_no_search": "No previous search to load.",
        "profile_form_cleared": "Form cleared.",

        # footer ---------------------------------------------------------
        "run_btn": "Search positions",
        "run_running": "Searching the web...",
        "run_followups": "Asking clarifying questions...",
        "run_extracting": "Structuring results...",
        "run_verifying": "Verifying links...",
        "run_scoring": "Scoring matches...",
        "run_gap": "Computing skill gap...",
        "run_disabled_hint": "Add a job title (or your CV / bio) to start searching.",
        "error_no_key_template": "Your {provider} API key is not saved yet. Open Settings to add it.",
        "search_failed_template": "Search failed: {error}",
        "search_cancelled": "Search cancelled.",
        "search_done_template": "Found {count} active positions ({dropped} link(s) skipped because they were dead or redirected).",
        "search_done_no_drops_template": "Found {count} active positions.",
        "search_zero_results": "AI returned no positions for this query. Try broader keywords or a different location.",

        "footer_ask_followups_label": "Let the AI ask clarifying questions first",
        "footer_ask_followups_hint": (
            "When something is missing or contradictory, the AI pauses "
            "and asks you instead of guessing. Toggle off to skip the modal."
        ),
        "followup_title": "Quick clarifications",
        "followup_intro": (
            "Before I run the search, I want to confirm a few things "
            "instead of guessing. Pick one or more options or use Other... "
            "to type your own. Skip leaves the field blank."
        ),
        "followup_skip_btn": "Skip all",
        "followup_continue_btn": "Run the search",
        "followup_cancel": "Cancel",
        "followup_other_label": "Other...",
        "followup_other_hint": "Type your own answer in 1-2 sentences.",
        "followup_answer_hint": "",

        # results tab ----------------------------------------------------
        "results_title": "Found positions",
        "results_subtitle_template": "{count} active openings - sorted by relevance.",
        "results_empty_title": "No search yet",
        "results_empty_desc": "Open Setup, fill in at least the role (or your CV) and click Search positions.",
        "results_meta_company": "Company",
        "results_meta_location": "Location",
        "results_meta_posted": "Posted",
        "results_meta_source": "Source",
        "results_meta_salary": "Salary",
        "results_meta_contract": "Contract",
        "results_open_btn": "Open posting",
        "results_copy_btn": "Copy link",
        "results_copied_template": "Link copied: {url}",
        "results_save_btn": "Save as HTML",
        "results_saving": "Saving...",
        "results_save_done_template": "Saved to {path}",
        "results_save_failed_template": "Save failed: {error}",
        "results_summary_title": "AI summary",
        "results_query_template": "Query: {query}",
        "results_location_template": "Location: {location}",
        "results_dropped_note_template": "{count} link(s) were dropped during verification.",
        "results_inactive_count_template": "{count} posting(s) are still listed but no longer accepting applications, returned a 404, or could not be reached.",
        "results_inactive_pill": "No longer hiring",
        "results_inactive_tooltip": "AI Hub detected this listing is dead - the page either says it's closed (e.g. \"No longer accepting applications\"), returned a 404, or redirected to a generic placeholder.",
        "results_inactive_section_title": "Closed listings",
        "results_relaxed_pill": "Less relevant",
        "results_relaxed_tooltip": "AI Hub broadened the search (adjacent roles or nearby cities) because there were not enough strict matches for your filters. Still active - just less aligned with your CV than the top hits.",
        "results_match_pill_template": "Match {score}%",
        "results_open_skill_gap_btn": "Open skill gap analysis",
        "results_card_fit_title": "Fits",
        "results_card_concerns_title": "Possible concerns",
        "results_card_recommendation_title": "AI recommendation",

        # skill gap tab --------------------------------------------------
        "skill_gap_title": "Skill gap analysis",
        "skill_gap_subtitle": "AI compared every posting against your profile and grouped the most common requirements.",
        "skill_gap_empty_title": "No skill gap yet",
        "skill_gap_empty_desc": "Run a search with a profile (CV, bio, LinkedIn, or skills list) and AI will compute the gap once results are in.",
        "skill_gap_top_title": "Most requested skills",
        "skill_gap_top_count_template": "{count} of {total} postings",
        "skill_gap_strong_title": "Strong sides (match your profile)",
        "skill_gap_missing_title": "Missing or weaker skills",
        "skill_gap_advice_title": "AI advice",
        "skill_gap_no_strong": "AI did not detect any strong overlaps yet.",
        "skill_gap_no_missing": "AI did not detect any obvious gaps.",
        "skill_gap_no_advice": "AI has no extra advice for this run.",
        "skill_gap_skipped_no_profile": "AI did not run the skill gap analysis because no profile was provided.",

        # history tab ----------------------------------------------------
        "history_title": "Past searches",
        "history_subtitle": "Each saved search is kept on disk so you can re-open the HTML or delete the folder.",
        "history_empty_title": "No saved searches yet",
        "history_empty_desc": "Run a search and click Save as HTML to keep it for later.",
        "history_open_results_btn": "Results",
        "history_open_skill_gap_btn": "Skill gap",
        "history_open_folder_btn": "Open folder",
        "history_delete_btn": "Delete",
        "history_refresh_btn": "Refresh",
        "history_query_template": "{query}",
        "history_location_template": "{location}",
        "history_count_template": "{count} positions",

        # right-hand context panel ---------------------------------------
        "ctx_cost_title": "Session cost",
        "ctx_cost_calls_template": "{calls} calls \u00b7 {tokens} tokens",
        "ctx_cost_session_template": "~${cost:.2f} this session",
        "ctx_provider_template": "{provider} \u00b7 {model}",
        "ctx_activity_title": "Activity",
        "ctx_activity_ready": "Ready",
        "ctx_activity_searching": "Searching the web...",
        "ctx_activity_extracting": "Structuring results...",
        "ctx_activity_followups": "Asking clarifying questions...",
        "ctx_activity_waiting_user": "Waiting for your clarifications...",
        "ctx_activity_verifying": "Verifying links...",
        "ctx_activity_scoring": "Scoring matches...",
        "ctx_activity_gap": "Computing skill gap...",
        "ctx_activity_saving": "Saving HTML...",
        "ctx_activity_error": "Error",
        "ctx_quick_actions_title": "Quick actions",
        "ctx_qa_new_search": "New search",
        "ctx_qa_open_results": "Open results",
        "ctx_qa_open_skill_gap": "Open skill gap",
        "ctx_qa_show_history": "Open history",
        "ctx_qa_open_folder": "Open output folder",
        "ctx_qa_open_how_to": "How to use this assistant",
        "ctx_last_run_title": "Last search",
        "ctx_last_run_empty": "No search has been run yet.",

        # header overflow menu -------------------------------------------
        "menu_new_search": "New search",
        "menu_save_html": "Save results as HTML",
        "menu_open_folder": "Open output folder",
        "menu_show_history": "Show history",
        "menu_show_skill_gap": "Show skill gap",
        "menu_demo_load": "Show demo data",
        "menu_demo_clear": "Hide demo data",
        "demo_pill": "DEMO",
        "menu_how_to": "How to use this assistant",
        "menu_save_no_run": "Run a search first - there is nothing to save yet.",
        "menu_open_folder_no_run": "No saved searches yet - save one first.",

        # how-to dialog --------------------------------------------------
        "how_to_title": "How to use this assistant",
        "how_to_section_what": "What this section does",
        "how_to_what_text": "AI Job Search asks the model's hosted web search to find currently open positions matching your role keywords (or your CV / bio) and location. It then verifies every URL with the built-in scraper, drops any dead or expired links, scores each survivor against your profile, and aggregates a skill gap so you know what to learn or highlight in your CV.",
        "how_to_section_inputs": "Inputs you should prepare",
        "how_to_inputs_text": "At minimum: a job title (e.g. 'QA software engineer'). Optionally a CV (PDF / DOCX / TXT / HTML), a short bio about yourself, your public LinkedIn URL, your skills list, exclusions you want to skip, and the boards you want AI to search. Anything you provide makes the matches more relevant.",
        "how_to_section_sources": "Sources picker and saved profiles",
        "how_to_sources_text": "Step 6 lets you pick specific job boards (Global / Remote / Europe / CZ-SK / Tech / Freelance) and add your own URLs. Save the whole setup as a template in Step 11 so you can rerun the same search later with one click.",
        "how_to_section_quality": "Quality tips",
        "how_to_quality_text": "Bigger 'number of results' values cost more tokens and take longer (each link is HTTP-verified, scored, and a final skill-gap pass aggregates everything). The Search mode picker controls how widely AI casts the net - start with 'Smart' for synonyms, switch to 'Broad' for adjacent roles. Save your OpenAI / Anthropic key in Settings before searching.",
        "how_to_close": "Got it",

        # html labels ----------------------------------------------------
        "html_match_pill_template": "Match {score}%",
        "html_matched_label": "Why it fits",
        "html_missing_label": "What could be a problem",
        "html_recommendation_label": "AI recommendation",
        "html_skill_gap_title": "Skill gap analysis",
        "html_skill_gap_top": "Most requested skills",
        "html_skill_gap_strong": "Strong sides",
        "html_skill_gap_missing": "Missing or weaker skills",
        "html_skill_gap_advice": "AI advice",
        "html_skill_gap_count_template": "{count} of {total} postings",
        "html_search_summary_title": "Search summary",
        "html_search_summary_role": "Role",
        "html_search_summary_location": "Location",
        "html_search_summary_sources": "Sources",
        "html_search_summary_mode": "Search mode",
        "html_search_summary_seniority": "Seniority",
        "html_search_summary_salary": "Minimum salary",
    },
    "cs": {
        # sidebar / header ------------------------------------------------
        "nav_label": "AI Hled\u00e1n\u00ed pr\u00e1ce",
        "title": "AI Hled\u00e1n\u00ed pr\u00e1ce",
        "subtitle": "Pop\u011b\u0161 pozici (nebo nahraj \u017eivotopis), zvol lokalitu a AI prohled\u00e1 web po aktivn\u00edch nab\u00eddk\u00e1ch.",

        # tab labels ------------------------------------------------------
        "tab_setup": "Nastaven\u00ed",
        "tab_results": "V\u00fdsledky",
        "tab_skill_gap": "Mezera dovednost\u00ed",
        "tab_history": "Historie",

        # setup hero ------------------------------------------------------
        "setup_hero_title": "Najdi pozice, na kter\u00e9 stoj\u00ed za to reagovat",
        "setup_hero_desc": "\u0158ekni AI, co hled\u00e1\u0161. \u010c\u00edm v\u00edc kontextu d\u00e1\u0161 (\u017eivotopis, kr\u00e1tk\u00e9 bio, c\u00edlov\u00e9 kl\u00ed\u010dov\u00e9 slova), t\u00edm p\u0159esn\u011bj\u0161\u00ed shody. Ukazujeme jen aktivn\u00ed inzer\u00e1ty - mrtv\u00e9 odkazy zahod\u00edme d\u0159\u00edv, ne\u017e je uvid\u00ed\u0161.",

        # step 1 - keywords ----------------------------------------------
        "step_1_label": "KROK 1",
        "step_1_title": "Jakou roli hled\u00e1\u0161?",
        "step_1_desc": "Napi\u0161 n\u00e1zev pozice nebo kl\u00ed\u010dov\u00e1 slova. AI sama p\u0159id\u00e1 synonyma (nap\u0159. 'QA Engineer' pokryje i 'Tester' nebo 'Quality Engineer').",
        "keywords_hint": "QA software engineer, Python backend developer, data anal\u00fdza...",
        "keywords_synonyms_note": "Synonyma a p\u0159\u00edbuzn\u00e9 role se p\u0159id\u00e1vaj\u00ed automaticky.",

        # step 2 - profile -----------------------------------------------
        "step_2_label": "KROK 2",
        "step_2_title": "Tv\u016fj profil (voliteln\u00e9)",
        "step_2_desc": "P\u0159etr\u00e1hni \u017eivotopis, vlo\u017e kr\u00e1tk\u00fd popis sebe nebo URL na LinkedIn profil. M\u016f\u017ee\u0161 d\u00e1t libovolnou kombinaci - AI vyu\u017eije v\u0161e, co m\u00e1.",
        "profile_text_label": "O sob\u011b (voln\u00fd text)",
        "profile_text_hint": "Jsem QA engineer se 4 lety zku\u0161enost\u00ed v testov\u00e1n\u00ed API, automatizaci v Playwrightu a CI v GitLabu. Hled\u00e1m senior roli...",
        "profile_file_label": "Nahraj \u017eivotopis / LinkedIn export (PDF / DOCX / TXT / HTML)",
        "profile_file_drop_title": "P\u0159et\u00e1hni svoje CV sem",
        "profile_file_drop_hint": "nebo klikni a vyber z disku",
        "profile_file_no_file": "Nen\u00ed vybr\u00e1n \u017e\u00e1dn\u00fd soubor",
        "profile_file_unsupported": "Nepodporovan\u00fd typ souboru. Pou\u017eij PDF, DOCX, TXT nebo HTML.",
        "profile_file_clear": "Vy\u010distit",
        "linkedin_label": "Ve\u0159ejn\u00fd LinkedIn profil URL (voliteln\u00e9)",
        "linkedin_hint": "https://www.linkedin.com/in/tvoje-jmeno",

        # step 3 - location ----------------------------------------------
        "step_3_label": "KROK 3",
        "step_3_title": "Kde m\u00e1 AI hledat?",
        "step_3_desc": "Vyber region nebo m\u011bsto. Inzer\u00e1ty mimo zvolenou lokalitu se ignoruj\u00ed.",
        "location_preset_label": "Lokalita",
        "location_custom_label": "Vlastn\u00ed lokalita",
        "location_custom_hint": "nap\u0159. Praha + 30 km, nebo Berl\u00edn / Mnichov",

        # step 4 - technologies + seniority ------------------------------
        "step_4_label": "KROK 4",
        "step_4_title": "Technologie a dovednosti",
        "step_4_desc": "N\u00e1stroje, frameworky, certifikace nebo soft skills, kter\u00e9 ovl\u00e1d\u00e1\u0161. AI je pou\u017eije pro v\u00fdpo\u010det shody s pracovn\u00edmi nab\u00eddkami.",
        "tech_skills_label": "Technologie / skills",
        "tech_skills_hint": "Python, FastAPI, Playwright, GitLab CI, SQL, Docker...",
        "additional_experience_label": "Dal\u0161\u00ed zku\u0161enosti",
        "additional_experience_hint": "API testing, automatizace test\u016f, pr\u00e1ce s datab\u00e1zemi, CI/CD...",
        "seniority_label": "\u00darove\u0148 zku\u0161enost\u00ed",
        "seniority_any": "Cokoli",
        "seniority_junior": "Junior",
        "seniority_medior": "Medior",
        "seniority_senior": "Senior",
        "seniority_lead": "Lead",
        "skills_helper_note": "AI t\u011bmito \u00fadaji spo\u010d\u00edt\u00e1 match sk\u00f3re a doporu\u010d\u00ed, co v CV zv\u00fdraznit.",

        # step 5 - exclusions --------------------------------------------
        "step_5_label": "KROK 5",
        "step_5_title": "Co nechce\u0161 ve v\u00fdsledc\u00edch?",
        "step_5_desc": "Role, technologie, firmy nebo podm\u00ednky, kter\u00e9 m\u00e1 AI vynechat. Nevhodn\u00e9 nab\u00eddky p\u0159esko\u010d\u00ed nebo ozna\u010d\u00ed jako rizikov\u00e9.",
        "excluded_keywords_label": "Vylou\u010den\u00e1 kl\u00ed\u010dov\u00e1 slova",
        "excluded_keywords_hint": "unpaid, sales, PHP, on-site only, call centrum, senior only...",
        "excluded_companies_label": "Vylou\u010den\u00e9 firmy",
        "excluded_companies_hint": "Firma A, Firma B, agentury...",
        "excluded_locations_label": "Vylou\u010den\u00e9 lokality",
        "excluded_locations_hint": "Praha, USA, no relocation...",
        "excluded_work_types_label": "Vylou\u010den\u00e9 typy pr\u00e1ce",
        "exclude_night": "No\u010dn\u00ed sm\u011bny",
        "exclude_sales": "\u010cist\u00fd sales",
        "exclude_unpaid": "Neplacen\u00e1 st\u00e1\u017e",
        "exclude_onsite_only": "Pouze on-site",
        "exclusions_helper_note": "Vylou\u010den\u00e9 nab\u00eddky se v ulo\u017een\u00e9m HTML neztrat\u00ed - AI u nich nap\u00ed\u0161e d\u016fvod, pro\u010d byly skryty.",

        # step 6 - sources -----------------------------------------------
        "step_6_label": "KROK 6",
        "step_6_title": "Kde m\u00e1 AI hledat?",
        "step_6_desc": "Vyber pracovn\u00ed port\u00e1ly a regiony. M\u016f\u017ee\u0161 zvolit v\u00edc zdroj\u016f - AI v\u00fdsledky sjednot\u00ed, odstran\u00ed duplicity a ov\u011b\u0159\u00ed odkazy.",
        "sources_helper_note": "Ponech 'Doporu\u010den\u00e9 pro region' zapnut\u00e9, AI pou\u017eije k\u00f3dovan\u00fd v\u00fdb\u011br pro zvolenou lokalitu.",
        "sources_custom_urls_label": "Vlastn\u00ed URL (jeden odkaz na \u0159\u00e1dek)",
        "sources_custom_urls_hint": "https://firma.com/careers\nhttps://greenhouse.io/firma\n...",
        "src_category_recommended": "Doporu\u010den\u00e9",
        "src_category_global": "Glob\u00e1ln\u00ed port\u00e1ly",
        "src_category_remote": "Remote",
        "src_category_europe": "Evropa",
        "src_category_cz_sk": "\u010cesko / Slovensko",
        "src_category_tech": "Tech / Startup",
        "src_category_freelance": "Freelance / kontrakty",
        "src_recommended_for_region": "Doporu\u010den\u00e9 pro region",
        "src_linkedin_jobs": "LinkedIn Jobs",
        "src_indeed": "Indeed",
        "src_glassdoor": "Glassdoor",
        "src_google_jobs": "Google Jobs",
        "src_jooble": "Jooble",
        "src_talent_com": "Talent.com",
        "src_monster": "Monster",
        "src_careerbuilder": "CareerBuilder",
        "src_ziprecruiter": "ZipRecruiter",
        "src_simplyhired": "SimplyHired",
        "src_adzuna": "Adzuna",
        "src_themuse": "The Muse",
        "src_we_work_remotely": "We Work Remotely",
        "src_remote_ok": "Remote OK",
        "src_remotive": "Remotive",
        "src_flexjobs": "FlexJobs",
        "src_working_nomads": "Working Nomads",
        "src_himalayas": "Himalayas",
        "src_wttj": "Welcome to the Jungle / Otta",
        "src_remote_co": "Remote.co",
        "src_justremote": "JustRemote",
        "src_nodesk": "NoDesk",
        "src_jobspresso": "Jobspresso",
        "src_fourdayweek": "4 Day Week",
        "src_eures": "EURES",
        "src_eurojobs": "Eurojobs",
        "src_euraxess": "Euraxess",
        "src_jobsinnetwork": "Jobs in Network",
        "src_europe_language_jobs": "Europe Language Jobs",
        "src_stepstone": "StepStone",
        "src_pracuj_pl": "Pracuj.pl",
        "src_xing_jobs": "Xing Jobs",
        "src_karriere_at": "karriere.at",
        "src_reed_uk": "Reed.co.uk",
        "src_totaljobs": "TotalJobs",
        "src_jobs_cz": "Jobs.cz",
        "src_prace_cz": "Prace.cz",
        "src_startupjobs_cz": "StartupJobs",
        "src_atmoskop": "Atmoskop",
        "src_dobra_prace": "Dobr\u00e1 pr\u00e1ce",
        "src_profesia_sk": "Profesia",
        "src_kariera_sk": "Kari\u00e9ra.sk",
        "src_pretlak": "Pretlak",
        "src_jenprace": "JenPr\u00e1ce.cz",
        "src_it_jobs_cz": "IT.jobs.cz",
        "src_pracomat": "Pracomat",
        "src_easyjobs_cz": "EasyJobs.cz",
        "src_wttj_cz": "Welcome to the Jungle CZ",
        "src_praca_sk": "Praca.sk",
        "src_wellfound": "Wellfound / AngelList",
        "src_hn_who_is_hiring": "HN Who is Hiring",
        "src_yc_jobs": "Y Combinator Jobs",
        "src_github_hiring": "GitHub hiring posty",
        "src_stackoverflow_companies": "Stack Overflow firmy",
        "src_no_fluff_jobs": "No Fluff Jobs",
        "src_landing_jobs": "Landing.jobs",
        "src_honeypot": "Honeypot",
        "src_dice": "Dice",
        "src_builtin": "Built In",
        "src_justjoinit": "JustJoin.IT",
        "src_otta": "Otta",
        "src_techstars_jobs": "Techstars Jobs",
        "src_upwork": "Upwork",
        "src_freelancer": "Freelancer",
        "src_fiverr": "Fiverr",
        "src_toptal": "Toptal",
        "src_contra": "Contra",
        "src_malt": "Malt",
        "src_peopleperhour": "PeoplePerHour",
        "src_arc_dev": "Arc.dev",
        "src_gun_io": "Gun.io",
        "src_guru": "Guru",

        # step 7 - job age -----------------------------------------------
        "step_7_label": "KROK 7",
        "step_7_title": "Jak star\u00e9 nab\u00eddky chce\u0161 zobrazit?",
        "step_7_desc": "Star\u0161\u00ed nab\u00eddky mohou b\u00fdt m\u00e9n\u011b aktu\u00e1ln\u00ed. AI se pokus\u00ed ov\u011b\u0159it, jestli je odkaz st\u00e1le aktivn\u00ed.",
        "age_label": "St\u00e1\u0159\u00ed nab\u00eddky",
        "age_any": "Cokoli",
        "age_24h": "Posledn\u00edch 24 hodin",
        "age_3d": "Posledn\u00ed 3 dny",
        "age_7d": "Posledn\u00edch 7 dn\u00ed",
        "age_14d": "Posledn\u00edch 14 dn\u00ed",
        "age_30d": "Posledn\u00edch 30 dn\u00ed",
        "verify_links_label": "Ov\u011b\u0159ovat aktivn\u00ed odkazy",
        "show_without_date_label": "Zobrazit i nab\u00eddky bez data zve\u0159ejn\u011bn\u00ed",
        "age_helper_note": "Ka\u017ed\u00fd v\u00fdsledek se p\u0159i ov\u011b\u0159en\u00ed proklikne. Mrtv\u00e9 odkazy se zahod\u00ed, ne\u017e je uvid\u00ed\u0161.",

        # step 8 - filters (work mode + contract + count) ---------------
        "step_8_label": "KROK 8",
        "step_8_title": "Forma pr\u00e1ce, \u00favazek a po\u010det v\u00fdsledk\u016f",
        "step_8_desc": "Voliteln\u00e9 filtry. Nech \"Cokoli\", pokud na tom nez\u00e1le\u017e\u00ed.",
        "work_mode_label": "Forma pr\u00e1ce",
        "contract_label": "Typ \u00favazku",
        "contract_hpp": "HPP",
        "contract_ico": "I\u010cO",
        "contract_contract": "Kontrakt",
        "contract_dpp_dpc": "DPP / DP\u010c",
        "contract_internship": "St\u00e1\u017e",
        "contract_freelance": "Freelance",
        "max_results_label": "Po\u010det aktivn\u00edch nab\u00eddek, kter\u00e9 chce\u0161 st\u00e1hnout",
        "max_results_hint": "Tohle je c\u00edlov\u00fd po\u010det nab\u00eddek, na kter\u00e9 se opravdu d\u00e1 p\u0159ihl\u00e1sit. AI Hub na pozad\u00ed sahne pro v\u00edc kandid\u00e1t\u016f, ov\u011b\u0159\u00ed ka\u017ed\u00fd odkaz a mrtv\u00e9 odst\u0159ihne \u2013 tak\u017ee 15 tady znamen\u00e1 a\u017e 15 st\u00e1le otev\u0159en\u00fdch (plus p\u00e1r uzav\u0159en\u00fdch pro p\u0159ehled). V\u011bt\u0161\u00ed \u010d\u00edsla stoj\u00ed v\u00edc token\u016f.",

        # location presets -----------------------------------------------
        "loc_any": "Kdekoli",
        "loc_remote_world": "Remote (cel\u00fd sv\u011bt)",
        "loc_eu": "Evropsk\u00e1 unie",
        "loc_usa": "Spojen\u00e9 st\u00e1ty",
        "loc_uk": "Spojen\u00e9 kr\u00e1lovstv\u00ed",
        "loc_cz": "\u010cesk\u00e1 republika",
        "loc_sk": "Slovensko",
        "loc_de": "N\u011bmecko",
        "loc_at": "Rakousko",
        "loc_pl": "Polsko",
        "loc_praha": "Praha",
        "loc_brno": "Brno",
        "loc_ostrava": "Ostrava",
        "loc_custom": "Vlastn\u00ed (voln\u00fd text)...",

        # work modes -----------------------------------------------------
        "mode_any": "Cokoli",
        "mode_remote": "Remote",
        "mode_hybrid": "Hybridn\u00ed",
        "mode_onsite": "Na pracovi\u0161ti",

        # step 9 - search mode -------------------------------------------
        "step_9_label": "KROK 9",
        "step_9_title": "Re\u017eim hled\u00e1n\u00ed",
        "step_9_desc": "Jak \u0161iroce m\u00e1 AI hledat pracovn\u00ed nab\u00eddky?",
        "mode_exact": "P\u0159esn\u00e9 shody",
        "mode_exact_desc": "Hled\u00e1 hlavn\u011b p\u0159esn\u00fd n\u00e1zev role a p\u0159esn\u00e9 technologie.",
        "mode_smart": "Chytr\u00e9 podobn\u00e9 role",
        "mode_smart_desc": "AI p\u0159id\u00e1 synonyma a p\u0159\u00edbuzn\u00e9 pozice.",
        "mode_broad": "\u0160irok\u00e9 hled\u00e1n\u00ed",
        "mode_broad_desc": "AI hled\u00e1 i role, kter\u00e9 nejsou \u00fapln\u011b stejn\u00e9, ale mohou odpov\u00eddat tv\u00fdm zku\u0161enostem.",
        "mode_discovery": "Kari\u00e9rn\u00ed objevov\u00e1n\u00ed",
        "mode_discovery_desc": "AI navrhne i jin\u00e9 sm\u011bry, kter\u00e9 by se k tv\u00e9mu profilu mohly hodit.",

        # step 10 - salary + output language ----------------------------
        "step_10_label": "KROK 10",
        "step_10_title": "Plat a jazyk",
        "step_10_desc": "Minim\u00e1ln\u00ed plat je m\u011bkk\u00fd filtr - AI preferuje l\u00e9pe placen\u00e9 nab\u00eddky, ale nezahazuje ty bez uveden\u00e9ho platu.",
        "salary_min_label": "Minim\u00e1ln\u00ed plat (m\u011bs\u00ed\u010dn\u011b)",
        "salary_currency_label": "M\u011bna",
        "currency_any": "Nefiltrovat",
        "salary_helper_note": "Nastav 0 pro ignorov\u00e1n\u00ed. Nab\u00eddky bez uveden\u00e9ho platu z\u016fst\u00e1vaj\u00ed, ale jsou ozna\u010den\u00e9 v HTML reportu.",
        "output_lang_label": "Jazyk v\u00fdstupu",
        "output_lang_auto": "Auto (jazyk UI)",
        "output_lang_en": "Angli\u010dtina",
        "output_lang_cs": "\u010ce\u0161tina",

        # step 11 - summary + run ---------------------------------------
        "step_11_label": "KROK 11",
        "step_11_title": "Souhrn a spu\u0161t\u011bn\u00ed",
        "step_11_desc": "Zkontroluj nastaven\u00ed a spus\u0165 hled\u00e1n\u00ed pracovn\u00edch nab\u00eddek.",
        "summary_role_label": "Role",
        "summary_location_label": "Lokalita",
        "summary_seniority_label": "Seniorita",
        "summary_work_mode_label": "Forma pr\u00e1ce",
        "summary_contract_label": "\u00davazek",
        "summary_salary_label": "Minim\u00e1ln\u00ed plat",
        "summary_sources_label": "Zdroje",
        "summary_results_label": "Po\u010det v\u00fdsledk\u016f",
        "summary_mode_label": "Re\u017eim",
        "summary_age_label": "St\u00e1\u0159\u00ed nab\u00eddky",
        "summary_output_lang_label": "Jazyk v\u00fdstupu",
        "summary_value_unset": "Nezad\u00e1no",
        "summary_value_any": "Cokoli",
        "summary_sources_recommended": "Doporu\u010den\u00e9 pro region",
        "summary_sources_count_template": "{count} zdroj\u016f",
        "summary_salary_value_template": "{amount} {currency}",
        "run_more_btn_save_template": "Ulo\u017eit jako \u0161ablonu",
        "run_more_btn_clear": "Vymazat formul\u00e1\u0159",
        "run_more_btn_load_last": "Na\u010d\u00edst posledn\u00ed hled\u00e1n\u00ed",

        # step 12 - saved profiles --------------------------------------
        "step_12_label": "KROK 12",
        "step_12_title": "Ulo\u017een\u00e9 profily hled\u00e1n\u00ed",
        "step_12_desc": "Ulo\u017e si nastaven\u00ed hled\u00e1n\u00ed a p\u0159\u00ed\u0161t\u011b ho spus\u0165 jedn\u00edm kliknut\u00edm.",
        "profiles_empty": "Zat\u00edm \u017e\u00e1dn\u00fd ulo\u017een\u00fd profil. Pou\u017eij 'Ulo\u017eit jako \u0161ablonu' v\u00fd\u0161e, ab\u016fchom toto nastaven\u00ed m\u011bli na p\u0159\u00ed\u0161t\u011b.",
        "profile_save_dialog_title": "Ulo\u017eit profil hled\u00e1n\u00ed",
        "profile_save_dialog_label": "N\u00e1zev profilu",
        "profile_save_dialog_hint": "QA Automation Remote Europe",
        "profile_save_btn": "Ulo\u017eit profil",
        "profile_cancel_btn": "Zru\u0161it",
        "profile_last_run_template": "Posledn\u00ed spu\u0161t\u011bn\u00ed: {when}",
        "profile_never_run": "Je\u0161t\u011b nespou\u0161t\u011bno",
        "profile_run_again": "Spustit znovu",
        "profile_edit": "Upravit",
        "profile_duplicate": "Duplikovat",
        "profile_delete": "Smazat",
        "profile_saved_toast_template": "Profil '{name}' ulo\u017een.",
        "profile_loaded_toast_template": "Profil '{name}' na\u010dten.",
        "profile_deleted_toast_template": "Profil '{name}' smaz\u00e1n.",
        "profile_duplicate_suffix": " (kopie)",
        "profile_save_failed_template": "Profil se nepoda\u0159ilo ulo\u017eit: {error}",
        "profile_load_last_no_search": "\u017d\u00e1dn\u00e9 minul\u00e9 hled\u00e1n\u00ed k na\u010dten\u00ed.",
        "profile_form_cleared": "Formul\u00e1\u0159 vymaz\u00e1n.",

        # footer ---------------------------------------------------------
        "run_btn": "Hledat pozice",
        "run_running": "Prohled\u00e1v\u00e1m web...",
        "run_followups": "P\u0159ipravuji up\u0159es\u0148uj\u00edc\u00ed ot\u00e1zky...",
        "run_extracting": "Strukturalizuju v\u00fdsledky...",
        "run_verifying": "Ov\u011b\u0159uji odkazy...",
        "run_scoring": "Po\u010d\u00edt\u00e1m shodu s profilem...",
        "run_gap": "Sestavuji skill gap...",
        "run_disabled_hint": "Doplnit n\u00e1zev pozice (nebo \u017eivotopis / bio), ab\u016fch mohl/a hledat.",
        "error_no_key_template": "API kl\u00ed\u010d pro {provider} je\u0161t\u011b nen\u00ed ulo\u017een. Otev\u0159i Nastaven\u00ed a p\u0159idej ho.",
        "search_failed_template": "Hled\u00e1n\u00ed selhalo: {error}",
        "search_cancelled": "Hled\u00e1n\u00ed zru\u0161eno.",
        "search_done_template": "Na\u0161el jsem {count} aktivn\u00edch pozic ({dropped} odkaz(\u016f) jsem zahodil, proto\u017ee byly mrtv\u00e9 nebo p\u0159esm\u011brovan\u00e9).",
        "search_done_no_drops_template": "Na\u0161el jsem {count} aktivn\u00edch pozic.",
        "search_zero_results": "AI nena\u0161la \u017e\u00e1dnou pozici pro tento dotaz. Zkus \u0161ir\u0161\u00ed kl\u00ed\u010dov\u00e1 slova nebo jinou lokalitu.",

        "footer_ask_followups_label": "Nejd\u0159\u00edv se zeptat na up\u0159esn\u011bn\u00ed",
        "footer_ask_followups_hint": (
            "Kdy\u017e n\u011bco chyb\u00ed nebo si AI nen\u00ed jist\u00e1, "
            "rad\u011bji se zept\u00e1, ne\u017e aby si dom\u00fd\u0161lela. "
            "Vypni, kdy\u017e chce\u0161 modal p\u0159esko\u010dit."
        ),
        "followup_title": "Rychl\u00e9 up\u0159esn\u011bn\u00ed",
        "followup_intro": (
            "Ne\u017e spust\u00edm hled\u00e1n\u00ed, chci si pot\u0159\u00e1st p\u00e1r v\u011bc\u00ed, "
            "abych necelovala. Vyber jednu nebo v\u00edce mo\u017enost\u00ed, nebo "
            "pou\u017eij Vlastn\u00ed... a vepi\u0161 si svoji odpov\u011b\u010f. "
            "P\u0159esko\u010dit nech\u00e1 pole pr\u00e1zdn\u00e9."
        ),
        "followup_skip_btn": "P\u0159esko\u010dit v\u0161e",
        "followup_continue_btn": "Spustit hled\u00e1n\u00ed",
        "followup_cancel": "Zru\u0161it",
        "followup_other_label": "Vlastn\u00ed...",
        "followup_other_hint": "Vepi\u0161 si vlastn\u00ed odpov\u011b\u010f v 1-2 v\u011bt\u00e1ch.",
        "followup_answer_hint": "",

        # results tab ----------------------------------------------------
        "results_title": "Nalezen\u00e9 pozice",
        "results_subtitle_template": "{count} aktivn\u00edch nab\u00eddek - se\u0159azeno podle relevance.",
        "results_empty_title": "Zat\u00edm \u017e\u00e1dn\u00e9 hled\u00e1n\u00ed",
        "results_empty_desc": "Otev\u0159i Nastaven\u00ed, doplnit aspo\u0148 roli (nebo \u017eivotopis) a klikni na Hledat pozice.",
        "results_meta_company": "Firma",
        "results_meta_location": "Lokalita",
        "results_meta_posted": "Vlo\u017eeno",
        "results_meta_source": "Zdroj",
        "results_meta_salary": "Plat",
        "results_meta_contract": "\u00davazek",
        "results_open_btn": "Otev\u0159\u00edt inzer\u00e1t",
        "results_copy_btn": "Kop\u00edrovat odkaz",
        "results_copied_template": "Odkaz zkop\u00edrov\u00e1n: {url}",
        "results_save_btn": "Ulo\u017eit jako HTML",
        "results_saving": "Ukl\u00e1d\u00e1m...",
        "results_save_done_template": "Ulo\u017eeno do {path}",
        "results_save_failed_template": "Ulo\u017een\u00ed selhalo: {error}",
        "results_summary_title": "Shrnut\u00ed od AI",
        "results_query_template": "Dotaz: {query}",
        "results_location_template": "Lokalita: {location}",
        "results_dropped_note_template": "{count} odkaz(\u016f) bylo b\u011bhem ov\u011b\u0159ov\u00e1n\u00ed zahozeno.",
        "results_inactive_count_template": "{count} nab\u00eddka(y) je v seznamu, ale u\u017e nep\u0159ij\u00edm\u00e1 \u017e\u00e1dosti, vrac\u00ed chybu 404 nebo nejde otev\u0159\u00edt.",
        "results_inactive_pill": "U\u017e nenab\u00edr\u00e1",
        "results_inactive_tooltip": "AI Hub zjistil, \u017ee tahle nab\u00eddka u\u017e neplat\u00ed \u2013 str\u00e1nka bu\u010f \u0159\u00edk\u00e1, \u017ee je uzav\u0159en\u00e1 (nap\u0159. \u201eU\u017e nep\u0159ij\u00edm\u00e1 \u017e\u00e1dosti\u201c), vrac\u00ed chybu 404, nebo p\u0159esm\u011brov\u00e1v\u00e1 na obecn\u00fd placeholder.",
        "results_inactive_section_title": "Uzav\u0159en\u00e9 nab\u00eddky",
        "results_relaxed_pill": "M\u00e9n\u011b relevantn\u00ed",
        "results_relaxed_tooltip": "AI Hub roz\u0161\u00ed\u0159il hled\u00e1n\u00ed (sousedn\u00ed role nebo bl\u00edzk\u00e1 m\u011bsta), proto\u017ee p\u0159esn\u00fdch shod podle tv\u00fdch filtr\u016f nebylo dost. Po\u0159\u00e1d aktivn\u00ed - jen m\u00e9n\u011b s tv\u00fdm CV.",
        "results_match_pill_template": "Shoda {score} %",
        "results_open_skill_gap_btn": "Otev\u0159\u00edt skill gap anal\u00fdzu",
        "results_card_fit_title": "Sed\u00ed",
        "results_card_concerns_title": "Co m\u016f\u017ee b\u00fdt probl\u00e9m",
        "results_card_recommendation_title": "Doporu\u010den\u00ed AI",

        # skill gap tab --------------------------------------------------
        "skill_gap_title": "Skill gap anal\u00fdza",
        "skill_gap_subtitle": "AI porovnala v\u0161echny nab\u00eddky s tv\u00fdm profilem a se\u0159adila nej\u010dast\u011bj\u0161\u00ed po\u017eadavky.",
        "skill_gap_empty_title": "Zat\u00edm \u017e\u00e1dn\u00e1 anal\u00fdza",
        "skill_gap_empty_desc": "Spus\u0165 hled\u00e1n\u00ed s vypln\u011bn\u00fdm profilem (CV, bio, LinkedIn nebo seznam dovednost\u00ed) a AI po na\u010dten\u00ed v\u00fdsledk\u016f sestav\u00ed gap.",
        "skill_gap_top_title": "Nej\u010dast\u011bji po\u017eadovan\u00e9 dovednosti",
        "skill_gap_top_count_template": "{count} z {total} nab\u00eddek",
        "skill_gap_strong_title": "Siln\u00e9 str\u00e1nky (shoda s profilem)",
        "skill_gap_missing_title": "Chyb\u011bj\u00edc\u00ed nebo slab\u0161\u00ed dovednosti",
        "skill_gap_advice_title": "Doporu\u010den\u00ed AI",
        "skill_gap_no_strong": "AI zat\u00edm nena\u0161la \u017e\u00e1dn\u00e9 v\u00fdrazn\u00e9 p\u0159esahy.",
        "skill_gap_no_missing": "AI nena\u0161la \u017e\u00e1dn\u00e9 z\u0159ejm\u00e9 mezery.",
        "skill_gap_no_advice": "AI nem\u00e1 \u017e\u00e1dn\u00e9 dal\u0161\u00ed doporu\u010den\u00ed pro tento b\u011bh.",
        "skill_gap_skipped_no_profile": "AI nespustila skill gap anal\u00fdzu, proto\u017ee nebyl zad\u00e1n \u017e\u00e1dn\u00fd profil.",

        # history tab ----------------------------------------------------
        "history_title": "P\u0159edchoz\u00ed hled\u00e1n\u00ed",
        "history_subtitle": "Ka\u017ed\u00e9 ulo\u017een\u00e9 hled\u00e1n\u00ed z\u016fst\u00e1v\u00e1 na disku, ab\u016fchom mohl/a otev\u0159\u00edt HTML nebo slo\u017eku smazat.",
        "history_empty_title": "Zat\u00edm \u017e\u00e1dn\u00e9 ulo\u017een\u00e9 hled\u00e1n\u00ed",
        "history_empty_desc": "Spus\u0165 hled\u00e1n\u00ed a klikni na Ulo\u017eit jako HTML, ab\u016fchom ho m\u011bli na pozd\u011bji.",
        "history_open_results_btn": "V\u00fdsledky",
        "history_open_skill_gap_btn": "Mezera",
        "history_open_folder_btn": "Otev\u0159\u00edt slo\u017eku",
        "history_delete_btn": "Smazat",
        "history_refresh_btn": "Obnovit",
        "history_query_template": "{query}",
        "history_location_template": "{location}",
        "history_count_template": "{count} pozic",

        # right-hand context panel ---------------------------------------
        "ctx_cost_title": "N\u00e1klady relace",
        "ctx_cost_calls_template": "{calls} vol\u00e1n\u00ed \u00b7 {tokens} token\u016f",
        "ctx_cost_session_template": "~${cost:.2f} v t\u00e9to relaci",
        "ctx_provider_template": "{provider} \u00b7 {model}",
        "ctx_activity_title": "Aktivita",
        "ctx_activity_ready": "P\u0159ipraveno",
        "ctx_activity_searching": "Prohled\u00e1v\u00e1m web...",
        "ctx_activity_extracting": "Strukturalizuju v\u00fdsledky...",
        "ctx_activity_followups": "P\u0159ipravuji up\u0159es\u0148uj\u00edc\u00ed ot\u00e1zky...",
        "ctx_activity_waiting_user": "\u010cek\u00e1m na tv\u00e9 odpov\u011bdi...",
        "ctx_activity_verifying": "Ov\u011b\u0159uji odkazy...",
        "ctx_activity_scoring": "Po\u010d\u00edt\u00e1m shodu...",
        "ctx_activity_gap": "Sestavuji skill gap...",
        "ctx_activity_saving": "Ukl\u00e1d\u00e1m HTML...",
        "ctx_activity_error": "Chyba",
        "ctx_quick_actions_title": "Rychl\u00e9 akce",
        "ctx_qa_new_search": "Nov\u00e9 hled\u00e1n\u00ed",
        "ctx_qa_open_results": "Otev\u0159\u00edt v\u00fdsledky",
        "ctx_qa_open_skill_gap": "Otev\u0159\u00edt skill gap",
        "ctx_qa_show_history": "Otev\u0159\u00edt historii",
        "ctx_qa_open_folder": "Otev\u0159\u00edt v\u00fdstupn\u00ed slo\u017eku",
        "ctx_qa_open_how_to": "Jak pou\u017e\u00edvat tohoto asistenta",
        "ctx_last_run_title": "Posledn\u00ed hled\u00e1n\u00ed",
        "ctx_last_run_empty": "Hled\u00e1n\u00ed je\u0161t\u011b neprob\u011bhlo.",

        # header overflow menu -------------------------------------------
        "menu_new_search": "Nov\u00e9 hled\u00e1n\u00ed",
        "menu_save_html": "Ulo\u017eit v\u00fdsledky jako HTML",
        "menu_open_folder": "Otev\u0159\u00edt v\u00fdstupn\u00ed slo\u017eku",
        "menu_show_history": "Otev\u0159\u00edt historii",
        "menu_show_skill_gap": "Otev\u0159\u00edt skill gap",
        "menu_demo_load": "Zobrazit demo data",
        "menu_demo_clear": "Skr\u00fdt demo data",
        "demo_pill": "DEMO",
        "menu_how_to": "Jak pou\u017e\u00edvat tohoto asistenta",
        "menu_save_no_run": "Spus\u0165 nejprve hled\u00e1n\u00ed - zat\u00edm nen\u00ed co ukl\u00e1dat.",
        "menu_open_folder_no_run": "Zat\u00edm \u017e\u00e1dn\u00e9 ulo\u017een\u00e9 hled\u00e1n\u00ed - nejprve n\u011bjak\u00e9 ulo\u017e.",

        # how-to dialog --------------------------------------------------
        "how_to_title": "Jak pou\u017e\u00edvat tohoto asistenta",
        "how_to_section_what": "Co tahle sekce d\u011bl\u00e1",
        "how_to_what_text": "AI Hled\u00e1n\u00ed pr\u00e1ce vyu\u017e\u00edv\u00e1 vestav\u011bn\u00fd web search providera, aby na\u0161la aktu\u00e1ln\u011b otev\u0159en\u00e9 pozice. Ka\u017edou URL ov\u011b\u0159\u00ed, mrtv\u00e9 odkazy zahod\u00ed, ka\u017edou zb\u00fdvaj\u00edc\u00ed pozici porovn\u00e1 s tv\u00fdm profilem (match sk\u00f3re) a nakonec sestav\u00ed skill gap, ab\u016f v\u011bd\u011bl/a, co se nau\u010dit nebo co zv\u00fdraznit v CV.",
        "how_to_section_inputs": "Co si p\u0159ichystat",
        "how_to_inputs_text": "Minim\u00e1ln\u011b: n\u00e1zev pozice (nap\u0159. 'QA software engineer'). Voliteln\u011b: \u017eivotopis, kr\u00e1tk\u00e9 bio, LinkedIn URL, seznam dovednost\u00ed, exclusion list a vybran\u00e9 port\u00e1ly. \u010c\u00edm v\u00edc \u00fadaj\u016f d\u00e1\u0161, t\u00edm p\u0159esn\u011bj\u0161\u00ed shody.",
        "how_to_section_sources": "V\u00fdb\u011br zdroj\u016f a ulo\u017een\u00e9 profily",
        "how_to_sources_text": "Krok 6 ti umo\u017e\u0148uje vybrat konkr\u00e9tn\u00ed port\u00e1ly (Glob\u00e1ln\u00ed / Remote / Evropa / CZ-SK / Tech / Freelance) a p\u0159idat vlastn\u00ed URL. V Kroku 11 m\u016f\u017ee\u0161 cel\u00e9 nastaven\u00ed ulo\u017eit jako \u0161ablonu a p\u0159\u00ed\u0161t\u011b znovu spustit jedn\u00edm kliknut\u00edm.",
        "how_to_section_quality": "Tipy na kvalitu",
        "how_to_quality_text": "V\u011bt\u0161\u00ed po\u010det v\u00fdsledk\u016f stoj\u00ed v\u00edc token\u016f a trv\u00e1 d\u00e9l (ka\u017ed\u00fd odkaz se ov\u011b\u0159uje, scoruje a fin\u00e1ln\u00ed skill-gap pas agreguje v\u0161echno). Re\u017eim hled\u00e1n\u00ed \u0159\u00edd\u00ed, jak \u0161iroce m\u00e1 AI hledat - za\u010dni se 'Chytr\u00fdm' re\u017eimem pro synonyma a p\u0159epni na '\u0160irok\u00fd' pro p\u0159\u00edbuzn\u00e9 role. Ne\u017e za\u010dne\u0161, ulo\u017e si OpenAI / Anthropic kl\u00ed\u010d v Nastaven\u00ed.",
        "how_to_close": "Rozum\u00edm",

        # html labels ----------------------------------------------------
        "html_match_pill_template": "Shoda {score} %",
        "html_matched_label": "Sed\u00ed",
        "html_missing_label": "Co m\u016f\u017ee b\u00fdt probl\u00e9m",
        "html_recommendation_label": "Doporu\u010den\u00ed AI",
        "html_skill_gap_title": "Skill gap anal\u00fdza",
        "html_skill_gap_top": "Nej\u010dast\u011bji po\u017eadovan\u00e9 dovednosti",
        "html_skill_gap_strong": "Siln\u00e9 str\u00e1nky",
        "html_skill_gap_missing": "Chyb\u011bj\u00edc\u00ed nebo slab\u0161\u00ed dovednosti",
        "html_skill_gap_advice": "Doporu\u010den\u00ed AI",
        "html_skill_gap_count_template": "{count} z {total} nab\u00eddek",
        "html_search_summary_title": "Souhrn hled\u00e1n\u00ed",
        "html_search_summary_role": "Role",
        "html_search_summary_location": "Lokalita",
        "html_search_summary_sources": "Zdroje",
        "html_search_summary_mode": "Re\u017eim",
        "html_search_summary_seniority": "Seniorita",
        "html_search_summary_salary": "Minim\u00e1ln\u00ed plat",
    },
}


def s(lang: str) -> dict[str, str]:
    return STRINGS.get(lang) or STRINGS["en"]
